set_attack_value(AT_DSPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_DSPECIAL_2, AG_SPRITE, sprite_get("phonedance"));
set_attack_value(AT_DSPECIAL_2, AG_NUM_WINDOWS, 4);
set_attack_value(AT_DSPECIAL_2, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_DSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("phonedance_hurt"));
set_attack_value(AT_DSPECIAL_2, AG_OFF_LEDGE, 1);

set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_LENGTH, 20);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 7);

set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_LENGTH, 20);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAME_START, 7);

set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_SFX, sound_get("superdeathkilldance"));
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_SFX_FRAME, 14);

set_window_value(AT_DSPECIAL_2, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 4, AG_WINDOW_LENGTH, 40);
set_window_value(AT_DSPECIAL_2, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DSPECIAL_2, 4, AG_WINDOW_ANIM_FRAME_START, 14);

set_num_hitboxes(AT_DSPECIAL_2, 7);

set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_WINDOW, 4);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_LIFETIME, 398);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_WIDTH, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HEIGHT, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_SPRITE, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_MASK, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_ANIM_SPEED, .4);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_GRAVITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_HSPEED, 6);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_ANGLE, 50);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HIT_SFX, sound_get("hit"));
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PROJECTILE_DESTROY_EFFECT, ouchiemama );
set_hitbox_value(AT_DSPECIAL_2, 1, HG_VISUAL_EFFECT, ouchiemama);


set_hitbox_value(AT_DSPECIAL_2, 2, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_WINDOW, 4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_LIFETIME, 398);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_WIDTH, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HEIGHT, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_SPRITE, sprite_get("chaosdash"));
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_MASK, sprite_get("chaosdash"));
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, .4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_GRAVITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_HSPEED, 6);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_ANGLE, 50);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HIT_SFX, sound_get("hit"));
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_DESTROY_EFFECT, ouchiemamachaos );
set_hitbox_value(AT_DSPECIAL_2, 2, HG_VISUAL_EFFECT, ouchiemamachaos);


set_hitbox_value(AT_DSPECIAL_2, 3, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_WINDOW, 4);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_LIFETIME, 398);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_WIDTH, 1);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HEIGHT, 1);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_SPRITE, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_MASK, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_ANIM_SPEED, .4);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_GRAVITY, 0.20);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_HSPEED, 6);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_VSPEED, 7);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_DAMAGE, 4);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_ANGLE, 50);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HIT_SFX, sound_get("hit"));
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PROJECTILE_DESTROY_EFFECT, ouchiemama );
set_hitbox_value(AT_DSPECIAL_2, 3, HG_VISUAL_EFFECT, ouchiemama);

set_hitbox_value(AT_DSPECIAL_2, 4, HG_WINDOW_CREATION_FRAME, 17);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_WINDOW, 4);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_LIFETIME, 398);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_WIDTH, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HEIGHT, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_SPRITE, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_MASK, sprite_get("dash"));
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_ANIM_SPEED, .4);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_GRAVITY, 0.69);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_ANGLE, 280);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_KNOCKBACK_SCALING, 0.50);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HIT_SFX, sound_get("hit"));
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_DESTROY_EFFECT, ouchiemama );
set_hitbox_value(AT_DSPECIAL_2, 4, HG_VISUAL_EFFECT, ouchiemama);