sprite_change_offset("idle", 19, 39);
sprite_change_offset("hurt", 19, 38);
sprite_change_offset("bighurt", 23, 36);
sprite_change_offset("uphurt", 12, 36);
sprite_change_offset("downhurt", 13, 41);
sprite_change_offset("bouncehurt", 16, 15);
sprite_change_offset("spinhurt", 16, 28);
sprite_change_offset("hurtground", 19, 38);
sprite_change_offset("crouch", 14, 34);
sprite_change_offset("walk", 16, 37);
sprite_change_offset("walkturn", 14, 37);
sprite_change_offset("dash", 20, 26);
sprite_change_offset("dashstart", 19, 32);
sprite_change_offset("dashstop", 24, 39);
sprite_change_offset("dashturn", 22, 37);

sprite_change_offset("jumpstart", 12, 29);
sprite_change_offset("jump", 16, 52);
sprite_change_offset("doublejump", 23, 43);
sprite_change_offset("walljump", 15, 41);
sprite_change_offset("pratfall", 15, 53);
sprite_change_offset("land", 14, 29);
sprite_change_offset("landinglag", 19, 26);

sprite_change_offset("parry", 13, 36);
sprite_change_offset("roll_forward", 15, 34);
sprite_change_offset("roll_backward", 15, 34);
sprite_change_offset("airdodge", 13, 35);
// sprite_change_offset("waveland", 13, 29);
sprite_change_offset("waveland", 26, 28);
sprite_change_offset("tech", 26, 28);

sprite_change_offset("jab", 20, 34, true);
sprite_change_offset("dattack", 28, 44, true);
sprite_change_offset("ftilt", 18, 35, true);
sprite_change_offset("dtilt", 34, 31, true);
sprite_change_offset("utilt", 27, 38, true);
sprite_change_offset("nair", 20, 36, true);
sprite_change_offset("fair", 20, 35, true);
sprite_change_offset("bair", 42, 39, true);
sprite_change_offset("uair", 22, 42, true);
sprite_change_offset("dair", 22, 54, true);
sprite_change_offset("fstrong", 19, 31, true);
sprite_change_offset("ustrong", 26, 111, true);
sprite_change_offset("dstrong", 39, 39, true);

sprite_change_offset("nspecial", 13, 40, true);
sprite_change_offset("nspecial_air", 13, 40, true);
sprite_change_offset("fthrow", 20, 36, true);
sprite_change_offset("fthrow_air", 26, 38, true);
sprite_change_offset("nthrow", 19, 34, true);
sprite_change_offset("nthrow_air", 19, 34, true);
sprite_change_offset("uthrow", 12, 40, true);
sprite_change_offset("uthrow_air", 12, 40, true);
sprite_change_offset("dthrow", 18, 36, true);
sprite_change_offset("dthrow_air", 18, 36, true);

sprite_change_offset("fspecial", 21, 37, true);
sprite_change_offset("fspecial_air", 21, 37, true);
sprite_change_offset("fspecial_sparkle", 29, 35);
sprite_change_offset("fspecial_wand", 21, 31);
sprite_change_offset("uspecial", 16, 37, true);
sprite_change_offset("uspecial_air", 16, 37, true);
sprite_change_offset("dspecial", 21, 41, true);
sprite_change_offset("taunt", 18, 35);

sprite_change_offset("plat", 25, 12);

sprite_change_offset("wandeffect", 14, 14);
sprite_change_offset("wandeffect_EA", 14, 14);
sprite_change_offset("wandeffect_abyss", 14, 14);
sprite_change_offset("ironthorn", 16, 9);
sprite_change_offset("geopebble", 12, 11);
sprite_change_offset("bullet_seed", 7, 5);
sprite_change_offset("blastseed", 12, 12);
sprite_change_offset("blastseed_article", 36*2, 41*2);
sprite_change_offset("blastseed_mask", 36*2, 41*2);
sprite_change_offset("dig_dirt_burst", 10, 41);
sprite_change_offset("blastseed_explosion", 18, 32);
sprite_change_offset("timegearglow", 14, 14);
sprite_change_offset("escapebeam", 14, 0);
sprite_change_offset("dattackeffect", 15, 63);
sprite_change_offset("nspecial_ui", 10, 5);
sprite_change_offset("emera_dust", 7, 15);
sprite_change_offset("emera_dust_mask", 7, 16);
sprite_change_offset("emera", 7, 11);
sprite_change_offset("dthrow_trail", 18, 36);

sprite_change_offset("grov_lastresort01", 27, 39);
sprite_change_offset("grov_lastresort02", 27, 39);
sprite_change_offset("feri_costume_grovyle", 50, 70);
sprite_change_offset("GFZ_Grovyle", 18, 41);
sprite_change_offset("miiverse_grovyle", 60, 30);
sprite_change_offset("grovyle_cheer", 16*2, 35*2);
sprite_change_offset("grovyle_cheer_alt0", 16*2, 35*2);
sprite_change_offset("amber_cheer", 16*2, 35*2);
sprite_change_offset("walk_hikaruclone", 16*2, 37*2);
sprite_change_offset("dair_hikaruclone", 22*2, 54*2);
sprite_change_offset("tauntHikaru", 18, 35);