sprite_change_offset("idle", 40/2, 78/2, true);
sprite_change_offset("hurt", 40/2, 78/2, true);
sprite_change_offset("hurtground", 40/2, 78/2, true);
sprite_change_offset("uphurt", 40/2, 78/2, true);
sprite_change_offset("downhurt", 40/2, 78/2, true);
sprite_change_offset("bouncehurt", 40/2, 78/2, true);
sprite_change_offset("bighurt", 40/2, 78/2, true);
sprite_change_offset("crouch", 40/2, 78/2, true);
sprite_change_offset("walk", 40/2, 78/2, true);
sprite_change_offset("walkturn", 40/2, 78/2, true);
sprite_change_offset("dash", 40/2, 78/2, true);
sprite_change_offset("dashstart", 40/2, 78/2, true);
sprite_change_offset("dashstop", 40/2, 78/2, true);
sprite_change_offset("dashturn", 40/2, 78/2, true);

sprite_change_offset("jumpstart", 40/2, 78/2, true);
sprite_change_offset("jump", 40, 58, true);
sprite_change_offset("doublejump", 20, 30, true);
sprite_change_offset("doublejump_backward", 20, 30, true);
sprite_change_offset("walljump", 40, 58, true);
sprite_change_offset("pratfall", 40, 58, true);
sprite_change_offset("land", 40/2, 78/2, true);
sprite_change_offset("landinglag", 40/2, 78/2, true);

sprite_change_offset("parry", 40/2, 78/2, true);
sprite_change_offset("roll_forward", 40/2, 78/2, true);
sprite_change_offset("roll_backward", 40/2, 78/2, true);
sprite_change_offset("airdodge", 40/2, 78/2, true);
sprite_change_offset("airdodge_back", 40/2, 78/2, true);
sprite_change_offset("airdodge_upback", 40/2, 78/2, true);
sprite_change_offset("waveland", 40/2, 78/2, true);
sprite_change_offset("tech", 40/2, 78/2, true);

sprite_change_offset("jab", 40, 58, true);
sprite_change_offset("dattack", 40, 58, true);
sprite_change_offset("dattack_mc", 40, 58, true);
sprite_change_offset("ftilt", 40, 58, true);
sprite_change_offset("dtilt", 30, 59, true);
sprite_change_offset("utilt", 40, 58, true);
sprite_change_offset("nair", 40, 58, true);
sprite_change_offset("fair", 40, 58, true);
sprite_change_offset("bair", 40, 58, true);
sprite_change_offset("uair", 40, 58, true);
sprite_change_offset("uair2", 40, 58, true);
sprite_change_offset("uair3", 40, 58, true);
sprite_change_offset("dair", 40, 58, true);
sprite_change_offset("dair2", 40, 58, true);
sprite_change_offset("dair3", 40, 58, true);
sprite_change_offset("fstrong", 40, 58, true);
sprite_change_offset("fstrong_planet", 40, 58, true);
sprite_change_offset("fstrong_melon", 40, 58, true);
sprite_change_offset("fstrong_golf", 40, 58, true);
sprite_change_offset("fstrong_anvil", 40, 58, true);
sprite_change_offset("ustrong", 40, 58, true);
sprite_change_offset("dstrong", 40, 58, true);
sprite_change_offset("nspecial", 40, 58, true);
sprite_change_offset("nspecial_air", 40, 58, true);
sprite_change_offset("fspecial", 40, 58, true);
sprite_change_offset("fspecial_air", 40, 58, true);
sprite_change_offset("uspecial", 40, 58, true);
sprite_change_offset("uspecial_air", 40, 58, true);
sprite_change_offset("dspecial", 40, 58, true);
sprite_change_offset("dspecial_air", 40, 58, true);
sprite_change_offset("grab", 40, 58, true);
sprite_change_offset("grab_air", 40, 58, true);
sprite_change_offset("taunt", 40/2, 78/2, true);
sprite_change_offset("taunt_beeg", 100, 399, true);

sprite_change_offset("plat", 35, 30, true);
sprite_change_offset("plat2", 70, 60, true);
sprite_change_offset("_phone", 40, 58, true);
sprite_change_offset("lookup", 40/2, 78/2, true);

sprite_change_offset("icon_gip", 4, 4, true);
sprite_change_offset("icon_gip_2", 7, 7, true);

sprite_change_offset("miiverse_post", 60, 30);
sprite_change_offset("taunt_specialkewtian", 40,79, true);
sprite_change_offset("trialgrounds", 31, 0, true);
sprite_change_offset("lastresort", 27, 39, true);
sprite_change_offset("greenflowerzone", 20, 43, true);
sprite_change_offset("abysshime", 60, 188, true);

sprite_change_offset("pocket_effect", 70, 70);
sprite_change_offset("fspecial_lloid", 30, 50);
sprite_change_offset("fspecial_lloid_collision", 30, 30);
sprite_change_offset("fspecial_lloid_mjau", 50, 60);
sprite_change_offset("fspecial_lloid_mjau_alts", 50, 60);
sprite_change_offset("fspecial_lloid_golfcar", 38, 44);
sprite_change_offset("uspecial_balloon", 30, 30);
sprite_change_offset("uspecial_balloon_sol", 30, 30);
sprite_change_offset("uspecial_balloon_sol_alts", 30, 30);
sprite_change_offset("dspecial_tree", 80, 159);
sprite_change_offset("dspecial_tree_collision", 80, 159);
sprite_change_offset("dspecial_tree_alts", 80, 159);
sprite_change_offset("dspecial_tree_mc", 80, 159);
sprite_change_offset("dspecial_tree_falling", 80, 80);
sprite_change_offset("dspecial_tree_falling_collision", 80, 80);
sprite_change_offset("dspecial_tree_falling_alts", 80, 80);
sprite_change_offset("dspecial_tree_falling_mc", 80, 80);
sprite_change_offset("dspecial_tree_leaves", 20, 20);
sprite_change_offset("dspecial_tree_leaves_alts", 20, 20);
sprite_change_offset("dspecial_tree_fall", 15, 30);
sprite_change_offset("dspecial_seed", 20, 20);
sprite_change_offset("dspecial_seed_collision", 20, 20);
sprite_change_offset("dspecial_seed_mc", 20, 20);
sprite_change_offset("dspecial_water", 20, 20);
sprite_change_offset("dspecial_water_alts", 20, 20);
sprite_change_offset("dattack_pot", 28, 30);
sprite_change_offset("dattack_pot_collision", 21, 21);
sprite_change_offset("dattack_pot_mc", 28, 30);
sprite_change_offset("bowlingball", 15, 15);
sprite_change_offset("bowlingball_collision", 15, 15);
sprite_change_offset("bowlingball_fall", 15, 15);
sprite_change_offset("bowlingball_planet", 15, 15);
sprite_change_offset("bowlingball_melon", 15, 15);
sprite_change_offset("bowlingball_golf", 15, 15);
sprite_change_offset("bowlingball_anvil", 15, 15);
sprite_change_offset("ustrong_fireworks", 16, 30);
sprite_change_offset("ustrong_fireworks_collision", 16, 30);
sprite_change_offset("ustrong_fireworks_mc", 16, 30);
sprite_change_offset("ustrong_fireworks_explosion_blue", 60, 60);
sprite_change_offset("ustrong_fireworks_explosion_purple", 60, 60);
sprite_change_offset("ustrong_fireworks_explosion_yellow", 60, 60);
sprite_change_offset("ustrong_fireworks_shot", 20, 20);
sprite_change_offset("slingshot_projectile", 7, 7);
sprite_change_offset("slingshot_projectile_trail", 15, 15);
sprite_change_offset("slingshot_projectile_planet", 7, 7);
sprite_change_offset("slingshot_projectile_abl", 7, 7);
sprite_change_offset("slingshot_projectile_golf", 7, 7);
sprite_change_offset("bury", 23, 19);
sprite_change_offset("bury_effect", 50, 58);
sprite_change_offset("bells_coin", 12, 12);
sprite_change_offset("bells_bag", 19, 19);
sprite_change_offset("dust_effect", 15, 15);
sprite_change_offset("dust_sharp", 30, 40);
sprite_change_offset("dust_sharp_big", 60, 80);
sprite_change_offset("explosion", 100, 100);
sprite_change_offset("fx_lightbeams_small", 200, 200);
sprite_change_offset("star_tiny", 30, 30);
sprite_change_offset("fx_sharphit", 120, 120);
sprite_change_offset("fx_sharphitbig", 120, 240);
sprite_change_offset("fx_sharphitbig2", 120, 480);
sprite_change_offset("groundcracks", 80, 0);
sprite_change_offset("groundcracks2", 80, 0);