set_attack_value(AT_FSTRONG, AG_SPRITE, sprite_get("fstrong"));
set_attack_value(AT_FSTRONG, AG_NUM_WINDOWS, 4);
set_attack_value(AT_FSTRONG, AG_CATEGORY, 0);
set_attack_value(AT_FSTRONG, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_FSTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_FSTRONG, AG_HURTBOX_SPRITE, sprite_get("fstrong_hurt"));




set_window_value(AT_FSTRONG, 1, AG_WINDOW_INVINCIBILITY, 2);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_INVINCIBILITY, 2);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_INVINCIBILITY, 2);

set_window_value(AT_FSTRONG, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_LENGTH, 16);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.4);
set_window_value(AT_FSTRONG, 1, AG_WINDOW_HSPEED, 2);

set_window_value(AT_FSTRONG, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_LENGTH, 5);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HSPEED, 4);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX_FRAME, 0);

set_window_value(AT_FSTRONG, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_FSTRONG, 3, AG_WINDOW_HAS_SFX, 1);


set_window_value(AT_FSTRONG, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_LENGTH, 15);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_FSTRONG, 4, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FSTRONG, 3);

set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_WINDOW, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FSTRONG, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_X, 22);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSTRONG, 5, HG_WIDTH, 176);
set_hitbox_value(AT_FSTRONG, 5, HG_HEIGHT, 176);
set_hitbox_value(AT_FSTRONG, 5, HG_SHAPE, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_PRIORITY, 3);
set_hitbox_value(AT_FSTRONG, 5, HG_DAMAGE, .1);
set_hitbox_value(AT_FSTRONG, 5, HG_ANGLE, 56);
set_hitbox_value(AT_FSTRONG, 5, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 5, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSTRONG, 5, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 5, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSTRONG, 5, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FSTRONG, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_WINDOW, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FSTRONG, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_X, 22);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSTRONG, 3, HG_WIDTH, 66);
set_hitbox_value(AT_FSTRONG, 3, HG_HEIGHT, 44);
set_hitbox_value(AT_FSTRONG, 3, HG_SHAPE, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_FSTRONG, 3, HG_DAMAGE, .1);
set_hitbox_value(AT_FSTRONG, 3, HG_ANGLE, 56);
set_hitbox_value(AT_FSTRONG, 3, HG_EFFECT, 9);
set_hitbox_value(AT_FSTRONG, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FSTRONG, 3, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 3, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 3, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_FSTRONG, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW, 3);
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_X, 32);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSTRONG, 1, HG_WIDTH, 94);
set_hitbox_value(AT_FSTRONG, 1, HG_HEIGHT, 84);
set_hitbox_value(AT_FSTRONG, 1, HG_SHAPE, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_FSTRONG, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE, 50);
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_FSTRONG, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT_Y_OFFSET, 10);
set_hitbox_value(AT_FSTRONG, 1, HG_HITSTUN_MULTIPLIER, 1.0);
set_hitbox_value(AT_FSTRONG, 1, HG_VISUAL_EFFECT, 306);
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSTRONG, 1, HG_HIT_SFX, asset_get("sfx_absa_kickhit"));
set_hitbox_value(AT_FSTRONG, 1, HG_TECHABLE, 1);


set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_WINDOW, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FSTRONG, 8, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_X, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSTRONG, 8, HG_WIDTH, 126);
set_hitbox_value(AT_FSTRONG, 8, HG_HEIGHT, 126);
set_hitbox_value(AT_FSTRONG, 8, HG_SHAPE, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_PRIORITY, 3);
set_hitbox_value(AT_FSTRONG, 8, HG_DAMAGE, 5);
set_hitbox_value(AT_FSTRONG, 8, HG_ANGLE, 56);
set_hitbox_value(AT_FSTRONG, 8, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 8, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSTRONG, 8, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 8, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 8, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSTRONG, 8, HG_HIT_SFX, asset_get("sfx_blow_medium3"));

set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_WINDOW, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FSTRONG, 9, HG_LIFETIME, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_X, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSTRONG, 9, HG_WIDTH, 350);
set_hitbox_value(AT_FSTRONG, 9, HG_HEIGHT, 300);
set_hitbox_value(AT_FSTRONG, 9, HG_SHAPE, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_PRIORITY, 3);
set_hitbox_value(AT_FSTRONG, 9, HG_DAMAGE, 5);
set_hitbox_value(AT_FSTRONG, 9, HG_GROUNDEDNESS, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_ANGLE, 90);
set_hitbox_value(AT_FSTRONG, 9, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FSTRONG, 9, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FSTRONG, 9, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_TECHABLE, 1);
set_hitbox_value(AT_FSTRONG, 9, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSTRONG, 9, HG_HIT_SFX, asset_get("sfx_blow_medium3"));