chainsaw_gravity = 0.3; // can't call this gravity or else the game applies it automatically even when paused lmao
lifetime = 300;

sprite_index = sprite_get("chainsaw");
image_index = 0;
anim_speed = 0;
max_anim_speed = 1.0;
anim_spinup_frames = 60;
spr_dir = player_id.spr_dir;
image_angle = 10*spr_dir;
min_time_between_hits = 4;
last_hit_time = -10;
explosion_damage = 0; // this should be overwritten by the player when releasing the chainsaw, depending on how strong the charge is
timer = 0;
has_hit = false;
fuse_remaining = 60;
exploding = false;
explosion_timer = 0;
released = false;
destroyed = false;
was_parried = false;