
set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("extra_1"));
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 6);
set_attack_value(AT_EXTRA_2, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_EXTRA_2, AG_AIR_SPRITE, sprite_get("extra_1"));
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("empty"));

set_window_value(AT_EXTRA_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 30);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAME_START, 0);


set_window_value(AT_EXTRA_2, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_LENGTH, 14);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAME_START, 6);

set_window_value(AT_EXTRA_2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_LENGTH, 14);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAME_START, 9);

set_window_value(AT_EXTRA_2, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_LENGTH, 14);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAME_START, 13);

set_window_value(AT_EXTRA_2, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_LENGTH, 30);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAME_START, 17);

set_window_value(AT_EXTRA_2, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_LENGTH, 30);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_SFX, asset_get("sfx_spin"))
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAME_START, 22);


set_num_hitboxes(AT_EXTRA_2, 0);


set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 200);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_2, 1, HG_WIDTH, 40);
set_hitbox_value(AT_EXTRA_2, 1, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 1, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_2, 1, HG_EXTRA_HITPAUSE, 35);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, sh1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_SPRITE, sprite_get("pratfall"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_HSPEED, -12);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_PLASMA_SAFE, true);

set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 200);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_2, 2, HG_WIDTH, 40);
set_hitbox_value(AT_EXTRA_2, 2, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 2, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_2, 2, HG_EXTRA_HITPAUSE, 35);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, sh3);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_SPRITE, sprite_get("pratfall"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_HSPEED, -6);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_VSPEED, -8);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_PLASMA_SAFE, true);

set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 200);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_2, 3, HG_WIDTH, 40);
set_hitbox_value(AT_EXTRA_2, 3, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 3, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_2, 3, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, sh2);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_SPRITE, sprite_get("pratfall"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_HSPEED, 6);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_VSPEED, -8);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PLASMA_SAFE, true);

set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_LIFETIME, 200);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_2, 4, HG_WIDTH, 40);
set_hitbox_value(AT_EXTRA_2, 4, HG_HEIGHT, 90);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 4, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_2, 4, HG_EXTRA_HITPAUSE, 35);
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT, sh4);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_SPRITE, sprite_get("pratfall"));
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_HSPEED, 12);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_PLASMA_SAFE, true);

set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_LIFETIME, 10);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_2, 5, HG_WIDTH, 120);
set_hitbox_value(AT_EXTRA_2, 5, HG_HEIGHT, 120);
set_hitbox_value(AT_EXTRA_2, 5, HG_PRIORITY, 9);
set_hitbox_value(AT_EXTRA_2, 5, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 5, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_2, 5, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(AT_EXTRA_2, 5, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_DESTROY_EFFECT, 304);
set_hitbox_value(AT_EXTRA_2, 5, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_SPRITE, sprite_get("empty"));
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_EXTRA_2, 5, HG_PROJECTILE_PLASMA_SAFE, true);