//Flutter Kick
set_attack_value(AT_EXTRA_1, AG_CATEGORY, 1);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("flutter"));
set_attack_value(AT_EXTRA_1, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("beegguy_hurt"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 6);
set_attack_value(AT_EXTRA_1, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_EXTRA_1, AG_MUNO_ATTACK_EXCLUDE, 1);

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX, sound_get("yoshi_flutter_loop"));
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_CUSTOM_GRAVITY, .25);

set_attack_value(AT_EXTRA_1, AG_MUNO_ATTACK_NAME, "Flutter Kick");
set_num_hitboxes(AT_EXTRA_1,0);


set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -57);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, -20);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 120);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 120);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 10);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITSTUN_MULTIPLIER, 0.8);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -57);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, -20);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 130);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 100);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 10);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 7);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 46);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITPAUSE_SCALING, .7);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITSTUN_MULTIPLIER, 0.6);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -57);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, -20);
set_hitbox_value(AT_EXTRA_1, 3, HG_WIDTH, 180);
set_hitbox_value(AT_EXTRA_1, 3, HG_HEIGHT, 140);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 10);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 7);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 3, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITPAUSE_SCALING, .7);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITSTUN_MULTIPLIER, 0.6);
set_hitbox_value(AT_EXTRA_1, 3, HG_MUNO_ATTACK_EXCLUDE, 1);

set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_Y, -57);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_X, -20);
set_hitbox_value(AT_EXTRA_1, 4, HG_WIDTH, 120);
set_hitbox_value(AT_EXTRA_1, 4, HG_HEIGHT, 120);
set_hitbox_value(AT_EXTRA_1, 4, HG_PRIORITY, 10);
set_hitbox_value(AT_EXTRA_1, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_EXTRA_1, 4, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 4, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITSTUN_MULTIPLIER, 0.8);

set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_Y, -40);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_WIDTH, 160);
set_hitbox_value(AT_EXTRA_1, 5, HG_HEIGHT, 160);
set_hitbox_value(AT_EXTRA_1, 5, HG_PRIORITY, 10);
set_hitbox_value(AT_EXTRA_1, 5, HG_DAMAGE, 16);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_KNOCKBACK, 15);
set_hitbox_value(AT_EXTRA_1, 5, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_1, 5, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_EXTRA_1, 5, HG_HITPAUSE_SCALING, .8);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_GROUP, -1);