set_attack_value(AT_DTILT, AG_SPRITE, sprite_get("dtilt"));
set_attack_value(AT_DTILT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DTILT, AG_HURTBOX_SPRITE, sprite_get("dtilt_hurt"));

set_window_value(AT_DTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_weak2"));
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX_FRAME, 2);

set_window_value(AT_DTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);

set_window_value(AT_DTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_DTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_DTILT, 4);

set_hitbox_value(AT_DTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_X, 37);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_Y, -41);
set_hitbox_value(AT_DTILT, 1, HG_WIDTH, 46);
set_hitbox_value(AT_DTILT, 1, HG_HEIGHT, 57);
set_hitbox_value(AT_DTILT, 1, HG_SHAPE, 2);
set_hitbox_value(AT_DTILT, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_DTILT, 1, HG_DAMAGE, 7);
set_hitbox_value(AT_DTILT, 1, HG_ANGLE, 290);
set_hitbox_value(AT_DTILT, 1, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DTILT, 1, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_DTILT, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_DTILT, 1, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_DTILT, 1, HG_HIT_SFX, sfx_hit2);
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT, 301);

set_hitbox_value(AT_DTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 2, HG_LIFETIME, 6);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_X, 16);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_Y, -49);
set_hitbox_value(AT_DTILT, 2, HG_WIDTH, 59);
set_hitbox_value(AT_DTILT, 2, HG_HEIGHT, 37);
set_hitbox_value(AT_DTILT, 2, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_DTILT, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_DTILT, 2, HG_ANGLE, 0);
set_hitbox_value(AT_DTILT, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DTILT, 2, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_DTILT, 2, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_DTILT, 2, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_DTILT, 2, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT, 301);

set_hitbox_value(AT_DTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 3, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_DTILT, 3, HG_HITBOX_X, 37);
set_hitbox_value(AT_DTILT, 3, HG_HITBOX_Y, -14);
set_hitbox_value(AT_DTILT, 3, HG_WIDTH, 35);
set_hitbox_value(AT_DTILT, 3, HG_HEIGHT, 29);
set_hitbox_value(AT_DTILT, 3, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 3, HG_DAMAGE, 7);
set_hitbox_value(AT_DTILT, 3, HG_ANGLE, 270);
set_hitbox_value(AT_DTILT, 3, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_DTILT, 3, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_DTILT, 3, HG_BASE_HITPAUSE, 22);
set_hitbox_value(AT_DTILT, 3, HG_HITPAUSE_SCALING, .8);
set_hitbox_value(AT_DTILT, 3, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_DTILT, 3, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_DTILT, 3, HG_HIT_SFX, sfx_hit3);
set_hitbox_value(AT_DTILT, 3, HG_VISUAL_EFFECT, 305);

set_hitbox_value(AT_DTILT, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 4, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_DTILT, 4, HG_LIFETIME, 9);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_X, 37);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_Y, -14);
set_hitbox_value(AT_DTILT, 4, HG_WIDTH, 35);
set_hitbox_value(AT_DTILT, 4, HG_HEIGHT, 29);
set_hitbox_value(AT_DTILT, 4, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 4, HG_DAMAGE, 4);
set_hitbox_value(AT_DTILT, 4, HG_ANGLE, 270);
set_hitbox_value(AT_DTILT, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DTILT, 4, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_DTILT, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_DTILT, 4, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_DTILT, 4, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_DTILT, 4, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_DTILT, 4, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_DTILT, 4, HG_VISUAL_EFFECT, 301);
