set_attack_value(AT_FSPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_FSPECIAL, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_NUM_WINDOWS, 2);
set_attack_value(AT_FSPECIAL, AG_AIR_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));

set_window_value(AT_FSPECIAL, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_LENGTH, 16);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_FSPECIAL, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 2);


set_num_hitboxes(AT_FSPECIAL, 0);

set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_LIFETIME, 100);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_DAMAGE, 6);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_HITPAUSE_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_SPRITE, sprite_get("proj_pumpkin"));
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_MASK, sprite_get("hbox_pumpkin"));
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_GRAVITY, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_AIR_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_GROUND_FRICTION, 100);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_VISUAL_EFFECT, vfx_pumpkin);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_HIT_SFX, sfx_hit5);
set_hitbox_value(AT_FSPECIAL, itm_pumpkin, HG_PROJECTILE_DESTROY_EFFECT, 1);

set_hitbox_value(AT_FSPECIAL, itm_flask, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_LIFETIME, 45);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PRIORITY, 5);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_DAMAGE, 4);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_ANGLE, 1);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_SPRITE, sprite_get("proj_flask"));
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_MASK, sprite_get("hbox_flask"));
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_GRAVITY, 0.6);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_AIR_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_GROUND_FRICTION, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_VISUAL_EFFECT, 302);
set_hitbox_value(AT_FSPECIAL, itm_flask, HG_HIT_SFX, sfx_hit4);

set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_LIFETIME, 100);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PRIORITY, 4);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_DAMAGE, 4);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_ANGLE, 90);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_EXTRA_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_SPRITE, sprite_get("proj_coffee"));
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_MASK, sprite_get("hbox_coffee"));
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_GRAVITY, 0.6);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_AIR_FRICTION, 0.02);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_GROUND_FRICTION, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_HIT_SFX, sfx_hit2);
set_hitbox_value(AT_FSPECIAL, itm_coffee, HG_HIT_LOCKOUT, 1);

//coffeee splash
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_LIFETIME, 24);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PRIORITY, 8);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_DAMAGE, 0);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_ANGLE, 80);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_EFFECT, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_SPRITE, sprite_get("proj_coffee_boom"));
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_MASK, sprite_get("hbox_coffee_boom"));
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_coffee + 20, HG_VISUAL_EFFECT, 3);

set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_DAMAGE, 2);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_SPRITE, sprite_get("proj_candy_corn"));
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_MASK, sprite_get("proj_candy_corn"));
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_GRAVITY, 0.6);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_AIR_FRICTION, 0.01);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_GROUND_FRICTION, 1);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_HIT_LOCKOUT, 3);
set_hitbox_value(AT_FSPECIAL, itm_candycorn, HG_HIT_SFX, sfx_hit1);

set_hitbox_value(AT_FSPECIAL, itm_window, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_DAMAGE, 2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_SPRITE, sprite_get("proj_window"));
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_MASK, sprite_get("hbox_window"));
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_ANIM_SPEED, 1);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_GRAVITY, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_AIR_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_GROUND_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_PROJECTILE_PLASMA_SAFE, 1);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSPECIAL, itm_window, HG_HIT_SFX, sfx_hit3);

set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_LIFETIME, 300);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_DAMAGE, 5);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_ANGLE, 90);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_SPRITE, sprite_get("proj_knifebear"));
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_MASK, sprite_get("hbox_knifebear"));
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_FORCE_FLINCH, 1);
set_hitbox_value(AT_FSPECIAL, itm_knifebear, HG_HIT_SFX, sound_get("stab"));

set_hitbox_value(AT_FSPECIAL, itm_bust, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_LIFETIME, 1000);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_DAMAGE, 8);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_ANGLE, 80);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_SPRITE, sprite_get("proj_bust"));
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_MASK, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_GRAVITY, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_AIR_FRICTION, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_GROUND_FRICTION, 100);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_HIT_SFX, sfx_crash);
set_hitbox_value(AT_FSPECIAL, itm_bust, HG_PROJECTILE_DESTROY_EFFECT, 192);

set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_LIFETIME, 160);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_DAMAGE, 0);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_ANGLE, 90);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_SPRITE, sprite_get("proj_cc_sack"));
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_MASK, sprite_get("hbox_cc_sack"));
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_GRAVITY, 1);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_AIR_FRICTION, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_GROUND_FRICTION, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_cc_sack, HG_HIT_SFX, sfx_hit5);

set_hitbox_value(AT_FSPECIAL, itm_code, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_DAMAGE, 1);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_ANGLE, 60);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_KNOCKBACK_SCALING, 3);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_HITPAUSE_SCALING, 3);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_SPRITE, sprite_get("proj_code"));
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_MASK, sprite_get("proj_code"));
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_GRAVITY, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_FSPECIAL, itm_code, HG_HIT_SFX, sfx_hit1);

set_hitbox_value(AT_FSPECIAL, itm_lock, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_LIFETIME, 40);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PRIORITY, 5);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_DAMAGE, 4);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_ANGLE, 90);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_EXTRA_HITPAUSE, 30);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_HIT_LOCKOUT, 30);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PROJECTILE_SPRITE, sprite_get("proj_lock"));
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PROJECTILE_MASK, sprite_get("hbox_lock"));
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PROJECTILE_GRAVITY, 0.6);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PROJECTILE_AIR_FRICTION, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_lock, HG_HIT_SFX, sfx_hit2);

set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_LIFETIME, 100);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_ANGLE, 80);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_PROJECTILE_SPRITE, sprite_get("bullet"));
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_PROJECTILE_MASK, sprite_get("hbox_pumpkin"));
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_PROJECTILE_GRAVITY, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_PROJECTILE_AIR_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_bullets, HG_VISUAL_EFFECT_Y_OFFSET, -16);


set_hitbox_value(AT_FSPECIAL, itm_egg, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_DAMAGE, 6);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_HITPAUSE_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_SPRITE, sprite_get("proj_egg"));
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_MASK, sprite_get("proj_egg"));
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_GRAVITY, 0.9);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_AIR_FRICTION, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_egg, HG_PROJECTILE_DESTROY_EFFECT, 1);

set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_DAMAGE, 6);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_HITPAUSE_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_SPRITE, sprite_get("proj_codpiece"));
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_MASK, sprite_get("proj_codpiece"));
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_GRAVITY, 0.3);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_AIR_FRICTION, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_codpiece, HG_PROJECTILE_DESTROY_EFFECT, 1);

set_hitbox_value(AT_FSPECIAL, itm_pie, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_DAMAGE, 6);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_KNOCKBACK_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_HITPAUSE_SCALING, 1.5);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_SPRITE, sprite_get("proj_pie"));
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_MASK, sprite_get("proj_pie"));
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_GRAVITY, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_pie, HG_PROJECTILE_DESTROY_EFFECT, 1);

set_hitbox_value(AT_FSPECIAL, itm_melon, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_LIFETIME, 30);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_DAMAGE, 6);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_ANGLE, 70);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_SPRITE, sprite_get("proj_melon"));
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_MASK, sprite_get("proj_melon"));
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_GRAVITY, 0.7);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_AIR_FRICTION, 0.3);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_HIT_SFX, sfx_hit1);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_melon, HG_PROJECTILE_DESTROY_EFFECT, 1);



set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_LIFETIME, 700);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_DAMAGE, 8);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_ANGLE, 80);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_SPRITE, sprite_get("proj_bust"));
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_MASK, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_GRAVITY, 0.4);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_AIR_FRICTION, 0.5);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_GROUND_FRICTION, 100);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_HIT_SFX, sfx_crash);
set_hitbox_value(AT_FSPECIAL, itm_busted_bust, HG_PROJECTILE_DESTROY_EFFECT, 192);