set_attack_value(AT_USTRONG_2, AG_SPRITE, sprite_get("ustrong_tired"));
set_attack_value(AT_USTRONG_2, AG_NUM_WINDOWS, 3);
set_attack_value(AT_USTRONG_2, AG_CATEGORY, 0);
set_attack_value(AT_USTRONG_2, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_USTRONG_2, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_USTRONG_2, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_USTRONG_2, AG_HURTBOX_SPRITE, sprite_get("ustrong_tired_hurt"));

set_window_value(AT_USTRONG_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG_2, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_USTRONG_2, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_USTRONG_2, 1, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(AT_USTRONG_2, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_LENGTH, 9);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_SFX, sfx_steam2);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.4);
set_window_value(AT_USTRONG_2, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.4);

set_window_value(AT_USTRONG_2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_LENGTH, 25);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_CUSTOM_GRAVITY, 1.5);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.4);
set_window_value(AT_USTRONG_2, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.4);

set_num_hitboxes(AT_USTRONG_2, 4);

set_hitbox_value(AT_USTRONG_2, 1, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_USTRONG_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG_2, 1, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_USTRONG_2, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_USTRONG_2, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_USTRONG_2, 1, HG_HITBOX_Y, -130);
set_hitbox_value(AT_USTRONG_2, 1, HG_WIDTH, 30);
set_hitbox_value(AT_USTRONG_2, 1, HG_HEIGHT, 200);
set_hitbox_value(AT_USTRONG_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG_2, 1, HG_DAMAGE, 12);
set_hitbox_value(AT_USTRONG_2, 1, HG_ANGLE, 90);
set_hitbox_value(AT_USTRONG_2, 1, HG_ANGLE_FLIPPER, 7);
set_hitbox_value(AT_USTRONG_2, 1, HG_SHAPE, 1);
set_hitbox_value(AT_USTRONG_2, 1, HG_VISUAL_EFFECT, vfx_steam_hit_large_tired);
set_hitbox_value(AT_USTRONG_2, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG_2, 1, HG_KNOCKBACK_SCALING, 0.95);
set_hitbox_value(AT_USTRONG_2, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_USTRONG_2, 1, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_USTRONG_2, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_USTRONG_2, 1, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));

set_hitbox_value(AT_USTRONG_2, 2, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_USTRONG_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG_2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG_2, 2, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_USTRONG_2, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_USTRONG_2, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_USTRONG_2, 2, HG_HITBOX_Y, -225);
set_hitbox_value(AT_USTRONG_2, 2, HG_WIDTH, 35);
set_hitbox_value(AT_USTRONG_2, 2, HG_HEIGHT, 35);
set_hitbox_value(AT_USTRONG_2, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG_2, 2, HG_DAMAGE, 16);
set_hitbox_value(AT_USTRONG_2, 2, HG_ANGLE, 90);
set_hitbox_value(AT_USTRONG_2, 2, HG_ANGLE_FLIPPER, 7);
set_hitbox_value(AT_USTRONG_2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG_2, 2, HG_VISUAL_EFFECT, vfx_steam_hit_large_tired);
set_hitbox_value(AT_USTRONG_2, 2, HG_BASE_KNOCKBACK, 8.5);
set_hitbox_value(AT_USTRONG_2, 2, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_USTRONG_2, 2, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_USTRONG_2, 2, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_USTRONG_2, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_USTRONG_2, 2, HG_HIT_SFX, sound_get("sfx_critical_strike"));
