set_attack_value(AT_EXTRA_3, AG_CATEGORY, 1);
set_attack_value(AT_EXTRA_3, AG_SPRITE, sprite_get("nair"));
set_attack_value(AT_EXTRA_3, AG_NUM_WINDOWS, 3);
set_attack_value(AT_EXTRA_3, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_EXTRA_3, AG_LANDING_LAG, 8);
set_attack_value(AT_EXTRA_3, AG_HURTBOX_SPRITE, sprite_get("nair_hurt"));

set_window_value(AT_EXTRA_3, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_ANIM_FRAMES, 2);

set_window_value(AT_EXTRA_3, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_3, 2, AG_WINDOW_LENGTH, 80);
set_window_value(AT_EXTRA_3, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_3, 2, AG_WINDOW_ANIM_FRAME_START, 2);

set_window_value(AT_EXTRA_3, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_3, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_EXTRA_3, 3, AG_WINDOW_ANIM_FRAMES, -2);
set_window_value(AT_EXTRA_3, 3, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_EXTRA_3, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_EXTRA_3, 12);
//Multi1
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 1, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 1, HG_PRIORITY, 5);
set_hitbox_value(AT_EXTRA_3, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE, 145);
set_hitbox_value(AT_EXTRA_3, 1, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_EXTRA_3, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
//Multi1Back
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_EXTRA_3, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 2, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 2, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 2, HG_PRIORITY, 5);
set_hitbox_value(AT_EXTRA_3, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_ANGLE, 45);
set_hitbox_value(AT_EXTRA_3, 2, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_EXTRA_3, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_3, 2, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_EXTRA_3, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
//Multi2
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_EXTRA_3, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 3, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 3, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 3, HG_PRIORITY, 5);
//Multi2Back
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 4, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_EXTRA_3, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 4, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 4, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 4, HG_PRIORITY, 5);
//Multi3
set_hitbox_value(AT_EXTRA_3, 5, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_EXTRA_3, 5, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 5, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 5, HG_WINDOW_CREATION_FRAME, 18);
set_hitbox_value(AT_EXTRA_3, 5, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 5, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 5, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 5, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 5, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 5, HG_PRIORITY, 5);
//Multi3Back
set_hitbox_value(AT_EXTRA_3, 6, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_EXTRA_3, 6, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_3, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 6, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 6, HG_WINDOW_CREATION_FRAME, 18);
set_hitbox_value(AT_EXTRA_3, 6, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 6, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 6, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 6, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 6, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 6, HG_PRIORITY, 5);
//Multi4
set_hitbox_value(AT_EXTRA_3, 7, HG_HITBOX_GROUP, 4);
set_hitbox_value(AT_EXTRA_3, 7, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 7, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 7, HG_WINDOW_CREATION_FRAME, 26);
set_hitbox_value(AT_EXTRA_3, 7, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 7, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 7, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 7, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 7, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 7, HG_PRIORITY, 5);
//Multi4Back
set_hitbox_value(AT_EXTRA_3, 8, HG_HITBOX_GROUP, 4);
set_hitbox_value(AT_EXTRA_3, 8, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_3, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 8, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 8, HG_WINDOW_CREATION_FRAME, 26);
set_hitbox_value(AT_EXTRA_3, 8, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 8, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 8, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 8, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 8, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 8, HG_PRIORITY, 5);
//Multi5
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_GROUP, 5);
set_hitbox_value(AT_EXTRA_3, 9, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 9, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 9, HG_WINDOW_CREATION_FRAME, 32);
set_hitbox_value(AT_EXTRA_3, 9, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 9, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 9, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 9, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 9, HG_PRIORITY, 5);
//Multi5Back
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_GROUP, 5);
set_hitbox_value(AT_EXTRA_3, 10, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 10, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 10, HG_WINDOW_CREATION_FRAME, 32);
set_hitbox_value(AT_EXTRA_3, 10, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 10, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 10, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 10, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 10, HG_PRIORITY, 5);
//Multi6
set_hitbox_value(AT_EXTRA_3, 11, HG_HITBOX_GROUP, 6);
set_hitbox_value(AT_EXTRA_3, 11, HG_PARENT_HITBOX, 11);
set_hitbox_value(AT_EXTRA_3, 11, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 11, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 11, HG_WINDOW_CREATION_FRAME, 42);
set_hitbox_value(AT_EXTRA_3, 11, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 11, HG_HITBOX_X, 60);
set_hitbox_value(AT_EXTRA_3, 11, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 11, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 11, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 11, HG_PRIORITY, 5);
set_hitbox_value(AT_EXTRA_3, 11, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_3, 11, HG_ANGLE, 45);
set_hitbox_value(AT_EXTRA_3, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_3, 11, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_3, 11, HG_KNOCKBACK_SCALING, .9);
set_hitbox_value(AT_EXTRA_3, 11, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_3, 11, HG_HITPAUSE_SCALING, .9);
set_hitbox_value(AT_EXTRA_3, 11, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 11, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_3, 11, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_EXTRA_3, 11, HG_EXTRA_CAMERA_SHAKE, 11);
set_hitbox_value(AT_EXTRA_3, 11, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
//Multi6Back
set_hitbox_value(AT_EXTRA_3, 12, HG_HITBOX_GROUP, 6);
set_hitbox_value(AT_EXTRA_3, 12, HG_PARENT_HITBOX, 12);
set_hitbox_value(AT_EXTRA_3, 12, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_3, 12, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_3, 12, HG_WINDOW_CREATION_FRAME, 42);
set_hitbox_value(AT_EXTRA_3, 12, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_3, 12, HG_HITBOX_X, -60);
set_hitbox_value(AT_EXTRA_3, 12, HG_HITBOX_Y, -60);
set_hitbox_value(AT_EXTRA_3, 12, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_3, 12, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_3, 12, HG_PRIORITY, 5);
set_hitbox_value(AT_EXTRA_3, 12, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_3, 12, HG_ANGLE, 145);
set_hitbox_value(AT_EXTRA_3, 12, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_3, 12, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_3, 12, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_3, 12, HG_KNOCKBACK_SCALING, .9);
set_hitbox_value(AT_EXTRA_3, 12, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_3, 12, HG_HITPAUSE_SCALING, .9);
set_hitbox_value(AT_EXTRA_3, 12, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_EXTRA_3, 12, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_3, 12, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_EXTRA_3, 12, HG_EXTRA_CAMERA_SHAKE, 11);
set_hitbox_value(AT_EXTRA_3, 12, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));