set_attack_value(AT_NAIR, AG_CATEGORY, 1);
set_attack_value(AT_NAIR, AG_SPRITE, sprite_get("nair"));
set_attack_value(AT_NAIR, AG_AIR_SPRITE, sprite_get("nair"));
set_attack_value(AT_NAIR, AG_HURTBOX_SPRITE, sprite_get("nair_hurt"));
set_attack_value(AT_NAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_NAIR, AG_LANDING_LAG, 6);

set_attack_value(AT_NAIR, AG_NUM_WINDOWS, 4);
set_window_value(AT_NAIR, 1, AG_WINDOW_LENGTH, 5);
set_window_value(AT_NAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);

set_window_value(AT_NAIR, 2, AG_WINDOW_LENGTH, 2);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAME_START, 1);

set_window_value(AT_NAIR, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAME_START, 3);

set_window_value(AT_NAIR, 4, AG_WINDOW_LENGTH, 7);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_NAIR, 4, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_NAIR, 8);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 1, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_NAIR, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_X, 36);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NAIR, 1, HG_WIDTH, 65);
set_hitbox_value(AT_NAIR, 1, HG_HEIGHT, 65);
set_hitbox_value(AT_NAIR, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_NAIR, 1, HG_EXTRA_HITPAUSE, 2);
set_hitbox_value(AT_NAIR, 1, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NAIR, 1, HG_HIT_SFX, asset_get("sfx_icehit_weak2"));

set_hitbox_value(AT_NAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_NAIR, 2, HG_LIFETIME, 1);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_X, 20);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_Y, -15);
set_hitbox_value(AT_NAIR, 2, HG_WIDTH, 75);
set_hitbox_value(AT_NAIR, 2, HG_HEIGHT, 55);
set_hitbox_value(AT_NAIR, 2, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 2, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 2, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_NAIR, 2, HG_EXTRA_HITPAUSE, 2);
set_hitbox_value(AT_NAIR, 2, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NAIR, 2, HG_HIT_SFX, asset_get("sfx_icehit_weak2"));

set_hitbox_value(AT_NAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_NAIR, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_X, -30);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NAIR, 3, HG_WIDTH, 65);
set_hitbox_value(AT_NAIR, 3, HG_HEIGHT, 55);
set_hitbox_value(AT_NAIR, 3, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 3, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_NAIR, 3, HG_EXTRA_HITPAUSE, 2);
set_hitbox_value(AT_NAIR, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NAIR, 3, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NAIR, 3, HG_HIT_SFX, asset_get("sfx_icehit_weak2"));

set_hitbox_value(AT_NAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 4, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 4, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NAIR, 4, HG_LIFETIME, 1);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_X, -30);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_Y, -42);
set_hitbox_value(AT_NAIR, 4, HG_WIDTH, 75);
set_hitbox_value(AT_NAIR, 4, HG_HEIGHT, 55);
set_hitbox_value(AT_NAIR, 4, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 4, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 4, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 4, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_NAIR, 4, HG_EXTRA_HITPAUSE, 2);
set_hitbox_value(AT_NAIR, 4, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NAIR, 4, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NAIR, 4, HG_HIT_SFX, asset_get("sfx_icehit_weak2"));

set_hitbox_value(AT_NAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 5, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 5, HG_WINDOW_CREATION_FRAME, 9);
set_hitbox_value(AT_NAIR, 5, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_X, 20);
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_Y, -15);
set_hitbox_value(AT_NAIR, 5, HG_WIDTH, 75);
set_hitbox_value(AT_NAIR, 5, HG_HEIGHT, 55);
set_hitbox_value(AT_NAIR, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_NAIR, 5, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 5, HG_ANGLE, 45);
set_hitbox_value(AT_NAIR, 5, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NAIR, 5, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 5, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NAIR, 5, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NAIR, 5, HG_HIT_SFX, asset_get("sfx_icehit_medium2"));

set_hitbox_value(AT_NAIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 6, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 6, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_NAIR, 6, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_X, 0);
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_Y, -55);
set_hitbox_value(AT_NAIR, 6, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 6, HG_HEIGHT, 60);
set_hitbox_value(AT_NAIR, 6, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 6, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 6, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 6, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 6, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_NAIR, 6, HG_EXTRA_HITPAUSE, 2);
set_hitbox_value(AT_NAIR, 6, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_NAIR, 6, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NAIR, 6, HG_HIT_SFX, asset_get("sfx_icehit_weak2"));

set_hitbox_value(AT_NAIR, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 7, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 7, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_NAIR, 7, HG_LIFETIME, 1);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_X, 40);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NAIR, 7, HG_WIDTH, 65);
set_hitbox_value(AT_NAIR, 7, HG_HEIGHT, 65);
set_hitbox_value(AT_NAIR, 7, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 7, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 7, HG_ANGLE, 45);
set_hitbox_value(AT_NAIR, 7, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NAIR, 7, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 7, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NAIR, 7, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 7, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NAIR, 7, HG_HIT_SFX, asset_get("sfx_icehit_medium2"));

set_hitbox_value(AT_NAIR, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 8, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 8, HG_WINDOW_CREATION_FRAME, 11);
set_hitbox_value(AT_NAIR, 8, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_X, -30);
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_Y, -25);
set_hitbox_value(AT_NAIR, 8, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 8, HG_HEIGHT, 60);
set_hitbox_value(AT_NAIR, 8, HG_PRIORITY, 6);
set_hitbox_value(AT_NAIR, 8, HG_DAMAGE, 3);
set_hitbox_value(AT_NAIR, 8, HG_ANGLE, 45);
set_hitbox_value(AT_NAIR, 8, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NAIR, 8, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 8, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NAIR, 8, HG_HITPAUSE_SCALING, 0.2);
set_hitbox_value(AT_NAIR, 8, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NAIR, 8, HG_HIT_SFX, asset_get("sfx_icehit_medium2"));


