// set_attack_value(AT_DSPECIAL_2, AG_CATEGORY, 2);
// set_attack_value(AT_DSPECIAL_2, AG_SPRITE, sprite_get("dspecial"));
// set_attack_value(AT_DSPECIAL_2, AG_NUM_WINDOWS, 4);
// set_attack_value(AT_DSPECIAL_2, AG_HAS_LANDING_LAG, 4);
// set_attack_value(AT_DSPECIAL_2, AG_OFF_LEDGE, 1);
// set_attack_value(AT_DSPECIAL_2, AG_AIR_SPRITE, sprite_get("dspecial"));
// set_attack_value(AT_DSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("dspecial_hurt"));

// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_TYPE, 1);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_LENGTH, 5);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 1);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HSPEED_TYPE, 0);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_VSPEED_TYPE, 0);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HSPEED, 0);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_VSPEED, 0);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HAS_SFX, 1);
// set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_SFX, asset_get("sfx_birdflap"));

// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_TYPE, 1);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_LENGTH, 16);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_HSPEED_TYPE, 1);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_VSPEED_TYPE, 1);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_HSPEED, 0);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_VSPEED, 0);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.06);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAMES, 2);
// set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAME_START, 1);

// set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_TYPE, 1);
// set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_LENGTH, 7);
// set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 4);
// set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 8);

// set_num_hitboxes(AT_DSPECIAL_2, 1);

// set_hitbox_value(AT_DSPECIAL_2, 1, HG_PARENT_HITBOX, 1);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_TYPE, 1);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_WINDOW, 2);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_WINDOW_CREATION_FRAME, 0);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_LIFETIME, 2);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_ANGLE, 65);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_Y, -40);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_WIDTH, 100);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_HEIGHT, 100);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_PRIORITY, 1);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_DAMAGE, 4);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_KNOCKBACK, 6);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_KNOCKBACK_SCALING, .6);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_HITPAUSE, 3);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_VISUAL_EFFECT, 20);
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_absa_singlezap1"));
// set_hitbox_value(AT_DSPECIAL_2, 1, HG_ANGLE_FLIPPER, 6);
// // set_hitbox_value(AT_DSPECIAL_2, 1, HG_TECHABLE, 3);
// // set_hitbox_value(AT_DSPECIAL_2, 1, HG_GROUNDEDNESS, 2);

// set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_TYPE, 2);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_LIFETIME, 80);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_WIDTH, 30);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_HEIGHT, 10);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PRIORITY, 3);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_DAMAGE, 4);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_SHAPE, 1);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_ANGLE, 270);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_ANGLE_FLIPPER, 0);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_KNOCKBACK, 5);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_KNOCKBACK_SCALING, 0);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_VISUAL_EFFECT_Y_OFFSET, -16);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITSTUN_MULTIPLIER, 20);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_HITPAUSE, 13);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITPAUSE_SCALING, .3);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_SPRITE, sprite_get("wave"));
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_MASK, -1);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, .4);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_absa_cloud_pop"));
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_HSPEED, 15);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_TECHABLE, 3);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_FORCE_FLINCH, 1);
// set_hitbox_value(AT_DSPECIAL_2, 2, HG_GROUNDEDNESS, 1);