sprite_change_offset("idle", 33, 72);
sprite_change_offset("hurt", 33, 78);
sprite_change_offset("hurtground", 33, 78);
sprite_change_offset("bighurt", 33, 78);
sprite_change_offset("spinhurt", 33, 78);
sprite_change_offset("uphurt", 33, 78);
sprite_change_offset("downhurt", 33, 78);
sprite_change_offset("bouncehurt", 33, 78);
sprite_change_offset("crouch", 33, 78);
sprite_change_offset("walk", 33, 78);
sprite_change_offset("walkturn", 33, 78);
sprite_change_offset("dash", 33, 78);
sprite_change_offset("dashstart", 33, 78);
sprite_change_offset("dashstop", 33, 78);
sprite_change_offset("dashturn", 33, 78);
sprite_change_offset("crouch_hurtbox", 28, 66);

sprite_change_offset("jumpstart", 45, 97);
sprite_change_offset("jump", 45, 97);
sprite_change_offset("doublejump", 33, 72);
sprite_change_offset("doublejump2", 33, 72);
sprite_change_offset("walljump", 41, 69);
sprite_change_offset("pratfall", 41, 76);
sprite_change_offset("land", 45, 97);
sprite_change_offset("landinglag", 45, 97);

sprite_change_offset("parry", 41, 78);
sprite_change_offset("roll_forward", 33, 81);
sprite_change_offset("roll_backward", 33, 81);
sprite_change_offset("airdodge", 33, 82);
sprite_change_offset("waveland", 33, 78);
sprite_change_offset("tech", 33, 78);

sprite_change_offset("jab", 76, 94);
sprite_change_offset("dattack", 48, 94);
sprite_change_offset("ftilt", 48, 94);
sprite_change_offset("dtilt", 33, 78);
sprite_change_offset("utilt", 37, 86);
sprite_change_offset("nair", 47, 68);
sprite_change_offset("fair", 72, 98);
sprite_change_offset("bair", 51, 67);
sprite_change_offset("uair", 45, 114);
sprite_change_offset("dair", 33, 72);
sprite_change_offset("fstrong", 46, 74);
sprite_change_offset("ustrong", 48, 94);
sprite_change_offset("dstrong", 33, 78);
sprite_change_offset("nspecial", 37, 88);
sprite_change_offset("nspecial_air", 37, 90);
sprite_change_offset("fspecial", 51, 94);
sprite_change_offset("fspecial_air", 51, 96);
sprite_change_offset("uspecial", 45, 96);
sprite_change_offset("uspecial_air", 45, 96);
sprite_change_offset("dspecial", 47, 78);
sprite_change_offset("taunt", 47, 78);

sprite_change_offset("plat", 44, 8);
set_victory_theme( sound_get( "victory" ));
set_victory_bg( sprite_get( "custom" ));
sprite_change_offset("intro", 122, 375);
sprite_change_offset("article_offscreen", 33, 33);
sprite_change_offset("arrow_indicator", -25, 50);
sprite_change_offset("phone_open", 39, 72);

sprite_change_offset("kirby_ryu", 46, 82);
sprite_change_offset("sign_ryu", 18, 41);
sprite_change_offset("kart_ryu", 6, 6);

sprite_change_offset("proj1", 0, 50);
sprite_change_offset("proj2", 0, 65);
sprite_change_offset("proj_smoke", 51, 94);
sprite_change_offset("proj_draw1", 51, 94);
sprite_change_offset("proj_draw2", 51, 94);
sprite_change_offset("izuna", 49, 77);
sprite_change_offset("izuna2", 49, 77);
sprite_change_offset("strongf1", 49, 38);
sprite_change_offset("strongf2", 49, 38);
sprite_change_offset("strongb1", 49, 38);
sprite_change_offset("strongb2", 49, 38);
sprite_change_offset("clone_hit", 48, 48);

sprite_change_offset("idle_clone", 33, 72);
sprite_change_offset("dash_clone", 33, 78);
sprite_change_offset("jab_clone", 76, 94);
sprite_change_offset("ftilt_clone", 48, 94);
sprite_change_offset("dtilt_clone", 33, 78);
sprite_change_offset("utilt_clone", 37, 86);
sprite_change_offset("dattack_clone", 48, 94);
sprite_change_offset("fstrong_clone", 46, 74);
sprite_change_offset("dstrong_clone", 33, 78);
sprite_change_offset("ustrong_clone", 48, 94);
sprite_change_offset("nair_clone", 47, 68);
sprite_change_offset("fair_clone", 72, 98);
sprite_change_offset("bair_clone", 51, 67);
sprite_change_offset("uair_clone", 45, 114);
sprite_change_offset("dair_clone", 33, 72);
sprite_change_offset("taunt_clone", 40, 78);
