set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("extra2"));
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 2);
set_attack_value(AT_EXTRA_2, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_EXTRA_2, AG_AIR_SPRITE, sprite_get("extra2"));
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("extra2_hurt"));


set_window_value(AT_EXTRA_2, 1, AG_WINDOW_TYPE, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 25);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX, sound_get("vRT"));
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_LENGTH, 24);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX, asset_get("sfx_clairen_spin"));
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX_FRAME, 0);




set_num_hitboxes(AT_EXTRA_2,3);


set_hitbox_value(AT_EXTRA_2, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_X, 26);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_Y, -30);
set_hitbox_value(AT_EXTRA_2, 1, HG_WIDTH, 88);
set_hitbox_value(AT_EXTRA_2, 1, HG_HEIGHT, 28);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE, 40);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, 20);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));
set_hitbox_value(AT_EXTRA_2, 1, HG_HITSTUN_MULTIPLIER, 0.6);

set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 151);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_X, 40);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_Y, -36);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_SPRITE, sprite_get("RT"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_HSPEED, 11);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ANIM_SPEED, 0.6);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 2, HG_WIDTH, 95);
set_hitbox_value(AT_EXTRA_2, 2, HG_HEIGHT, 30);
set_hitbox_value(AT_EXTRA_2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE, 40);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW, 999);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_X, 40);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_Y, -36);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ANIM_SPEED, 0.6);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 3, HG_WIDTH, 125);
set_hitbox_value(AT_EXTRA_2, 3, HG_HEIGHT, 50);
set_hitbox_value(AT_EXTRA_2, 3, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 80);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITSTUN_MULTIPLIER, 1.3);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, true );
set_hitbox_value(AT_EXTRA_2, 3, HG_IGNORES_PROJECTILES, true );
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW, 999);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_LIFETIME, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_X, 40);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_Y, -36);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_ANIM_SPEED, 0.6);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_2, 4, HG_WIDTH, 125);
set_hitbox_value(AT_EXTRA_2, 4, HG_HEIGHT, 50);
set_hitbox_value(AT_EXTRA_2, 4, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_ANGLE, 30);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_2, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITSTUN_MULTIPLIER, 1.3);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_PROJECTILE_IS_TRANSCENDENT, true );
set_hitbox_value(AT_EXTRA_2, 4, HG_IGNORES_PROJECTILES, true );