/// NOICE
sprite_change_offset("idle", 16, 39);
sprite_change_offset("hurt",  16, 39);
sprite_change_offset("crouch", 16, 39);
sprite_change_offset("walk", 16, 39);
sprite_change_offset("walkturn", 16, 39);
sprite_change_offset("dash", 16, 39);
sprite_change_offset("dashstart", 16, 39);
sprite_change_offset("dashstop", 16, 39);
sprite_change_offset("dashturn", 16, 39);


sprite_change_offset("jumpstart",16, 39);
sprite_change_offset("jump", 16, 39);
sprite_change_offset("doublejump", 16, 39);
sprite_change_offset("walljump", 16, 39);
sprite_change_offset("pratfall",16, 39);
sprite_change_offset("land",16, 39);
sprite_change_offset("landinglag",16, 39);

sprite_change_offset("parry", 16, 39);
sprite_change_offset("roll_forward",16, 39);
sprite_change_offset("roll_backward",16, 39);
sprite_change_offset("airdodge",16, 39);
sprite_change_offset("waveland",16, 39);
sprite_change_offset("tech",16, 39);

sprite_change_offset("pull_item",16, 39);
sprite_change_offset("pull_item_air",16, 39);
sprite_change_offset("nthrow",16, 39);
sprite_change_offset("nthrow_air",16, 39);
sprite_change_offset("dattack", 0, 0);
sprite_change_offset("uthrow",16, 39);
sprite_change_offset("uthrow_air",16, 39);
sprite_change_offset("fthrow",16, 39);
sprite_change_offset("utilt",24, 39,true);
sprite_change_offset("ftilt",24, 39,true);
sprite_change_offset("dtilt",24, 39,true);
sprite_change_offset("fthrow_air",16, 39);
sprite_change_offset("dthrow",16, 39);
sprite_change_offset("dthrow_air",16, 39);
sprite_change_offset("fstrong", 0, 0);
sprite_change_offset("ustrong",16, 39,true);
sprite_change_offset("dstrong", 0, 0);
sprite_change_offset("dattack", 16, 39, true);
sprite_change_offset("jab", 16, 39, true);
sprite_change_offset("dair", 16, 39, true);
sprite_change_offset("nair", 17, 39, true);
sprite_change_offset("uair", 24, 39, true);
sprite_change_offset("bair", 24, 39, true);
sprite_change_offset("fair", 24, 39, true);
sprite_change_offset("nspecial", 0, 0);
sprite_change_offset("fspecial", 0, 0);
sprite_change_offset("uspecial", 0, 0);
sprite_change_offset("dspecial", 0, 0);
sprite_change_offset("taunt",16, 39);
sprite_change_offset("item_swing_squeaky_hammer",32, 63);

sprite_change_offset("player_arrow", 7, 10);
sprite_change_offset("plat", 32, 0);
sprite_change_offset("gunk",6,6);
sprite_change_offset("shadow_bug",3,3);
sprite_change_offset("shadow_bug_inverse",3,3);
sprite_change_offset("shadow_bug_2x",6,6);
sprite_change_offset("mega_mushroom",16,32);
sprite_change_offset("mushroom",8,16);
sprite_change_offset("super_star",8,16);
sprite_change_offset("curry",9,12);
sprite_change_offset("metal_box",10,18);
sprite_change_offset("item_held_pop",8,16);
sprite_change_offset("superscope_bullet_small",8,8);
sprite_change_offset("superscope_bullet_large",16,16);
sprite_change_offset("item_held_boomerang",28,14);
sprite_change_offset("item_held_superscope",32,25);
sprite_change_offset("item_held_bumper",32,32);
sprite_change_offset("item_held_subspace_bomb",32,36);
sprite_change_offset("item_held_squeaky_hammer",24,50);
sprite_change_offset("item_held_gust_bellows",24,24);
sprite_change_offset("gust_bellows_dropped",24,40);
sprite_change_offset("subspace_hole",256,256);
sprite_change_offset("subspace_hole_grow",256,256);
sprite_change_offset("item_held_beamsword",48,48);
sprite_change_offset("item_fswing_beamsword",40,41);
sprite_change_offset("item_uswing_beamsword",35,64);
sprite_change_offset("item_dswing_beamsword",32,48);