sprite_change_offset("idle", 47, 40, true);
sprite_change_offset("hurt", 46, 52, true);
sprite_change_offset("hurtground", 47, 69, true);
sprite_change_offset("uphurt", 47, 69, true);
sprite_change_offset("downhurt", 47, 69, true);
sprite_change_offset("bouncehurt", 47, 69, true);
sprite_change_offset("bighurt", 28, 52, true);
sprite_change_offset("crouch", 47, 40, true);
sprite_change_offset("walk", 52, 69, true);
sprite_change_offset("walkturn", 52, 69, true);
sprite_change_offset("dash", 52, 69, true);
sprite_change_offset("dashstart", 52, 69, true);
sprite_change_offset("dashstop", 47, 69, true);
sprite_change_offset("dashturn", 52, 69, true);

sprite_change_offset("jumpstart", 47, 69, true);
sprite_change_offset("jump", 46, 58, true);
sprite_change_offset("doublejump", 46, 58, true);
sprite_change_offset("walljump", 46, 58, true);
sprite_change_offset("pratfall", 46, 58, true);
sprite_change_offset("land", 47, 40, true);
sprite_change_offset("landinglag", 47, 40, true);

sprite_change_offset("parry", 47, 49, true);
sprite_change_offset("roll_forward", 45, 40, true);
sprite_change_offset("roll_backward", 47, 40, true);
sprite_change_offset("airdodge", 52, 65, true);
//sprite_change_offset("airdodge_back", 80, 180, true);
sprite_change_offset("waveland", 47, 69, true);
sprite_change_offset("tech", 47, 69, true);

sprite_change_offset("jab", 52, 64, true);
sprite_change_offset("dattack", 52, 69, true);
sprite_change_offset("ftilt", 52, 69, true);
sprite_change_offset("dtilt", 40, 67, true);
sprite_change_offset("utilt", 57, 69, true);
sprite_change_offset("nair", 50, 70, true);
sprite_change_offset("fair", 52, 69, true);
sprite_change_offset("bair", 80, 60, true);
sprite_change_offset("uair", 50, 60, true);
sprite_change_offset("uair_alts", 50, 60, true);
sprite_change_offset("dair", 50, 60, true);
sprite_change_offset("fstrong", 52, 69, true);
sprite_change_offset("ustrong", 52, 88, true);
sprite_change_offset("dstrong", 57, 79, true);
sprite_change_offset("nspecial", 52,60, true);
sprite_change_offset("fspecial", 52, 65, true);
sprite_change_offset("uspecial", 47, 69, true);
sprite_change_offset("uspecial_grounded", 47, 69, true);
sprite_change_offset("dspecial", 52,60, true);
sprite_change_offset("taunt", 52,86, true);
sprite_change_offset("taunt_crystal", 40,40, true);

sprite_change_offset("plat", 100/2, 0, true);

sprite_change_offset("feri_costume", 84, 114);
sprite_change_offset("miiverse_post", 60, 30);

sprite_change_offset("nspecial_sword", 70, 70);
sprite_change_offset("nspecial_swordtrail", 70, 70);
sprite_change_offset("fstrong_projectile", 120, 80);
sprite_change_offset("fstrong_projectile_trail", 120, 80);
sprite_change_offset("fspecial_projectile", 40, 40);
sprite_change_offset("fspecial_projectile_trail", 40, 40);
sprite_change_offset("fx_trailvertical", 80, 80);
sprite_change_offset("star_tiny", 30, 30);
sprite_change_offset("feathers", 20, 20);
sprite_change_offset("ustrong_lightning", 60, 160);
sprite_change_offset("ustrong_lightning2", 60, 240);
sprite_change_offset("shockwave", 30, 120);
sprite_change_offset("shockwave_short", 30, 120);
sprite_change_offset("shockwave_short2", 30, 120);
sprite_change_offset("shockwave2", 40, 60);
sprite_change_offset("fx_slam", 100, 120);
sprite_change_offset("star_big_collision", 30, 30);
sprite_change_offset("tornado", 50, 100);
sprite_change_offset("tornado_alts", 50, 100);
sprite_change_offset("dspecial_time_rift", 50, 50, true);
sprite_change_offset("dspecial_time_rift_alts", 50, 50, true);
sprite_change_offset("dspecial_time_rift_laser", 80, 80, true);
sprite_change_offset("dspecial_time_rift_laser_alts", 80, 80, true);
sprite_change_offset("dspecial_time_rift_particle", 10, 10, true);
sprite_change_offset("dspecial_time_rift_particle_alts", 10, 10, true);
sprite_change_offset("star", 20, 20);
sprite_change_offset("star_big_collision", 30, 30);
sprite_change_offset("teleport", 30, 60);
sprite_change_offset("teleport2", 30, 60);
sprite_change_offset("dust_sharp_big", 60, 80);
sprite_change_offset("dust_sharp", 30, 40);
sprite_change_offset("fx_lightbeams", 400, 400);
sprite_change_offset("explosion_ball3", 100, 100);