sprite_change_offset("idle", 32, 47);
sprite_change_offset("crouch", 32, 47);
sprite_change_offset("walk", 32, 47);
sprite_change_offset("walkturn", 32, 47);
sprite_change_offset("dash", 32, 47);
sprite_change_offset("dashstart", 32, 47);
sprite_change_offset("dashstop", 32, 47);
sprite_change_offset("dashturn", 32, 47);
sprite_change_offset("p1ball", 16,16);
sprite_change_offset("p2ball", 16,16);
sprite_change_offset("p3ball", 16,16);
sprite_change_offset("p4ball", 16,16);
sprite_change_offset("ball_mask", 20,20);
sprite_change_offset("screen_effect", 960,540);
sprite_change_offset("wall1", 39,270);
sprite_change_offset("wall2", 402,34);
sprite_change_offset("smear", 240,15);
sprite_change_offset("p1plasma_hitfx", 64,64);
sprite_change_offset("p2plasma_hitfx", 64,64);
sprite_change_offset("p3plasma_hitfx", 64,64);
sprite_change_offset("p4plasma_hitfx", 64,64);
sprite_change_offset("angleindicator", 6,11);
sprite_change_offset("plasma_hitfx2", 64,64);
sprite_change_offset("dust", 114,134);
sprite_change_offset("charge_effect", 64,64);

sprite_change_offset("hurt", 32, 47);
sprite_change_offset("bighurt", 32, 47);
sprite_change_offset("hurtground", 32, 47);
sprite_change_offset("uphurt", 32, 47);
sprite_change_offset("downhurt", 32, 47);
sprite_change_offset("spinhurt", 32, 47);
sprite_change_offset("bouncehurt", 32, 47);

sprite_change_offset("hurt", 32, 47);
sprite_change_offset("jumpstart", 32, 47);
sprite_change_offset("jump", 32, 47);
sprite_change_offset("doublejump", 32, 47);
sprite_change_offset("walljump", 32, 47);
sprite_change_offset("pratfall", 32, 47);
sprite_change_offset("land", 32, 47);
sprite_change_offset("landinglag", 32, 47);
sprite_change_offset("spr_wall", 1, 1);

sprite_change_offset("parry", 32, 47);
sprite_change_offset("roll_forward", 32, 47);
sprite_change_offset("roll_backward", 32, 47);
sprite_change_offset("airdodge", 32, 47);
sprite_change_offset("waveland", 32, 47);
sprite_change_offset("tech", 32, 47);
sprite_change_offset("ball_explodep1", 64, 64);
sprite_change_offset("ball_explodep2", 64, 64);
sprite_change_offset("ball_explodep3", 64, 64);
sprite_change_offset("ball_explodep4", 64, 64);

sprite_change_offset("jab", 32, 47);
sprite_change_offset("jab_hurt", 64, 94);
sprite_change_offset("spr_hurtbox_idle", 64, 94);
sprite_change_offset("spr_crouch_hurtbox", 64, 94);
sprite_change_offset("dattack", 32, 47);
sprite_change_offset("dattack_hurt", 64, 94);
sprite_change_offset("ftilt", 32, 47);
sprite_change_offset("ftilt_hurt", 64, 94);
sprite_change_offset("dtilt", 32, 47);
sprite_change_offset("dtilt_hurt", 64, 94);
sprite_change_offset("utilt", 32, 47);
sprite_change_offset("utilt_hurt", 64, 94);
sprite_change_offset("nair", 32, 47);
sprite_change_offset("nair_hurt", 64, 94);
sprite_change_offset("fair", 32, 47);
sprite_change_offset("fair_hurt", 64, 94);
sprite_change_offset("bair", 32, 47);
sprite_change_offset("bair_hurt", 64, 94);
sprite_change_offset("uair", 32, 47);
sprite_change_offset("uair_hurt", 64, 94);
sprite_change_offset("dair", 32, 47);
sprite_change_offset("dair_hurt", 64, 94);
sprite_change_offset("fstrong", 32, 47);
sprite_change_offset("fstrong_hurt", 64, 94);
sprite_change_offset("ustrong", 32, 67);
sprite_change_offset("ustrong_hurt", 64, 134);
sprite_change_offset("dstrong", 38, 47);
sprite_change_offset("dstrong_hurt", 76, 94);
sprite_change_offset("nspecial", 32, 47);
sprite_change_offset("nspecial_p1", 32, 47);
sprite_change_offset("nspecial_air_p1", 32, 47);
sprite_change_offset("nspecial_p2", 32, 47);
sprite_change_offset("nspecial_air_p2", 32, 47);
sprite_change_offset("nspecial_p3", 32, 47);
sprite_change_offset("nspecial_air_p3", 32, 47);
sprite_change_offset("nspecial_p4", 32, 47);
sprite_change_offset("nspecial_air_p4", 32, 47);
sprite_change_offset("nspecial_air_nothing", 32, 47);
sprite_change_offset("nspecial_nothing", 32, 47);
sprite_change_offset("nspecial_air", 32, 47);
sprite_change_offset("nspecial_hurt", 64, 94);
sprite_change_offset("nspecial_air_hurt", 64, 94);
sprite_change_offset("fspecial", 32, 47);
sprite_change_offset("fspecial_hurt", 64, 94);
sprite_change_offset("fspecial_air", 32, 47);
sprite_change_offset("fspecial_air_hurt", 64, 94);
sprite_change_offset("uspecial", 32, 47);
sprite_change_offset("uspecial_air", 32, 47);
sprite_change_offset("uspecial_hurt", 64, 94);
sprite_change_offset("uspecial_air_hurt", 64, 94);
sprite_change_offset("dspecial", 32, 47);
sprite_change_offset("dspecial_hurt", 64, 94);
sprite_change_offset("taunt", 32, 47);
sprite_change_offset("taunt_hurt", 64, 94);

sprite_change_offset("plat", 46, 8);
sprite_change_offset("large_plasma_hfx",128,128);
sprite_change_offset("plasma_hfx",86, 90);
sprite_change_offset("spr_exp", 48, 48);
set_victory_theme( sound_get( "victorytheme" ));
set_victory_bg( sprite_get( "victoryroyalebg" ));
//