set_attack_value(AT_USTRONG, AG_SPRITE, sprite_get("ustrong"));
set_attack_value(AT_USTRONG, AG_NUM_WINDOWS, 5);
set_attack_value(AT_USTRONG, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_USTRONG, AG_OFF_LEDGE, 1);
set_attack_value(AT_USTRONG, AG_CATEGORY, 2);
set_attack_value(AT_USTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_USTRONG, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_USTRONG, AG_HURTBOX_SPRITE, sprite_get("ustrong_hurt"));

//Charge
set_window_value(AT_USTRONG, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_USTRONG, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_USTRONG, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG, 1, AG_WINDOW_CUSTOM_GRAVITY, 0.65);
set_window_value(AT_USTRONG, 1, AG_WINDOW_SFX, asset_get("sfx_jumpground"));

//Spin 1
set_window_value(AT_USTRONG, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_LENGTH, 16);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HSPEED, 0.5);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_USTRONG, 2, AG_WINDOW_VSPEED, -8);
set_window_value(AT_USTRONG, 2, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USTRONG, 2, AG_WINDOW_CUSTOM_GRAVITY, 1.1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.25);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));

//Spin 2
set_window_value(AT_USTRONG, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_LENGTH, 20);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_USTRONG, 3, AG_WINDOW_VSPEED, -8);
set_window_value(AT_USTRONG, 3, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USTRONG, 3, AG_WINDOW_CUSTOM_GRAVITY, 1.1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.25);
set_window_value(AT_USTRONG, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_USTRONG, 3, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));

//Spin 3
set_window_value(AT_USTRONG, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_LENGTH, 20);
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_USTRONG, 4, AG_WINDOW_VSPEED, -10);
set_window_value(AT_USTRONG, 4, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USTRONG, 4, AG_WINDOW_CUSTOM_GRAVITY, 1.1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.25);
set_window_value(AT_USTRONG, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_USTRONG, 4, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));

//Ending
set_window_value(AT_USTRONG, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_USTRONG, 5, AG_WINDOW_LENGTH, 10);
set_window_value(AT_USTRONG, 5, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_USTRONG, 5, AG_WINDOW_ANIM_FRAME_START, 17);
set_window_value(AT_USTRONG, 5, AG_WINDOW_CUSTOM_GRAVITY, 0.4);

set_num_hitboxes(AT_USTRONG, 8);

set_hitbox_value(AT_USTRONG, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_USTRONG, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_X, 9);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_USTRONG, 1, HG_WIDTH, 120);
set_hitbox_value(AT_USTRONG, 1, HG_HEIGHT, 76);
set_hitbox_value(AT_USTRONG, 1, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 1, HG_ANGLE, 80);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_KNOCKBACK, 8.5);
set_hitbox_value(AT_USTRONG, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 1, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 1, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 1, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_USTRONG, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_X, 21);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_Y, -47);
set_hitbox_value(AT_USTRONG, 2, HG_WIDTH, 93);
set_hitbox_value(AT_USTRONG, 2, HG_HEIGHT, 101);
set_hitbox_value(AT_USTRONG, 2, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 2, HG_ANGLE, 100);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 2, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 2, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 2, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW, 3);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_USTRONG, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_X, -5);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_Y, -51);
set_hitbox_value(AT_USTRONG, 3, HG_WIDTH, 98);
set_hitbox_value(AT_USTRONG, 3, HG_HEIGHT, 72);
set_hitbox_value(AT_USTRONG, 3, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 3, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 3, HG_ANGLE, 65);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 3, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 3, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 3, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 4, HG_WINDOW, 3);
set_hitbox_value(AT_USTRONG, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_USTRONG, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_X, 9);
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_Y, -32);
set_hitbox_value(AT_USTRONG, 4, HG_WIDTH, 120);
set_hitbox_value(AT_USTRONG, 4, HG_HEIGHT, 76);
set_hitbox_value(AT_USTRONG, 4, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 4, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 4, HG_ANGLE, 80);
set_hitbox_value(AT_USTRONG, 4, HG_BASE_KNOCKBACK, 8.5);
set_hitbox_value(AT_USTRONG, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 4, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 4, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 4, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 4, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 4, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 4, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 5, HG_WINDOW, 3);
set_hitbox_value(AT_USTRONG, 5, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_USTRONG, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_X, 21);
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_Y, -47);
set_hitbox_value(AT_USTRONG, 5, HG_WIDTH, 93);
set_hitbox_value(AT_USTRONG, 5, HG_HEIGHT, 101);
set_hitbox_value(AT_USTRONG, 5, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 5, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 5, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 5, HG_ANGLE, 100);
set_hitbox_value(AT_USTRONG, 5, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USTRONG, 5, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 5, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 5, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 5, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 5, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 5, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 5, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 6, HG_PARENT_HITBOX, 6);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 6, HG_WINDOW, 4);
set_hitbox_value(AT_USTRONG, 6, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_USTRONG, 6, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_X, 9);
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_Y, -32);
set_hitbox_value(AT_USTRONG, 6, HG_WIDTH, 120);
set_hitbox_value(AT_USTRONG, 6, HG_HEIGHT, 76);
set_hitbox_value(AT_USTRONG, 6, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 6, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 6, HG_DAMAGE, 2);
set_hitbox_value(AT_USTRONG, 6, HG_ANGLE, 80);
set_hitbox_value(AT_USTRONG, 6, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG, 6, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USTRONG, 6, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USTRONG, 6, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_USTRONG, 6, HG_DRIFT_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 6, HG_SDI_MULTIPLIER, 0.01);
set_hitbox_value(AT_USTRONG, 6, HG_HIT_SFX, sound_get("hit1"));
set_hitbox_value(AT_USTRONG, 6, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_USTRONG, 7, HG_PARENT_HITBOX, 7);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 7, HG_WINDOW, 4);
set_hitbox_value(AT_USTRONG, 7, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_USTRONG, 7, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_X, 21);
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_Y, -47);
set_hitbox_value(AT_USTRONG, 7, HG_WIDTH, 93);
set_hitbox_value(AT_USTRONG, 7, HG_HEIGHT, 101);
set_hitbox_value(AT_USTRONG, 7, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 7, HG_PRIORITY, 4);
set_hitbox_value(AT_USTRONG, 7, HG_DAMAGE, 3);
set_hitbox_value(AT_USTRONG, 7, HG_ANGLE, 45);
set_hitbox_value(AT_USTRONG, 7, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USTRONG, 7, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_USTRONG, 7, HG_BASE_HITPAUSE, 6.5);
set_hitbox_value(AT_USTRONG, 7, HG_HITPAUSE_SCALING, 0.35);
set_hitbox_value(AT_USTRONG, 7, HG_HIT_SFX, asset_get("sfx_troupple_fish_splash_in"));
set_hitbox_value(AT_USTRONG, 7, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_USTRONG, 8, HG_PARENT_HITBOX, 8);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 8, HG_WINDOW, 4);
set_hitbox_value(AT_USTRONG, 8, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_USTRONG, 8, HG_LIFETIME, 4);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_X, 43);
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_Y, -80);
set_hitbox_value(AT_USTRONG, 8, HG_WIDTH, 60);
set_hitbox_value(AT_USTRONG, 8, HG_HEIGHT, 60);
set_hitbox_value(AT_USTRONG, 8, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 8, HG_PRIORITY, 6);
set_hitbox_value(AT_USTRONG, 8, HG_DAMAGE, 7);
set_hitbox_value(AT_USTRONG, 8, HG_ANGLE, 80);
set_hitbox_value(AT_USTRONG, 8, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_USTRONG, 8, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_USTRONG, 8, HG_BASE_HITPAUSE, 7.5);
set_hitbox_value(AT_USTRONG, 8, HG_HITPAUSE_SCALING, 0.85);
set_hitbox_value(AT_USTRONG, 8, HG_HIT_SFX, asset_get("sfx_troupple_fish_splash_in"));
set_hitbox_value(AT_USTRONG, 8, HG_HITBOX_GROUP, 1);