set_attack_value(AT_UAIR, AG_CATEGORY, 1);
set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));
set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 3);
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_UAIR, AG_LANDING_LAG, 12);

set_window_value(AT_UAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 18);
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 17);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));

set_window_value(AT_UAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED, -4);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED_TYPE, 2);

set_window_value(AT_UAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_UAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_UAIR, 3);

//pig
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 20);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 240);
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 80);
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 100);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, .8);
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_shovel_hit_heavy2"));
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_SPRITE, sprite_get("stupidasspig"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_COLLISION_SPRITE, sprite_get("stupidasspig_mask"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_ANIM_SPEED, .7);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_VSPEED, -16);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_GRAVITY, 0.8);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_DESTROY_EFFECT, 304);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_UAIR, 1, HG_HIT_LOCKOUT, 2);

//swing
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, 5);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -40);
set_hitbox_value(AT_UAIR, 2, HG_WIDTH, 50);
set_hitbox_value(AT_UAIR, 2, HG_HEIGHT, 70);
set_hitbox_value(AT_UAIR, 2, HG_SHAPE, 0);
set_hitbox_value(AT_UAIR, 2, HG_PRIORITY, 5);
set_hitbox_value(AT_UAIR, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE, 70);
set_hitbox_value(AT_UAIR, 2, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_UAIR, 2, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_UAIR, 2, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_UAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_UAIR, 2, HG_HIT_LOCKOUT, 2);

//Falling Coin
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW, 80);
set_hitbox_value(AT_UAIR, 3, HG_LIFETIME, 90);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_X, 35);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_Y, -40);
set_hitbox_value(AT_UAIR, 3, HG_WIDTH, 15);
set_hitbox_value(AT_UAIR, 3, HG_HEIGHT, 15);
set_hitbox_value(AT_UAIR, 3, HG_SHAPE, 0);
set_hitbox_value(AT_UAIR, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_UAIR, 3, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 3, HG_BASE_KNOCKBACK, 0);
set_hitbox_value(AT_UAIR, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_UAIR, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_UAIR, 3, HG_HITSTUN_MULTIPLIER, -1);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_UAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_SPRITE, sprite_get("coin"));
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_ANIM_SPEED, .35);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_VSPEED, -7);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_GRAVITY, 0.3);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_PLASMA_SAFE, true);

//pig hit collision
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW, 20);
set_hitbox_value(AT_UAIR, 4, HG_LIFETIME, 9999);
set_hitbox_value(AT_UAIR, 4, HG_WIDTH, 100);
set_hitbox_value(AT_UAIR, 4, HG_HEIGHT, 100);
set_hitbox_value(AT_UAIR, 4, HG_PRIORITY, 0);
set_hitbox_value(AT_UAIR, 4, HG_EFFECT, 11);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_UAIR, 4, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_UAIR, 4, HG_IGNORES_PROJECTILES, true);