set_attack_value(AT_DATTACK, AG_SPRITE, sprite_get(string(spr_dir) + "_dattack"));
set_attack_value(AT_DATTACK, AG_HURTBOX_SPRITE, sprite_get(string(spr_dir) + "_dattack_hurt"));
set_attack_value(AT_DATTACK, AG_NUM_WINDOWS, 5);
set_attack_value(AT_DATTACK, AG_OFF_LEDGE, 1);

set_window_value(AT_DATTACK, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_DATTACK, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DATTACK, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DATTACK, 1, AG_WINDOW_HSPEED, 6);
set_window_value(AT_DATTACK, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DATTACK, 1, AG_WINDOW_SFX, sound_get("boost_start"));

set_window_value(AT_DATTACK, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_DATTACK, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_DATTACK, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_DATTACK, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DATTACK, 2, AG_WINDOW_HSPEED, 8);

set_window_value(AT_DATTACK, 3, AG_WINDOW_LENGTH, 3);
set_window_value(AT_DATTACK, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DATTACK, 3, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_DATTACK, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DATTACK, 3, AG_WINDOW_HSPEED, 8);

set_window_value(AT_DATTACK, 4, AG_WINDOW_TYPE, 9);
set_window_value(AT_DATTACK, 4, AG_WINDOW_LENGTH, 14);
set_window_value(AT_DATTACK, 4, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_DATTACK, 4, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DATTACK, 4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DATTACK, 4, AG_WINDOW_HSPEED, 10);
set_window_value(AT_DATTACK, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DATTACK, 4, AG_WINDOW_SFX, sound_get("boost_run"));

set_window_value(AT_DATTACK, 5, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DATTACK, 5, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DATTACK, 5, AG_WINDOW_ANIM_FRAME_START, 15);
set_window_value(AT_DATTACK, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DATTACK, 5, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DATTACK, 5, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_DATTACK, 4);

set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DATTACK, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 1, HG_LIFETIME, 12);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_X, 20);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_Y, -35);
set_hitbox_value(AT_DATTACK, 1, HG_WIDTH, 60);
set_hitbox_value(AT_DATTACK, 1, HG_HEIGHT, 70);
set_hitbox_value(AT_DATTACK, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_DATTACK, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_DATTACK, 1, HG_ANGLE, 50);
set_hitbox_value(AT_DATTACK, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DATTACK, 1, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_DATTACK, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DATTACK, 1, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_DATTACK, 1, HG_VISUAL_EFFECT, 112);
set_hitbox_value(AT_DATTACK, 1, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));

set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DATTACK, 2, HG_WINDOW, 4);
set_hitbox_value(AT_DATTACK, 2, HG_LIFETIME, 9);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_Y, -35);
set_hitbox_value(AT_DATTACK, 2, HG_WIDTH, 60);
set_hitbox_value(AT_DATTACK, 2, HG_HEIGHT, 70);
set_hitbox_value(AT_DATTACK, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_DATTACK, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_DATTACK, 2, HG_ANGLE, 130);
set_hitbox_value(AT_DATTACK, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DATTACK, 2, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_DATTACK, 2, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DATTACK, 2, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_DATTACK, 2, HG_VISUAL_EFFECT, 111);
set_hitbox_value(AT_DATTACK, 2, HG_HIT_SFX, asset_get("sfx_ori_energyhit_weak"));

set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DATTACK, 3, HG_WINDOW, 4);
set_hitbox_value(AT_DATTACK, 3, HG_LIFETIME, 9);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_X, -50);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_Y, -35);
set_hitbox_value(AT_DATTACK, 3, HG_WIDTH, 50);
set_hitbox_value(AT_DATTACK, 3, HG_HEIGHT, 50);
set_hitbox_value(AT_DATTACK, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_DATTACK, 3, HG_DAMAGE, 2);
set_hitbox_value(AT_DATTACK, 3, HG_ANGLE, 130);
set_hitbox_value(AT_DATTACK, 3, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DATTACK, 3, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_DATTACK, 3, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DATTACK, 3, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_DATTACK, 3, HG_VISUAL_EFFECT, 111);
set_hitbox_value(AT_DATTACK, 3, HG_HIT_SFX, asset_get("sfx_ori_energyhit_weak"));

set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DATTACK, 4, HG_WINDOW, 4);
set_hitbox_value(AT_DATTACK, 4, HG_LIFETIME, 9);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_X, -110);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_Y, -35);
set_hitbox_value(AT_DATTACK, 4, HG_WIDTH, 40);
set_hitbox_value(AT_DATTACK, 4, HG_HEIGHT, 40);
set_hitbox_value(AT_DATTACK, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_DATTACK, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_DATTACK, 4, HG_ANGLE, 130);
set_hitbox_value(AT_DATTACK, 4, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DATTACK, 4, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_DATTACK, 4, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DATTACK, 4, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_DATTACK, 4, HG_VISUAL_EFFECT, 111);
set_hitbox_value(AT_DATTACK, 4, HG_HIT_SFX, asset_get("sfx_ori_energyhit_weak"));