//Item hits

//Barrel Cannon Blast
set_hitbox_value(AT_JAB, 1, HG_WINDOW, 2);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_GROUP, 28);
set_hitbox_value(AT_JAB, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_JAB, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_JAB, 1, HG_WIDTH, 80);
set_hitbox_value(AT_JAB, 1, HG_HEIGHT, 80);
set_hitbox_value(AT_JAB, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_JAB, 1, HG_DAMAGE, 15);
set_hitbox_value(AT_JAB, 1, HG_BASE_KNOCKBACK, 8)
set_hitbox_value(AT_JAB, 1, HG_KNOCKBACK_SCALING, 0.7)
set_hitbox_value(AT_JAB, 1, HG_BASE_HITPAUSE, 8)
set_hitbox_value(AT_JAB, 1, HG_HITPAUSE_SCALING, 0.7)
set_hitbox_value(AT_JAB, 1, HG_ANGLE, 90);
//set_hitbox_value(AT_JAB, 1, HG_ANGLE_FLIPPER, 8);
set_hitbox_value(AT_JAB, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_AIR_FRICTION, 0)
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1)
set_hitbox_value(AT_JAB, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_JAB, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);

//Barrel Cannon launcher
set_hitbox_value(AT_JAB, 10, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_JAB, 10, HG_WINDOW, 9);
set_hitbox_value(AT_JAB, 10, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_JAB, 10, HG_LIFETIME, 10);
set_hitbox_value(AT_JAB, 10, HG_HITBOX_X, 0);
set_hitbox_value(AT_JAB, 10, HG_HITBOX_Y, 0);
set_hitbox_value(AT_JAB, 10, HG_WIDTH, 10);
set_hitbox_value(AT_JAB, 10, HG_HEIGHT, 10);
set_hitbox_value(AT_JAB, 10, HG_PRIORITY, 5);
set_hitbox_value(AT_JAB, 10, HG_DAMAGE, 0);
set_hitbox_value(AT_JAB, 10, HG_ANGLE, 90);
set_hitbox_value(AT_JAB, 10, HG_BASE_KNOCKBACK, 15);
set_hitbox_value(AT_JAB, 10, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_JAB, 10, HG_VISUAL_EFFECT, 196);
set_hitbox_value(AT_JAB, 10, HG_HIT_SFX, asset_get("sfx_birdflap"));
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_JAB, 10, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_JAB, 10, HG_IGNORES_PROJECTILES, 1);

//Wood Shards
set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_TAUNT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_TAUNT, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_X, -50);
set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_Y, -56);
set_hitbox_value(AT_TAUNT, 1, HG_WIDTH, 16);
set_hitbox_value(AT_TAUNT, 1, HG_HEIGHT, 16);
set_hitbox_value(AT_TAUNT, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_TAUNT, 1, HG_DAMAGE, 0);
set_hitbox_value(AT_TAUNT, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_TAUNT, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_SPRITE, sprite_get("wood"));
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_MASK, asset_get("empty_sprite"));
set_hitbox_value(AT_TAUNT, 1, HG_HIT_SFX, asset_get("blow_sfx1"));
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_ANIM_SPEED, 0.01);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_ANIM_SPEED, .15);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_HSPEED, 3);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_VSPEED, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_GRAVITY, .35);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_AIR_FRICTION, .025);