set_attack_value(AT_DSPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_DSPECIAL_2, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DSPECIAL_2, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_DSPECIAL_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_DSPECIAL_2, AG_SPRITE, sprite_get("dspecial_air"));
set_attack_value(AT_DSPECIAL_2, AG_AIR_SPRITE, sprite_get("dspecial_air"));
set_attack_value(AT_DSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("dspecial_air_hurt"));

set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_LENGTH, 14);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_SFX_FRAME, 12);
set_window_value(AT_DSPECIAL_2, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));

set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_TYPE, 10);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_LENGTH, 20);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_VSPEED, 15);
set_window_value(AT_DSPECIAL_2, 2, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_LENGTH, 32);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 12);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 14);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_DSPECIAL_2, 3, AG_WINDOW_SFX, asset_get("sfx_blow_heavy2"));

set_num_hitboxes(AT_DSPECIAL_2, 4);

set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_WINDOW, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_WINDOW_CREATION_FRAME, 13);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_X, -4);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_WIDTH, 60);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HEIGHT, 45);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_DAMAGE, 11);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_BASE_HITPAUSE, 6.5);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_DSPECIAL_2, 1, HG_ANGLE, 270);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSPECIAL_2, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_WINDOW, 2);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_LIFETIME, 999);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_X, -4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITBOX_Y, -16);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_WIDTH, 60);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HEIGHT, 45);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_KNOCKBACK, 9.5);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSPECIAL_2, 2, HG_ANGLE, 80);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSPECIAL_2, 2, HG_TECHABLE, 1);

set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_WINDOW, 87);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_LIFETIME, 7);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_X, -2);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITBOX_Y, -10);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_WIDTH, 135);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_DSPECIAL_2, 3, HG_ANGLE, 60);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSPECIAL_2, 3, HG_TECHABLE, 1);

set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_WINDOW, 87);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_LIFETIME, 25);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_X, 20);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITBOX_Y, -45);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_WIDTH, 135);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HEIGHT, 75);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PRIORITY, 5);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_DAMAGE, 10);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_ANGLE, 45);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_FINAL_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HITPAUSE_SCALING, 0.65);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_HIT_SFX, sound_get("sfx_ftilt_hit"));
set_hitbox_value(AT_DSPECIAL_2, 4, HG_VISUAL_EFFECT, 193);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_SPRITE, sprite_get("mudsplosion"));
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_ANIM_SPEED, 0.25);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DSPECIAL_2, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);