set_attack_value(AT_UAIR, AG_CATEGORY, 1);
set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 3);
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_UAIR, AG_LANDING_LAG, 4);
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));

set_window_value(AT_UAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_UAIR, 1, AG_WINDOW_CUSTOM_GRAVITY, 1.0);

set_window_value(AT_UAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED, -1);
set_window_value(AT_UAIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_weak1"));

set_window_value(AT_UAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_UAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 4);
set_window_value(AT_UAIR, 3, AG_WINDOW_CUSTOM_GRAVITY, 1.0);

set_num_hitboxes(AT_UAIR, 5);

set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, 15);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -15);
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 30);
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 65);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, .75);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 4.75);
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium3"));

set_hitbox_value(AT_UAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 5);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, 15);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -40);
set_hitbox_value(AT_UAIR, 2, HG_WIDTH, 45);
set_hitbox_value(AT_UAIR, 2, HG_HEIGHT, 35);
set_hitbox_value(AT_UAIR, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE, 89);
set_hitbox_value(AT_UAIR, 2, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_UAIR, 2, HG_KNOCKBACK_SCALING, .75);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 4.75);
set_hitbox_value(AT_UAIR, 2, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_UAIR, 2, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_UAIR, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_Y,-55);
set_hitbox_value(AT_UAIR, 3, HG_WIDTH, 30);
set_hitbox_value(AT_UAIR, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_UAIR, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 3, HG_ANGLE, 96);
set_hitbox_value(AT_UAIR, 3, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_UAIR, 3, HG_KNOCKBACK_SCALING, .75);
set_hitbox_value(AT_UAIR, 3, HG_BASE_HITPAUSE, 4.75);
set_hitbox_value(AT_UAIR, 3, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 3, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_UAIR, 3, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 4, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_UAIR, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_X, -10);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_Y,-50);
set_hitbox_value(AT_UAIR, 4, HG_WIDTH, 75);
set_hitbox_value(AT_UAIR, 4, HG_HEIGHT, 42);
set_hitbox_value(AT_UAIR, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 4, HG_ANGLE, 96);
set_hitbox_value(AT_UAIR, 4, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_UAIR, 4, HG_KNOCKBACK_SCALING, .75);
set_hitbox_value(AT_UAIR, 4, HG_BASE_HITPAUSE, 4.75);
set_hitbox_value(AT_UAIR, 4, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 4, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_UAIR, 4, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 5, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_UAIR, 5, HG_LIFETIME, 2);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_X, -28);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_Y, -30);
set_hitbox_value(AT_UAIR, 5, HG_WIDTH, 40);
set_hitbox_value(AT_UAIR, 5, HG_HEIGHT, 76);
set_hitbox_value(AT_UAIR, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_UAIR, 5, HG_DAMAGE, 6);
set_hitbox_value(AT_UAIR, 5, HG_ANGLE, 265);
set_hitbox_value(AT_UAIR, 5, HG_BASE_KNOCKBACK, 6.9); 
set_hitbox_value(AT_UAIR, 5, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(AT_UAIR, 5, HG_BASE_HITPAUSE, 4.75);
set_hitbox_value(AT_UAIR, 5, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 5, HG_VISUAL_EFFECT_Y_OFFSET, 15);
set_hitbox_value(AT_UAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_UAIR, 5, HG_ANGLE_FLIPPER, 6);