set_attack_value(AT_NAIR, AG_CATEGORY, 1);
set_attack_value(AT_NAIR, AG_SPRITE, sprite_get("nair"));
set_attack_value(AT_NAIR, AG_NUM_WINDOWS, 6);
set_attack_value(AT_NAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_NAIR, AG_LANDING_LAG, 8);
set_attack_value(AT_NAIR, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_NAIR, AG_HURTBOX_SPRITE, sprite_get("nair_hurt"));

set_window_value(AT_NAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_NAIR, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .1);
set_window_value(AT_NAIR, 1, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_SFX, sound_get("ris_lilgrab"));

set_window_value(AT_NAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_LENGTH, 5);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAME_START, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(AT_NAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_LENGTH, 20);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_NAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(AT_NAIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_LENGTH, 9);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_NAIR, 4, AG_WINDOW_VSPEED, -0.5);
set_window_value(AT_NAIR, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_NAIR, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.2);

set_window_value(AT_NAIR, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 5, AG_WINDOW_ANIM_FRAMES, 0);
set_window_value(AT_NAIR, 5, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_NAIR, 5, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_NAIR, 5, AG_WINDOW_HSPEED, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.2);

set_window_value(AT_NAIR, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 6, AG_WINDOW_LENGTH, 15);
set_window_value(AT_NAIR, 6, AG_WINDOW_ANIM_FRAMES, 0);
set_window_value(AT_NAIR, 6, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_NAIR, 6, AG_WINDOW_HSPEED, 5);
set_window_value(AT_NAIR, 6, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_NAIR, 6, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_NAIR, 6, AG_WINDOW_VSPEED, -4);
set_window_value(AT_NAIR, 6, AG_WINDOW_VSPEED_TYPE, 2);

set_num_hitboxes(AT_NAIR, 4);

set_hitbox_value(AT_NAIR, 1, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_NAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_X, 45);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NAIR, 1, HG_WIDTH, 38);
set_hitbox_value(AT_NAIR, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_NAIR, 1, HG_SHAPE, 2);
set_hitbox_value(AT_NAIR, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_NAIR, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_NAIR, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_NAIR, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NAIR, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_NAIR, 1, HG_VISUAL_EFFECT, 19);
set_hitbox_value(AT_NAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_NAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_NAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_NAIR, 1, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 1, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_NAIR, 2, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW, 4);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_NAIR, 2, HG_LIFETIME, 9);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_X, 40);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NAIR, 2, HG_WIDTH, 72);
set_hitbox_value(AT_NAIR, 2, HG_HEIGHT, 72);
set_hitbox_value(AT_NAIR, 2, HG_SHAPE, 2);
set_hitbox_value(AT_NAIR, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_NAIR, 2, HG_DAMAGE, 0);
set_hitbox_value(AT_NAIR, 2, HG_ANGLE, 130);
set_hitbox_value(AT_NAIR, 2, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_NAIR, 2, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_NAIR, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_NAIR, 2, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_NAIR, 2, HG_EFFECT, 9);
set_hitbox_value(AT_NAIR, 2, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_NAIR, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_NAIR, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 2, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 2, HG_TECHABLE, 1);

set_hitbox_value(AT_NAIR, 3, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW, 4);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_NAIR, 3, HG_LIFETIME, 9);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_X, -20);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_Y, -55);
set_hitbox_value(AT_NAIR, 3, HG_WIDTH, 2);
set_hitbox_value(AT_NAIR, 3, HG_HEIGHT, 75);
set_hitbox_value(AT_NAIR, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_NAIR, 3, HG_DAMAGE, 0);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE, 85);
set_hitbox_value(AT_NAIR, 3, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_NAIR, 3, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_NAIR, 3, HG_EXTRA_HITPAUSE, 3);
set_hitbox_value(AT_NAIR, 3, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_NAIR, 3, HG_EFFECT, 9);
set_hitbox_value(AT_NAIR, 3, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_NAIR, 3, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 3, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_NAIR, 3, HG_TECHABLE, 1);

set_hitbox_value(AT_NAIR, 4, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_NAIR, 4, HG_WINDOW, 6);
set_hitbox_value(AT_NAIR, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_NAIR, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_X, -20);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_Y, -55);
set_hitbox_value(AT_NAIR, 4, HG_WIDTH, 40);
set_hitbox_value(AT_NAIR, 4, HG_HEIGHT, 85);
set_hitbox_value(AT_NAIR, 4, HG_SHAPE, 2);
set_hitbox_value(AT_NAIR, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_NAIR, 4, HG_DAMAGE, 8);
set_hitbox_value(AT_NAIR, 4, HG_ANGLE, 42);
set_hitbox_value(AT_NAIR, 4, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_NAIR, 4, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_NAIR, 4, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_NAIR, 4, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_NAIR, 4, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_NAIR, 4, HG_HIT_SFX, asset_get("sfx_kragg_throw"));