set_attack_value(AT_NSPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_2, AG_SPRITE, sprite_get("nspecial"));
set_attack_value(AT_NSPECIAL_2, AG_NUM_WINDOWS, 1);
set_attack_value(AT_NSPECIAL_2, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_NSPECIAL_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_NSPECIAL_2, AG_AIR_SPRITE, sprite_get("nspecial"));
set_attack_value(AT_NSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("nspecial_hurt"));

set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_LENGTH, 35);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_SFX, asset_get("sfx_shovel_brandish"));

set_num_hitboxes(AT_NSPECIAL_2, 0);

/*
//set_hitbox_value(AT_NSPECIAL_2, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_LIFETIME, 900);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_X, 31);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_Y, -37);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_WIDTH, 30);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_ANGLE, 80);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_KNOCKBACK_SCALING, .35);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_SPRITE, sprite_get("rat_bombardier"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_MASK, sprite_get("rat_bombardier"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_COLLISION_SPRITE, sprite_get("rat_bombardier_mask"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_HSPEED, 3); //but when on ground should be 4
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_VSPEED, -13);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_GRAVITY, .65);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_VISUAL_EFFECT, bomb_explosion);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_DESTROY_EFFECT, bomb_explosion);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HIT_SFX, sound_get("sfx_bomb_explode"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_EXTRA_CAMERA_SHAKE, 2);

set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WINDOW, 10);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_LIFETIME, 900);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_X, 31);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_Y, -37);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WIDTH, 30);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HEIGHT, 30);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_ANGLE, 80);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_KNOCKBACK_SCALING, .35);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_SPRITE, sprite_get("rat_bombardier_bomb"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_MASK, sprite_get("rat_bombardier_mask"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_COLLISION_SPRITE, sprite_get("rat_bombardier_mask"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_HSPEED, 9); 
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_GRAVITY, 0.5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_VISUAL_EFFECT, bomb_explosion);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_DESTROY_EFFECT, bomb_explosion);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HIT_SFX, sound_get("sfx_bomb_explode"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_EXTRA_CAMERA_SHAKE, 2);

set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_LIFETIME, 6);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_WIDTH, 60);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HEIGHT, 60);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_ANGLE, 361);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_KNOCKBACK_SCALING, .35);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HIT_SFX, sound_get("sfx_bomb_explode"));
set_hitbox_value(AT_NSPECIAL_2, 3, HG_EXTRA_CAMERA_SHAKE, 2);