set_attack_value(AT_UAIR, AG_CATEGORY, 2);
set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 4);
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_UAIR, AG_AIR_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));

set_window_value(AT_UAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);
//set_window_value(AT_UAIR, 1, AG_WINDOW_HSPEED_TYPE, 1);
//set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, sound_get("whoosh"));
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 9);

set_window_value(AT_UAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 5);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAME_START, 2);
//set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED, -6);
set_window_value(AT_UAIR, 2, AG_WINDOW_HSPEED_TYPE, 1);
//set_window_value(AT_UAIR, 2, AG_WINDOW_HSPEED, 5);
set_window_value(AT_UAIR, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_UAIR, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);


set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 2);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_UAIR, 4, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_UAIR, 4, AG_WINDOW_SFX, sound_get("yell"));
set_window_value(AT_UAIR, 4, AG_WINDOW_TYPE, 7);
set_window_value(AT_UAIR, 4, AG_WINDOW_HSPEED, 3);
set_window_value(AT_UAIR, 4, AG_WINDOW_VSPEED, -12);
set_window_value(AT_UAIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 4, AG_WINDOW_LENGTH, 2);
set_window_value(AT_UAIR, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_UAIR, 4, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_UAIR, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_UAIR, 4, AG_WINDOW_ANIM_FRAME_START, 4);

set_num_hitboxes(AT_UAIR, 1);

set_hitbox_value(AT_UAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 3);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -80);
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 60);
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 56);
set_hitbox_value(AT_UAIR, 1, HG_SHAPE, 0);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 7);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 45);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 3);
//set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, .1);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 15);
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE_FLIPPER, 2);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
//set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_SPRITE, sprite_get("uair_proj"));
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, sound_get("punch"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_HSPEED, 10);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_VSPEED, -10);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_DESTROY_EFFECT, 1);