sprite_change_offset("idle", 50, 99, true);
sprite_change_offset("bighurt", 50, 99, true);
sprite_change_offset("hurt", 50, 99, true);
sprite_change_offset("hurtground", 50, 99, true);
sprite_change_offset("uphurt", 50, 99, true);
sprite_change_offset("downhurt", 50, 99, true);
sprite_change_offset("bouncehurt", 50, 99, true);
sprite_change_offset("crouch", 50, 99, true);
sprite_change_offset("walk", 50, 99, true);
sprite_change_offset("walkturn", 50, 99, true);
sprite_change_offset("dash", 50, 99, true);
sprite_change_offset("dash_alts", 50, 99, true);
sprite_change_offset("dashstart", 50, 99, true);
sprite_change_offset("dashstart_alts", 50, 99, true);
sprite_change_offset("dashstop", 50, 99, true);
sprite_change_offset("dashstop_alts", 50, 99, true);
sprite_change_offset("dashturn", 50, 95, true);

sprite_change_offset("jumpstart", 50, 99, true);
sprite_change_offset("jump", 50, 99, true);
sprite_change_offset("doublejump", 50, 99, true);
sprite_change_offset("walljump", 50, 99, true);
sprite_change_offset("pratfall", 50, 99, true);
sprite_change_offset("land", 50, 99, true);
sprite_change_offset("landinglag", 50, 99, true);

sprite_change_offset("parry", 50, 99, true);
sprite_change_offset("roll_forward", 50, 99, true);
sprite_change_offset("roll_backward", 50, 99, true);
sprite_change_offset("airdodge", 50, 99, true);
sprite_change_offset("waveland", 50, 99, true);
sprite_change_offset("tech", 50, 99, true);

sprite_change_offset("jab", 45, 99, true);
sprite_change_offset("dattack", 50, 89, true);
sprite_change_offset("dattack_ground", 50, 89, true);
sprite_change_offset("ftilt", 25, 99, true);
sprite_change_offset("dtilt", 30, 99, true);
sprite_change_offset("dtilt_alts", 30, 99, true);
sprite_change_offset("utilt", 40, 99, true);
sprite_change_offset("nair", 64, 90, true);
sprite_change_offset("fair", 64, 72, true);
sprite_change_offset("fair_alts", 64, 72, true);
sprite_change_offset("bair", 72, 99, true);
sprite_change_offset("bair_alts", 72, 99, true);
sprite_change_offset("uair", 40, 129, true);
sprite_change_offset("dair", 50, 66, true);
sprite_change_offset("fstrong", 45, 99, true);
sprite_change_offset("ustrong", 64, 109, true);
sprite_change_offset("dstrong", 64, 99, true);
sprite_change_offset("nspecial", 50, 99, true);
sprite_change_offset("nspecial_alts", 50, 99, true);
sprite_change_offset("nspecial_alts2", 50, 99, true);
sprite_change_offset("fspecial", 50, 99, true);
sprite_change_offset("uspecial", 50, 94, true);
sprite_change_offset("uspecial_alts", 50, 94, true);
sprite_change_offset("dspecial", 50, 99, true);
sprite_change_offset("taunt", 50, 99, true);

sprite_change_offset("_phone", 50, 99, true);
sprite_change_offset("plat", 64, 94);
sprite_change_offset("lookup", 50, 99, true);
sprite_change_offset("sleep", 50, 99, true);

//mechless_sprites
sprite_change_offset("idle_mechless", 50, 99, true);
sprite_change_offset("bighurt_mechless", 50, 99, true);
sprite_change_offset("hurt_mechless", 50, 99, true);
sprite_change_offset("hurtground_mechless", 50, 99, true);
sprite_change_offset("uphurt_mechless", 50, 99, true);
sprite_change_offset("downhurt_mechless", 50, 99, true);
sprite_change_offset("bouncehurt_mechless", 50, 99, true);
sprite_change_offset("crouch_mechless", 50, 99, true);
sprite_change_offset("walk_mechless", 50, 99, true);
sprite_change_offset("walkturn_mechless", 50, 99, true);
sprite_change_offset("dash_mechless", 50, 99, true);
sprite_change_offset("dashstart_mechless", 50, 99, true);
sprite_change_offset("dashstop_mechless", 50, 99, true);
sprite_change_offset("dashturn_mechless", 50, 99, true);

sprite_change_offset("jumpstart_mechless", 50, 99, true);
sprite_change_offset("jump_mechless", 50, 94, true);
sprite_change_offset("doublejump_mechless", 50, 94, true);
sprite_change_offset("walljump_mechless", 50, 94, true);
sprite_change_offset("pratfall_mechless", 50, 94, true);
sprite_change_offset("land_mechless", 50, 99, true);

sprite_change_offset("parry_mechless", 50, 99, true);
sprite_change_offset("roll_mechless", 50, 99, true);
sprite_change_offset("airdodge_mechless", 50, 94, true);
sprite_change_offset("waveland_mechless", 50, 99, true);
sprite_change_offset("tech_mechless", 50, 99, true);

sprite_change_offset("slap", 50, 93, true);
sprite_change_offset("slap_air", 50, 93, true);
sprite_change_offset("kick", 50, 93, true);
sprite_change_offset("kick_air", 50, 93, true);

sprite_change_offset("dspecial_mechless", 50, 99, true);
sprite_change_offset("dspecial_mechless_air", 50, 94, true);
sprite_change_offset("taunt_mechless", 50, 99, true);

sprite_change_offset("_phone_mechless", 50, 99, true);
sprite_change_offset("lookup_mechless", 50, 99, true);
sprite_change_offset("sleep_mechless", 50, 99, true);
sprite_change_offset("sleep_air_mechless", 50, 99, true);

sprite_change_offset("miiverse", 60, 30);
sprite_change_offset("trialgrounds", 31, 0);
sprite_change_offset("lastresort", 27, 39);
sprite_change_offset("greenflowerzone", 18, 41, true);

sprite_change_offset("eggpawn", 80, 80);
sprite_change_offset("eggpawn_alts", 80, 80);
sprite_change_offset("eggpawn_mask", 80, 80);
sprite_change_offset("eggflapper", 80, 80);
sprite_change_offset("eggflapper_alts", 80, 80);
sprite_change_offset("eggflapper_shot", 45, 29);
sprite_change_offset("eggpawn_seen", 20, 20);
sprite_change_offset("nspec_meter", 7, 18);
sprite_change_offset("nspec_laser", 70, 60);
sprite_change_offset("nspec_laser_alts", 70, 60);
sprite_change_offset("nspec_laser_alts2", 70, 60);
sprite_change_offset("nspec_laser2", 70, 60);
sprite_change_offset("nspec_laser2_alts", 70, 60);
sprite_change_offset("nspec_laser2_alts2", 70, 60);
sprite_change_offset("fspec_aim", 23, 23);
sprite_change_offset("fspec_aim_alts", 23, 23);
sprite_change_offset("fspec_projectile", 40, 40);
sprite_change_offset("fspec_projectile_alts", 40, 40);
sprite_change_offset("fspec_projectile_trail", 55, 40);
sprite_change_offset("fspec_projectile_trail2", 25, 40);
sprite_change_offset("uspecial_eggmobile", 100, 160);
sprite_change_offset("fx_sharphit", 120, 120);
sprite_change_offset("fx_sharphitbig", 120, 240);
sprite_change_offset("fx_sharphitbig2", 120, 480);
sprite_change_offset("fx_sharphit_alts", 120, 120);
sprite_change_offset("fx_sharphitbig_alts", 120, 240);
sprite_change_offset("fx_sharphitbig2_alts", 120, 480);
sprite_change_offset("fx_sharphit_alts2", 120, 120);
sprite_change_offset("fx_sharphitbig_alts2", 120, 240);
sprite_change_offset("fx_sharphitbig2_alts2", 120, 480);
sprite_change_offset("fx_lightbeams", 400, 400);
sprite_change_offset("fx_lightbeams_small", 200, 200);
sprite_change_offset("fx_lightbeams_small_alts", 200, 200);
sprite_change_offset("fx_lightbeams_small_alts2", 200, 200);
sprite_change_offset("fx_orb", 70, 70);
sprite_change_offset("fx_orb_alts", 70, 70);
sprite_change_offset("dattack_forcefield", 88, 40);
sprite_change_offset("fx_aimlaser", 400, 40);
sprite_change_offset("fx_aimlaser_alts", 400, 40);
sprite_change_offset("bury", 23, 19);
sprite_change_offset("bury_effect", 50, 58);
sprite_change_offset("dust_sharp_big", 60, 80);
sprite_change_offset("dust_sharp", 30, 40);
sprite_change_offset("fx_slam", 100, 120);
sprite_change_offset("fx_fire", 30, 30);
sprite_change_offset("fx_fire2", 40, 120);
sprite_change_offset("fx_fire2_small", 20, 60);
sprite_change_offset("fx_fire_alts", 30, 30);
sprite_change_offset("fx_fire2_alts", 40, 120);
sprite_change_offset("fx_fire2_small_alts", 20, 60);
sprite_change_offset("dust_effect", 15, 15);
sprite_change_offset("dust_effect_dark", 15, 15);
sprite_change_offset("fx_lightning", 10, 24);
sprite_change_offset("fx_pixel", 10, 28);
sprite_change_offset("fx_pixel_alts", 10, 28);
sprite_change_offset("explosion", 100, 100);
sprite_change_offset("taunt_laugh_fx", 50, 30);
sprite_change_offset("playerarrow", 7, 0);