set_attack_value(AT_NSPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL, AG_SPRITE, sprite_get("nspecial"));
set_attack_value(AT_NSPECIAL, AG_NUM_WINDOWS, 9);
set_attack_value(AT_NSPECIAL, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_NSPECIAL, AG_AIR_SPRITE, sprite_get("nspecial"));
set_attack_value(AT_NSPECIAL, AG_HURTBOX_SPRITE, sprite_get("nspecial_hurt"));

set_window_value(AT_NSPECIAL, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_NSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 3);

set_window_value(AT_NSPECIAL, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_LENGTH, 5);
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_SFX, sound_get("sweep"));
set_window_value(AT_NSPECIAL, 2, AG_WINDOW_SFX_FRAME, 4);

set_window_value(AT_NSPECIAL, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 3, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 4, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 4, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 4, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 5, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 5, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 5, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 6, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 6, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 6, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 7, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 7, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 7, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 7, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 8, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 8, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 8, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_NSPECIAL, 8, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_NSPECIAL, 9, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL, 9, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL, 9, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_NSPECIAL, 9, AG_WINDOW_ANIM_FRAME_START, 10);

set_num_hitboxes(AT_NSPECIAL, 10);

set_hitbox_value(AT_NSPECIAL, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL, 1, HG_WINDOW, 8);
set_hitbox_value(AT_NSPECIAL, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_NSPECIAL, 1, HG_HITBOX_X, 26);
set_hitbox_value(AT_NSPECIAL, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NSPECIAL, 1, HG_WIDTH, 22);
set_hitbox_value(AT_NSPECIAL, 1, HG_HEIGHT, 45);
set_hitbox_value(AT_NSPECIAL, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL, 1, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL, 1, HG_ANGLE, 40);
set_hitbox_value(AT_NSPECIAL, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL, 1, HG_KNOCKBACK_SCALING, 0.40);
set_hitbox_value(AT_NSPECIAL, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL, 1, HG_HITPAUSE_SCALING, 0.30);
set_hitbox_value(AT_NSPECIAL, 1, HG_HIT_SFX, sound_get("hit_punch"));
set_hitbox_value(AT_NSPECIAL, 1, HG_WINDOW_CREATION_FRAME, 6);

set_hitbox_value(AT_NSPECIAL, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL, 2, HG_WINDOW, 8);
set_hitbox_value(AT_NSPECIAL, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL, 2, HG_HITBOX_X, 68);
set_hitbox_value(AT_NSPECIAL, 2, HG_HITBOX_Y, -46);
set_hitbox_value(AT_NSPECIAL, 2, HG_WIDTH, 42);
set_hitbox_value(AT_NSPECIAL, 2, HG_HEIGHT, 39);
set_hitbox_value(AT_NSPECIAL, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL, 2, HG_ANGLE, 50);
set_hitbox_value(AT_NSPECIAL, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL, 2, HG_KNOCKBACK_SCALING, 0.40);
set_hitbox_value(AT_NSPECIAL, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL, 2, HG_HITPAUSE_SCALING, 0.30);
set_hitbox_value(AT_NSPECIAL, 2, HG_HIT_SFX, sound_get("hit_punch"));
set_hitbox_value(AT_NSPECIAL, 2, HG_WINDOW_CREATION_FRAME, 8);

set_hitbox_value(AT_NSPECIAL, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL, 3, HG_WINDOW, 8);
set_hitbox_value(AT_NSPECIAL, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL, 3, HG_HITBOX_X, 53);
set_hitbox_value(AT_NSPECIAL, 3, HG_HITBOX_Y, -19);
set_hitbox_value(AT_NSPECIAL, 3, HG_WIDTH, 30);
set_hitbox_value(AT_NSPECIAL, 3, HG_HEIGHT, 26);
set_hitbox_value(AT_NSPECIAL, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL, 3, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL, 3, HG_ANGLE, 50);
set_hitbox_value(AT_NSPECIAL, 3, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL, 3, HG_KNOCKBACK_SCALING, 0.40);
set_hitbox_value(AT_NSPECIAL, 3, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL, 3, HG_HITPAUSE_SCALING, 0.30);
set_hitbox_value(AT_NSPECIAL, 3, HG_HIT_SFX, sound_get("hit_punch"));
set_hitbox_value(AT_NSPECIAL, 3, HG_WINDOW_CREATION_FRAME, 8);

set_hitbox_value(AT_NSPECIAL, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL, 4, HG_WINDOW, 8);
set_hitbox_value(AT_NSPECIAL, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_NSPECIAL, 4, HG_HITBOX_X, 71);
set_hitbox_value(AT_NSPECIAL, 4, HG_HITBOX_Y, -69);
set_hitbox_value(AT_NSPECIAL, 4, HG_WIDTH, 50);
set_hitbox_value(AT_NSPECIAL, 4, HG_HEIGHT, 110);
set_hitbox_value(AT_NSPECIAL, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL, 4, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL, 4, HG_ANGLE, 70);
set_hitbox_value(AT_NSPECIAL, 4, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL, 4, HG_KNOCKBACK_SCALING, 0.40);
set_hitbox_value(AT_NSPECIAL, 4, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL, 4, HG_HITPAUSE_SCALING, 0.30);
set_hitbox_value(AT_NSPECIAL, 4, HG_HIT_SFX, sound_get("hit_punch"));
set_hitbox_value(AT_NSPECIAL, 4, HG_WINDOW_CREATION_FRAME, 11);

set_hitbox_value(AT_NSPECIAL, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 5, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL, 5, HG_LIFETIME, 25);
set_hitbox_value(AT_NSPECIAL, 5, HG_HITBOX_X, 70);
set_hitbox_value(AT_NSPECIAL, 5, HG_HITBOX_Y, -0);
set_hitbox_value(AT_NSPECIAL, 5, HG_WIDTH, 90);
set_hitbox_value(AT_NSPECIAL, 5, HG_HEIGHT, 60);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_SPRITE, sprite_get("poof"));
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_ANIM_SPEED, .15);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_NSPECIAL, 5, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL, 5, HG_WINDOW_CREATION_FRAME, 4);

set_hitbox_value(AT_NSPECIAL, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 6, HG_WINDOW, 3);
set_hitbox_value(AT_NSPECIAL, 6, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL, 6, HG_LIFETIME, 100);
set_hitbox_value(AT_NSPECIAL, 6, HG_HITBOX_X, 40);
set_hitbox_value(AT_NSPECIAL, 6, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NSPECIAL, 6, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL, 6, HG_WIDTH, 32);
set_hitbox_value(AT_NSPECIAL, 6, HG_HEIGHT, 32);
set_hitbox_value(AT_NSPECIAL, 6, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL, 6, HG_DAMAGE, 6);
set_hitbox_value(AT_NSPECIAL, 6, HG_ANGLE, 90);
set_hitbox_value(AT_NSPECIAL, 6, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_NSPECIAL, 6, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL, 6, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_NSPECIAL, 6, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_NSPECIAL, 6, HG_HIT_SFX, sound_get("hit_punch2"));
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_DESTROY_EFFECT, itembreakpot );
set_hitbox_value(AT_NSPECIAL, 6, HG_VISUAL_EFFECT, itembreakpot);

set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_SPRITE, sprite_get("itempot"));
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_ANIM_SPEED, 0.15);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_VSPEED, -9);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_GRAVITY, 0.4);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_AIR_FRICTION, 0.030);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_NSPECIAL, 6, HG_PROJECTILE_IS_TRANSCENDENT, 0);

set_hitbox_value(AT_NSPECIAL, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 7, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL, 7, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL, 7, HG_LIFETIME, 100);
set_hitbox_value(AT_NSPECIAL, 7, HG_HITBOX_X, 40);
set_hitbox_value(AT_NSPECIAL, 7, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NSPECIAL, 7, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL, 7, HG_WIDTH, 32);
set_hitbox_value(AT_NSPECIAL, 7, HG_HEIGHT, 32);
set_hitbox_value(AT_NSPECIAL, 7, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL, 7, HG_DAMAGE, 4);
set_hitbox_value(AT_NSPECIAL, 7, HG_ANGLE, 150);
set_hitbox_value(AT_NSPECIAL, 7, HG_EFFECT, 3);
set_hitbox_value(AT_NSPECIAL, 7, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NSPECIAL, 7, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_NSPECIAL, 7, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_NSPECIAL, 7, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_NSPECIAL, 7, HG_HIT_SFX, sound_get("hit_punch2"));
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_DESTROY_EFFECT, itembreaklamp );
set_hitbox_value(AT_NSPECIAL, 7, HG_VISUAL_EFFECT, itembreaklamp);

set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_SPRITE, sprite_get("itemlamp"));
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_ANIM_SPEED, 0.15);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_VSPEED, -11);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_GRAVITY, 0.36);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_AIR_FRICTION, 0.020);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_NSPECIAL, 7, HG_PROJECTILE_IS_TRANSCENDENT, 0);

set_hitbox_value(AT_NSPECIAL, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 8, HG_WINDOW, 5);
set_hitbox_value(AT_NSPECIAL, 8, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL, 8, HG_LIFETIME, 100);
set_hitbox_value(AT_NSPECIAL, 8, HG_HITBOX_X, 40);
set_hitbox_value(AT_NSPECIAL, 8, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NSPECIAL, 8, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL, 8, HG_WIDTH, 42);
set_hitbox_value(AT_NSPECIAL, 8, HG_HEIGHT, 42);
set_hitbox_value(AT_NSPECIAL, 8, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL, 8, HG_DAMAGE, 9);
set_hitbox_value(AT_NSPECIAL, 8, HG_ANGLE, 50);
set_hitbox_value(AT_NSPECIAL, 8, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NSPECIAL, 8, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_NSPECIAL, 8, HG_KNOCKBACK_SCALING, 0.3);
set_hitbox_value(AT_NSPECIAL, 8, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_NSPECIAL, 8, HG_HIT_SFX, sound_get("hit_punch2"));
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_DESTROY_EFFECT, itembreakrock );
set_hitbox_value(AT_NSPECIAL, 8, HG_VISUAL_EFFECT, itembreakrock);

set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_SPRITE, sprite_get("itemrock"));
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_ANIM_SPEED, 0.15);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_VSPEED, -11);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_GRAVITY, 0.65);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_AIR_FRICTION, 0.0454);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_NSPECIAL, 8, HG_PROJECTILE_IS_TRANSCENDENT, 1);

set_hitbox_value(AT_NSPECIAL, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 9, HG_WINDOW, 6);
set_hitbox_value(AT_NSPECIAL, 9, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL, 9, HG_LIFETIME, 100);
set_hitbox_value(AT_NSPECIAL, 9, HG_HITBOX_X, 40);
set_hitbox_value(AT_NSPECIAL, 9, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NSPECIAL, 9, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL, 9, HG_WIDTH, 42);
set_hitbox_value(AT_NSPECIAL, 9, HG_HEIGHT, 42);
set_hitbox_value(AT_NSPECIAL, 9, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL, 9, HG_DAMAGE, 7);
set_hitbox_value(AT_NSPECIAL, 9, HG_ANGLE, 310);
set_hitbox_value(AT_NSPECIAL, 9, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_NSPECIAL, 9, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_NSPECIAL, 9, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NSPECIAL, 9, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_NSPECIAL, 9, HG_HIT_SFX, sound_get("hit_punch2"));
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_DESTROY_EFFECT, itembreakplatter );
set_hitbox_value(AT_NSPECIAL, 9, HG_VISUAL_EFFECT, itembreakplatter);
set_hitbox_value(AT_NSPECIAL, 9, HG_ANGLE_FLIPPER, 9);

set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_SPRITE, sprite_get("itemplatter"));
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_ANIM_SPEED, 0.15);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_HSPEED, 7);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_VSPEED, -8);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_GRAVITY, 0.45);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_AIR_FRICTION, 0.0454);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_NSPECIAL, 9, HG_PROJECTILE_IS_TRANSCENDENT, 0);

set_hitbox_value(AT_NSPECIAL, 10, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL, 10, HG_WINDOW, 7);
set_hitbox_value(AT_NSPECIAL, 10, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL, 10, HG_LIFETIME, 100);
set_hitbox_value(AT_NSPECIAL, 10, HG_HITBOX_X, 40);
set_hitbox_value(AT_NSPECIAL, 10, HG_HITBOX_Y, -35);
set_hitbox_value(AT_NSPECIAL, 10, HG_SHAPE, 0);
set_hitbox_value(AT_NSPECIAL, 10, HG_WIDTH, 24);
set_hitbox_value(AT_NSPECIAL, 10, HG_HEIGHT, 24);
set_hitbox_value(AT_NSPECIAL, 10, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL, 10, HG_DAMAGE, 2);
set_hitbox_value(AT_NSPECIAL, 10, HG_ANGLE, 270);
set_hitbox_value(AT_NSPECIAL, 10, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_NSPECIAL, 10, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_NSPECIAL, 10, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_NSPECIAL, 10, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_NSPECIAL, 10, HG_HIT_SFX, sound_get("hit_punch2"));
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_DESTROY_EFFECT, itembreakicup );
set_hitbox_value(AT_NSPECIAL, 10, HG_VISUAL_EFFECT, itembreakicup);

set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_SPRITE, sprite_get("itemicup"));
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_ANIM_SPEED, 0.10);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_VSPEED, -11);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_GRAVITY, 0.35);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_AIR_FRICTION, 0.01696969);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_NSPECIAL, 10, HG_PROJECTILE_IS_TRANSCENDENT, 0);