set_attack_value(AT_NSPECIAL_AIR, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_AIR, AG_SPRITE, sprite_get("nspecial_air"));
set_attack_value(AT_NSPECIAL_AIR, AG_NUM_WINDOWS, 4);
set_attack_value(AT_NSPECIAL_AIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_NSPECIAL_AIR, AG_OFF_LEDGE, 1);
set_attack_value(AT_NSPECIAL_AIR, AG_HURTBOX_SPRITE, sprite_get("nspecial_air_hurt"));

//startup
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_LENGTH, 5);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_NSPECIAL_AIR, 1, AG_WINDOW_VSPEED_TYPE, 1);

//weak punch
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_SFX, asset_get("sfx_burnapplied"));
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.3);
set_window_value(AT_NSPECIAL_AIR, 2, AG_WINDOW_ANIM_FRAME_START, 1);

//medium punch
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_LENGTH, 20);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_SFX, asset_get("sfx_forsburn_combust"));
set_window_value(AT_NSPECIAL_AIR, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.3);

//strong uppercut
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_LENGTH, 26);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_ANIM_FRAME_START, 17);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_SFX, sound_get("sfx_uppercut"));
set_window_value(AT_NSPECIAL_AIR, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.3);

set_num_hitboxes(AT_NSPECIAL_AIR, 6);

set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HITBOX_X, 30);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_WIDTH, 45);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HEIGHT, 55);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HIT_SFX, asset_get("sfx_blow_weak1"));
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_ANGLE, 75);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 1, HG_HITPAUSE_SCALING, 0.2);

set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_WINDOW, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HITBOX_X, 30);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_WIDTH, 45);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HEIGHT, 55);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HIT_SFX, asset_get("sfx_blow_weak1"));
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_ANGLE, 85);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 2, HG_HITPAUSE_SCALING, 0);

set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_WINDOW, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HITBOX_X, 30);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HITBOX_Y, -50);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_WIDTH, 50);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HEIGHT, 65);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_ANGLE, 75);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_NSPECIAL_AIR, 3, HG_HITPAUSE_SCALING, 0.4);

set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HITBOX_X, 30);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HITBOX_Y, -15);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_WIDTH, 45);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HEIGHT, 60);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HIT_SFX, asset_get("sfx_blow_weak1"));
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_ANGLE, 85);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 4, HG_HITPAUSE_SCALING, 0);

set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_WINDOW_CREATION_FRAME, 7);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITBOX_X, 30);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITBOX_Y, -45);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_WIDTH, 55);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HEIGHT, 75);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_DAMAGE, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_ANGLE, 85);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 5, HG_HITPAUSE_SCALING, 0);

set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_PARENT_HITBOX, 6);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_WINDOW, 4);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_LIFETIME, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HITBOX_X, 20);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HITBOX_Y, -60);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_WIDTH, 70);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_WINDOW_CREATION_FRAME, 10);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HEIGHT, 65);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_PRIORITY, 3);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_DAMAGE, 6);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_ANGLE, 80);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_KNOCKBACK_SCALING, .95);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_NSPECIAL_AIR, 6, HG_HITPAUSE_SCALING, 0.8);