set_attack_value(49, AG_CATEGORY, 2);
set_attack_value(49, AG_SPRITE, sprite_get("finalsmesh"));
set_attack_value(49, AG_AIR_SPRITE, sprite_get("finalsmesh_air"));
set_attack_value(49, AG_NUM_WINDOWS, 5);
set_attack_value(49, AG_HAS_LANDING_LAG, 3);
set_attack_value(49, AG_HURTBOX_SPRITE, sprite_get("finalsmesh"));
set_attack_value(49, AG_OFF_LEDGE, 1);

set_window_value(49, 1, AG_WINDOW_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_LENGTH, 10);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(49, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 1, AG_WINDOW_SFX, sound_get("infinity_circle"));
set_window_value(49, 1, AG_WINDOW_SFX_FRAME, 1);
set_window_value(49, 1, AG_WINDOW_INVINCIBILITY, 1);

set_window_value(49, 2, AG_WINDOW_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_LENGTH, 50);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 9);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(49, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 2, AG_WINDOW_SFX, asset_get("sfx_bird_screech"));
set_window_value(49, 2, AG_WINDOW_SFX_FRAME, 20);
set_window_value(49, 2, AG_WINDOW_INVINCIBILITY, 1);

set_window_value(49, 3, AG_WINDOW_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_LENGTH, 10);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 11);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(49, 3, AG_WINDOW_HSPEED, 40);
set_window_value(49, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 3, AG_WINDOW_SFX, asset_get("sfx_bird_upspecial"));
set_window_value(49, 3, AG_WINDOW_INVINCIBILITY, 1);

set_window_value(49, 4, AG_WINDOW_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_LENGTH, 32);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 23);
set_window_value(49, 4, AG_WINDOW_HSPEED, 0);
set_window_value(49, 4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_INVINCIBILITY, 1);

set_window_value(49, 5, AG_WINDOW_TYPE, 1);
set_window_value(49, 5, AG_WINDOW_LENGTH, 3);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAME_START, 31);
set_window_value(49, 5, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(49, 5, AG_WINDOW_INVINCIBILITY, 1);

set_num_hitboxes(49,2);

set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(49, 1, HG_WINDOW, 3);
set_hitbox_value(49, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(49, 1, HG_LIFETIME, 12);
set_hitbox_value(49, 1, HG_HITBOX_X, 0);
set_hitbox_value(49, 1, HG_HITBOX_Y, -35);
set_hitbox_value(49, 1, HG_WIDTH, 100);
set_hitbox_value(49, 1, HG_HEIGHT, 110);
set_hitbox_value(49, 1, HG_SHAPE, 0);
set_hitbox_value(49, 1, HG_PRIORITY, 10);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(49, 1, HG_DAMAGE, 35);
set_hitbox_value(49, 1, HG_ANGLE, 70);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 1, HG_KNOCKBACK_SCALING, 1.75);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(49, 1, HG_EXTRA_HITPAUSE, 16);
set_hitbox_value(49, 1, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(49, 1, HG_HIT_SFX, asset_get("sfx_ori_energyhit_heavy"));
set_hitbox_value(49, 1, HG_ANGLE_FLIPPER, 0);

set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(49, 2, HG_WINDOW, 2);
set_hitbox_value(49, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(49, 2, HG_LIFETIME, 30);
set_hitbox_value(49, 2, HG_HITBOX_X, 225);
set_hitbox_value(49, 2, HG_HITBOX_Y, -35);
set_hitbox_value(49, 2, HG_WIDTH, 450);
set_hitbox_value(49, 2, HG_HEIGHT, 110);
set_hitbox_value(49, 2, HG_SHAPE, 0);
set_hitbox_value(49, 2, HG_PRIORITY, 10);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(49, 2, HG_DAMAGE, 0);
set_hitbox_value(49, 2, HG_ANGLE, 90);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 2, HG_EXTRA_HITPAUSE, 60);
set_hitbox_value(49, 2, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(49, 2, HG_ANGLE_FLIPPER, 0);