set_attack_value(AT_DTILT, AG_CATEGORY, 0);
set_attack_value(AT_DTILT, AG_SPRITE, sprite_get("dtilt"));
set_attack_value(AT_DTILT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DTILT, AG_HURTBOX_SPRITE, sprite_get("dtilt_hurt"));

set_window_value(AT_DTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_LENGTH, 9);
set_window_value(AT_DTILT, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX_FRAME, 8);

set_window_value(AT_DTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 2, AG_WINDOW_LENGTH, 9);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAME_START, 3);

set_window_value(AT_DTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_DTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_DTILT, 4);

set_hitbox_value(AT_DTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_X, 30);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_DTILT, 1, HG_WIDTH, 50);
set_hitbox_value(AT_DTILT, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_DTILT, 1, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 1, HG_PRIORITY, 5);
set_hitbox_value(AT_DTILT, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_DTILT, 1, HG_ANGLE, 361);
set_hitbox_value(AT_DTILT, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_DTILT, 1, HG_KNOCKBACK_SCALING, .95);
set_hitbox_value(AT_DTILT, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DTILT, 1, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_DTILT, 1, HG_HIT_SFX,asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT, 304);

set_hitbox_value(AT_DTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 2, HG_WINDOW, 20);
set_hitbox_value(AT_DTILT, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_X, 60);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_DTILT, 2, HG_WIDTH, 70);
set_hitbox_value(AT_DTILT, 2, HG_HEIGHT, 60);
set_hitbox_value(AT_DTILT, 2, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_DTILT, 2, HG_DAMAGE, 7);
set_hitbox_value(AT_DTILT, 2, HG_ANGLE, 45);
set_hitbox_value(AT_DTILT, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DTILT, 2, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_DTILT, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DTILT, 2, HG_HITPAUSE_SCALING, .75);
set_hitbox_value(AT_DTILT, 2, HG_HIT_SFX, asset_get("sfx_waterhit_heavy2"));
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT, 302);

set_hitbox_value(AT_DTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 3, HG_WINDOW, 20);
set_hitbox_value(AT_DTILT, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_DTILT, 3, HG_HITBOX_X, 90);
set_hitbox_value(AT_DTILT, 3, HG_HITBOX_Y, -15);
set_hitbox_value(AT_DTILT, 3, HG_WIDTH, 50);
set_hitbox_value(AT_DTILT, 3, HG_HEIGHT, 40);
set_hitbox_value(AT_DTILT, 3, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_DTILT, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_DTILT, 3, HG_ANGLE, 45);
set_hitbox_value(AT_DTILT, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DTILT, 3, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_DTILT, 3, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DTILT, 3, HG_HITPAUSE_SCALING, .55);
set_hitbox_value(AT_DTILT, 3, HG_HIT_SFX, asset_get("sfx_waterhit_heavy2"));
set_hitbox_value(AT_DTILT, 3, HG_VISUAL_EFFECT, 302);

set_hitbox_value(AT_DTILT, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 4, HG_WINDOW, 20);
set_hitbox_value(AT_DTILT, 4, HG_LIFETIME, 600);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_X, 50);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_Y, -15);
set_hitbox_value(AT_DTILT, 4, HG_WIDTH, 40);
set_hitbox_value(AT_DTILT, 4, HG_HEIGHT, 40);
set_hitbox_value(AT_DTILT, 4, HG_PRIORITY, 4);
set_hitbox_value(AT_DTILT, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_DTILT, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DTILT, 4, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_DTILT, 4, HG_ANGLE, 45);
set_hitbox_value(AT_DTILT, 4, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DTILT, 4, HG_HITPAUSE_SCALING, .80);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_SPRITE, sprite_get("mudprojectile"));
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 4, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_GRAVITY, 0.3);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_HSPEED, 8);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_VSPEED, -4);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
//set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
//set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_DTILT, 4, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_DTILT, 4, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_DESTROY_EFFECT, fx_mudsplash);