
set_attack_value(AT_EXTRA_1, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("intro"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 2);
set_attack_value(AT_EXTRA_1, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_EXTRA_1, AG_AIR_SPRITE, sprite_get("intro"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("empty"));

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, floor(90/22*18));
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 18);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX, asset_get("sfx_spin"))



set_window_value(AT_EXTRA_1, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, (119 - floor(90/22*18)));
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAME_START, 18);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX, asset_get("sfx_spin"))


set_num_hitboxes(AT_EXTRA_1, 4);

set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 150);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -56);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_SPRITE, sprite_get("greended"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_HSPEED, -4);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITSTUN_MULTIPLIER, 0.9);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_LOCKOUT, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_GRAVITY, 0.4);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 150);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -56);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_SPRITE, sprite_get("greended"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_HSPEED, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITSTUN_MULTIPLIER, 0.9);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_LOCKOUT, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_GRAVITY, 0.3);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 150);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -56);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_SPRITE, sprite_get("greended"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_HSPEED, -2);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_VSPEED, -8);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_1, 3, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 3, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITSTUN_MULTIPLIER, 0.9);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_LOCKOUT, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_GRAVITY, 0.3);

set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_LIFETIME, 150);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_Y, -56);
set_hitbox_value(AT_EXTRA_1, 4, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_SPRITE, sprite_get("greended"));
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_HSPEED, 4);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_VSPEED, -9);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_DESTROY_EFFECT, 302);
set_hitbox_value(AT_EXTRA_1, 4, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 4, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITPAUSE_SCALING, 0.3);
set_hitbox_value(AT_EXTRA_1, 4, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITSTUN_MULTIPLIER, 0.9);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_HIT_LOCKOUT, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_GRAVITY, 0.3);


set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 5, HG_LIFETIME, 600);
set_hitbox_value(AT_EXTRA_1, 5, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_SPRITE, sprite_get("tbfx"));
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 6, HG_LIFETIME, 600);
set_hitbox_value(AT_EXTRA_1, 6, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_SPRITE, sprite_get("tbfx"));
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 7, HG_LIFETIME, 600);
set_hitbox_value(AT_EXTRA_1, 7, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_SPRITE, sprite_get("tbfx"));
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 8, HG_LIFETIME, 600);
set_hitbox_value(AT_EXTRA_1, 8, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_SPRITE, sprite_get("tbfx"));
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 8, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_WINDOW, 99);
set_hitbox_value(AT_EXTRA_1, 9, HG_LIFETIME, 600);
set_hitbox_value(AT_EXTRA_1, 9, HG_PRIORITY, 0);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_SPRITE, sprite_get("tbfx"));
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_EXTRA_1, 9, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_UNBASHABLE, 1);