set_attack_value(AT_EXTRA_1, AG_CATEGORY, 0);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 3);

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_TYPE, 0);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAME_START, 0);

set_window_value(AT_EXTRA_1, 2, AG_WINDOW_TYPE, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 1);

set_window_value(AT_EXTRA_1, 3, AG_WINDOW_TYPE, 0);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAMES, 1);

set_num_hitboxes(AT_EXTRA_1,0);

set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 300);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 4, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 4, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 5, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 5, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_1, 6, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 6, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 6, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 6, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 6, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 6, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 7, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_DAMAGE, 3);
set_hitbox_value(AT_EXTRA_1, 7, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 7, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 7, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 7, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 7, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 7, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_LIFETIME, 120);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 8, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 8, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_MASK, sprite_get("evidence1"))
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_VISUAL_EFFECT_Y_OFFSET, 32);
set_hitbox_value(AT_EXTRA_1, 8, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 8, HG_ANGLE_FLIPPER, 3);

set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_LIFETIME, 10);
set_hitbox_value(AT_EXTRA_1, 9, HG_HEIGHT, 120);
set_hitbox_value(AT_EXTRA_1, 9, HG_WIDTH, 120);
set_hitbox_value(AT_EXTRA_1, 9, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_DAMAGE, 12);
set_hitbox_value(AT_EXTRA_1, 9, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 9, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_EXTRA_1, 9, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_EXTRA_1, 9, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_EXTRA_1, 9, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 9, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_VISUAL_EFFECT_Y_OFFSET, 35);
set_hitbox_value(AT_EXTRA_1, 9, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 9, HG_ANGLE_FLIPPER, 3);