set_attack_value(AT_FSPECIAL_1, AG_CATEGORY, 2);
set_attack_value(AT_FSPECIAL_1, AG_SPRITE, sprite_get("fspecial_1"));
set_attack_value(AT_FSPECIAL_1, AG_NUM_WINDOWS, 5);
set_attack_value(AT_FSPECIAL_1, AG_HURTBOX_SPRITE, sprite_get("fspecial_1_hurt"));
set_attack_value(AT_FSPECIAL_1, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_FSPECIAL_1, AG_OFF_LEDGE, 0);

set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_LENGTH, 16);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_SFX, sound_get("onslaught"));
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_SFX_FRAME, 7);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 1, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_LENGTH, 15);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_HSPEED, 19.5); //was 22
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);
set_window_value(AT_FSPECIAL_1, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, 1);

set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_LENGTH, 14);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.5);
set_window_value(AT_FSPECIAL_1, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.5);

set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_CUSTOM_GRAVITY, 0.35);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.5);
set_window_value(AT_FSPECIAL_1, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.5);

set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_LENGTH, 3);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_CUSTOM_GRAVITY, 0.35);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.5);
set_window_value(AT_FSPECIAL_1, 5, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.5);

//side kick
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_ANIM_FRAME_START, 10);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 6, AG_WINDOW_HSPEED_TYPE, 1);
//punches
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_LENGTH, 3);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 7, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_LENGTH, 3);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_ANIM_FRAME_START, 14);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 8, AG_WINDOW_HSPEED_TYPE, 2);
//kicks
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_ANIM_FRAME_START, 16);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_SFX_FRAME, 0);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 9, AG_WINDOW_HSPEED_TYPE, 2);
//dunk
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_ANIM_FRAME_START, 18);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_SFX_FRAME, 2);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 10, AG_WINDOW_HSPEED_TYPE, 2);
//finisher
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_ANIM_FRAME_START, 21);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_SFX_FRAME, 2);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_HSPEED, 0);
set_window_value(AT_FSPECIAL_1, 11, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_LENGTH, 20);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_ANIM_FRAME_START, 24);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_CUSTOM_GRAVITY, 0.65);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_SFX_FRAME, 3);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_VSPEED, -6);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_HSPEED, 2);
set_window_value(AT_FSPECIAL_1, 12, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FSPECIAL_1, 13, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL_1, 13, AG_WINDOW_LENGTH, 15);
set_window_value(AT_FSPECIAL_1, 13, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL_1, 13, AG_WINDOW_ANIM_FRAME_START, 29);
set_window_value(AT_FSPECIAL_1, 13, AG_WINDOW_CUSTOM_GRAVITY, 0.65);

set_num_hitboxes(AT_FSPECIAL_1, 8);

set_hitbox_value(AT_FSPECIAL_1, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_LIFETIME, 15);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HITBOX_X, 29);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HITBOX_Y, -29);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_WIDTH, 29);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HEIGHT, 55);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_ANGLE, 85);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HITSTUN_MULTIPLIER, 1.3);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_FSPECIAL_1, 2, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_WINDOW, 6);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_LIFETIME, 1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HITBOX_X, 43);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_WIDTH, 85);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HEIGHT, 85);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_ANGLE, 69);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FSPECIAL_1, 2, HG_HITSTUN_MULTIPLIER, 1.3);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_TECHABLE, 1);
set_hitbox_value(AT_FSPECIAL_1, 2, HG_SDI_MULTIPLIER, 0);

set_hitbox_value(AT_FSPECIAL_1, 3, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_WINDOW, 7);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_LIFETIME, 1);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_HITBOX_X, 43);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 3, HG_HIT_SFX, asset_get("sfx_blow_weak2"));

set_hitbox_value(AT_FSPECIAL_1, 4, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_WINDOW, 8);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_LIFETIME, 1);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_HITBOX_X, 43);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 4, HG_HIT_SFX, asset_get("sfx_blow_weak1"));

set_hitbox_value(AT_FSPECIAL_1, 5, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_WINDOW, 9);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_LIFETIME, 1);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_HITBOX_X, 43);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 5, HG_HIT_SFX, asset_get("sfx_blow_medium1"));

set_hitbox_value(AT_FSPECIAL_1, 6, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_WINDOW, 10);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_LIFETIME, 1);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_HITBOX_X, 43);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_HITBOX_Y, -43);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 6, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
//dunk
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_WINDOW, 11);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HITBOX_X, 41);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HITBOX_Y, -42);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_WIDTH, 75);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HEIGHT, 96);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_DAMAGE, 2);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_ANGLE, 265);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_BASE_KNOCKBACK, 6.5);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_FSPECIAL_1, 7, HG_TECHABLE, 1);

set_hitbox_value(AT_FSPECIAL_1, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_WINDOW, 12);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_LIFETIME, 4);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_HITBOX_X, 18);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_HITBOX_Y, -53);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_WIDTH, 104);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_HEIGHT, 104);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_ANGLE, 80);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_KNOCKBACK_SCALING, 1.20);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSPECIAL_1, 8, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));
set_hitbox_value(AT_FSPECIAL_1, 8, HG_DRIFT_MULTIPLIER, 1.0);