//POD STATES
PD_INIT = 0;
PD_IDLE = 1;
PD_GLIDE = 2;
PD_ATTACK = 3;
PD_RETURN = 4;
PD_RESPAWN = 5;
PD_DIE = 6;

//POD ATTACKS
PA_NSPECIAL = 0;
PA_FSPECIAL = 1;
PA_USPECIAL = 2;
PA_DSPECIAL = 3;
PA_NSPECIAL_AT = 4;
PA_DSPECIAL_CR = 5;
PA_USTRONG = 6;
PA_TAUNT = 7;