sprite_change_offset("idle", 64, 79);
sprite_change_offset("1_idlehbox", 64, 94);
sprite_change_offset("2_crouchhbox", 64, 94);

sprite_change_offset("hurt", 64, 79);
sprite_change_offset("hurtground", 64, 79);
sprite_change_offset("bighurt", 64, 79);
sprite_change_offset("uphurt", 64, 79);
sprite_change_offset("downhurt", 64, 79);
sprite_change_offset("bouncehurt", 64, 79);
sprite_change_offset("spinhurt", 64, 79);
sprite_change_offset("crouch", 64, 79);
sprite_change_offset("crawl", 64, 79);
sprite_change_offset("walk", 64, 79);
sprite_change_offset("walkturn", 64, 79);
sprite_change_offset("dash", 64, 79);
sprite_change_offset("dashstart", 64, 79);
sprite_change_offset("dashstop", 64, 79);
sprite_change_offset("dashturn", 64, 79);

sprite_change_offset("jumpstart", 64, 79);
sprite_change_offset("jump", 64, 79);
sprite_change_offset("doublejump", 64, 79);
sprite_change_offset("walljump", 64, 79);
sprite_change_offset("pratfall", 64, 79);
sprite_change_offset("land", 64, 79);
sprite_change_offset("landinglag", 64, 79);

sprite_change_offset("parry", 64, 79);
sprite_change_offset("parry_dooropen", 64*2, 79*2);
sprite_change_offset("parry_doorclose", 64, 79);
sprite_change_offset("roll_forward", 64, 79);
sprite_change_offset("roll_backward", 64, 79);
sprite_change_offset("airdodge", 64, 79);
sprite_change_offset("waveland", 64, 79);
sprite_change_offset("tech", 64, 79);

sprite_change_offset("jab", 64, 79, true);
sprite_change_offset("dattack", 64, 79, true);
sprite_change_offset("ftilt", 64, 79, true);
sprite_change_offset("dtilt", 64, 79, true);
sprite_change_offset("utilt", 64, 79, true);
sprite_change_offset("nair", 64, 79, true);
sprite_change_offset("fair_yield", 64, 79, true);
sprite_change_offset("fair_stop", 64, 79, true);
sprite_change_offset("fair_shovel", 64, 79, true);
sprite_change_offset("fair_hurt", 64*2, 79*2, true);
sprite_change_offset("bair", 64, 79, true);
sprite_change_offset("bair_shot_linger", 64*2, 79*2);
sprite_change_offset("bair_smoke_linger", 64*2, 79*2);
sprite_change_offset("bair_shotty", 26, 11);
sprite_change_offset("uair_shovel", 64, 79, true);
sprite_change_offset("uair_stop", 64, 79, true);
sprite_change_offset("uair_yield", 64, 79, true);
sprite_change_offset("uair_hurt", 64*2, 79*2, true);
sprite_change_offset("dair", 64, 79, true);
sprite_change_offset("fstrong_shovel", 64, 79, true);
sprite_change_offset("fstrong_stop", 64, 79, true);
sprite_change_offset("fstrong_yield", 64, 79, true);
sprite_change_offset("fstrong_hurt", 64*2, 79*2, true);
sprite_change_offset("ustrong_yield", 64, 79, true);
sprite_change_offset("ustrong_stop", 64, 79, true);
sprite_change_offset("ustrong_shovel", 64, 79, true);
sprite_change_offset("ustrong_hurt", 64*2, 79*2, true);
sprite_change_offset("dstrong", 64, 79, true);
sprite_change_offset("dstrong_ladderless", 64, 79, true);
sprite_change_offset("ladder_box", 16, 35, true);
sprite_change_offset("ladder_mask", 16, 35, true);
sprite_change_offset("ladder_extended", 16, 118, true);
sprite_change_offset("ladder_small", 7, 25, true);
sprite_change_offset("ladder_med", 7, 45, true);
sprite_change_offset("ladder_big", 7, 65, true);
sprite_change_offset("ladder_huge", 7, 85, true);
sprite_change_offset("ladder_box_destroy", 16, 26, true);
sprite_change_offset("nspecial", 64, 79, true);
sprite_change_offset("fspecial", 64, 79, true);
sprite_change_offset("fspecial_grenade", 32, 32, true);
sprite_change_offset("fspecial_grenade_glow", 32, 32, true);
sprite_change_offset("fspecial_grenade_mask", 32, 32, true);
sprite_change_offset("fspecial_grenade_mask_ground", 32, 32, true);
sprite_change_offset("fspec_pin", 7, 12, true);
sprite_change_offset("fspecial2", 64, 79, true);
sprite_change_offset("fspecial2_zap_linger", 64*2, 79*2, true);
sprite_change_offset("fspecial2_scan_linger", 64*2, 79*2, true);
sprite_change_offset("fspecial_fail", 64, 79, true);
sprite_change_offset("fspecial_fail_hurt", 64*2, 79*2, true);
sprite_change_offset("fspecial2_fail", 64, 79, true);
sprite_change_offset("fspecial2_fail_hurt", 64*2, 79*2, true);
sprite_change_offset("zapgun", 22, 16, true);
sprite_change_offset("uspecial", 64, 79, true);
sprite_change_offset("uspec_smoke", 23, 24, true);
sprite_change_offset("uspecial2", 64, 79, true);
sprite_change_offset("uspecial2_wheels", 64, 79, true);
sprite_change_offset("uspecial_fail", 64, 79, true);
sprite_change_offset("uspecial_fail_hurt", 64*2, 79*2, true);
sprite_change_offset("vfx_cruiser", 87, 48, true);
sprite_change_offset("vfx_cruiser_debris0", 89, 41, true);
sprite_change_offset("vfx_cruiser_debris1", 29, 17, true);
sprite_change_offset("vfx_cruiser_debris2", 24, 16, true);
sprite_change_offset("vfx_cruiser_eject", 87, 64, true);
sprite_change_offset("dspecial", 64, 79, true);
sprite_change_offset("dspecial2", 64, 79, true);
sprite_change_offset("dspecial_linger", 64*2, 79*2, true);
sprite_change_offset("scan_reticle_inner", 7, 7, true);
sprite_change_offset("scan_reticle_outer", 15, 15, true);
sprite_change_offset("scan_scrap_inner", 10, 10, true);
sprite_change_offset("scan_scrao_outer", 14, 14, true);
sprite_change_offset("taunt", 64, 79, true);
sprite_change_offset("taunt2", 64, 79, true);

sprite_change_offset("jeb_mask", 65, 62, true);
sprite_change_offset("jeb_open", 65, 62, true);
sprite_change_offset("jeb_close", 65, 62, true);
sprite_change_offset("jeb_takescrap", 65, 62, true);
sprite_change_offset("jeb_bell", 65, 62, true);
sprite_change_offset("jeb_angry", 81, 62, true);
sprite_change_offset("scrap_proj", 15, 15, true);
sprite_change_offset("scrap_dropped", 15, 15, true);
sprite_change_offset("scrap_cork_visual", 15, 15, true);
sprite_change_offset("scrap_large", 25, 25, true);
sprite_change_offset("scrap_mask_small", 15, 15, true);
sprite_change_offset("scrap_teeth", 15, 15, true);
sprite_change_offset("scrap_whoopee", 15, 28, true);
sprite_change_offset("scrap_whoopee_mask", 15, 28, true);
sprite_change_offset("scrap_mask_large", 25, 25, true);
sprite_change_offset("egg_explode", 96, 96, true);
sprite_change_offset("mask_active", 16, 16, true);
sprite_change_offset("mask_blood", 76, 76, true);
sprite_change_offset("bees", 64, 61, true);
sprite_change_offset("bees_destroyed", 64, 61, true);
sprite_change_offset("zap_small", 96, 96, true);
sprite_change_offset("zapgun_big", 128, 128, true);
sprite_change_offset("hfx_flashbang_hit", 128, 128);
sprite_change_offset("vfx_cork", 3, 4);

for (i = 0; i < 3; i++) {
    sprite_change_offset(`vfx_drop_melee${i}`, 21, 42, true);
}
sprite_change_offset("vfx_explosion", 128, 128, true);

sprite_change_offset("plat", 64, 79);
sprite_change_offset("plat_real", 64, 79);
sprite_change_offset("mamizou_transformation", 64, 79);
sprite_change_offset("intro", 64, 79, true);

sprite_change_offset("hud_rabbit", 0, -2);
sprite_change_offset("hudhurt_rabbit", 0, -2);
sprite_change_offset("offscreen_rabbit", 17, 17);

user_event(15); //initialize skin handler