set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("extra2"));
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 11);
set_attack_value(AT_EXTRA_2, AG_HAS_LANDING_LAG, 4);

set_attack_value(AT_EXTRA_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_EXTRA_2, AG_USES_CUSTOM_GRAVITY, 1);
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("extra2_hurt"));


set_window_value(AT_EXTRA_2, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX, sound_get("SpaceCutB"));
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_VSPEED, -3);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(AT_EXTRA_2, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_SFX_FRAME, 8);
set_window_value(AT_EXTRA_2, 2, AG_WINDOW_HSPEED, 0);



set_window_value(AT_EXTRA_2, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 3, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_LENGTH, 6);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 4, AG_WINDOW_SFX, asset_get("sfx_spin"));

set_window_value(AT_EXTRA_2, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_LENGTH, 2);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 5, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 6, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_LENGTH, 2);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 6, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 7, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_LENGTH, 2);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 7, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 8, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_LENGTH, 2);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 8, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 9, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_LENGTH, 2);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_EXTRA_2, 9, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 10, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_LENGTH, 8);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_VSPEED, -6.5);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_CUSTOM_GRAVITY, 0.2);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_EXTRA_2, 10, AG_WINDOW_HSPEED, 0);

set_window_value(AT_EXTRA_2, 11, AG_WINDOW_TYPE, 7);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_LENGTH, 25);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_CUSTOM_GRAVITY, 1);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_2, 11, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));






set_num_hitboxes(AT_EXTRA_2, 10);

set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 1, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 1, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_EXTRA_2, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_EXTRA_2, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW, 4);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 2, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 2, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE, 70);
set_hitbox_value(AT_EXTRA_2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW, 5);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 3, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 3, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 70);
set_hitbox_value(AT_EXTRA_2, 3, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW, 6);
set_hitbox_value(AT_EXTRA_2, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 4, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 4, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 4, HG_ANGLE, 70);
set_hitbox_value(AT_EXTRA_2, 4, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_2, 4, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 4, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 4, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 4, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_WINDOW, 10);
set_hitbox_value(AT_EXTRA_2, 5, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 5, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 5, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 5, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 5, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_EXTRA_2, 5, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 5, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 5, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 5, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 5, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 5, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 5, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_WINDOW, 11);
set_hitbox_value(AT_EXTRA_2, 6, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_LIFETIME, 6); 
set_hitbox_value(AT_EXTRA_2, 6, HG_HITBOX_X, 26);
set_hitbox_value(AT_EXTRA_2, 6, HG_HITBOX_Y, -42);
set_hitbox_value(AT_EXTRA_2, 6, HG_WIDTH, 98);
set_hitbox_value(AT_EXTRA_2, 6, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 6, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 6, HG_DAMAGE, 4);
set_hitbox_value(AT_EXTRA_2, 6, HG_ANGLE, 40);
set_hitbox_value(AT_EXTRA_2, 6, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 6, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_2, 6, HG_KNOCKBACK_SCALING, 0.9);
set_hitbox_value(AT_EXTRA_2, 6, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_2, 6, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_EXTRA_2, 6, HG_HITPAUSE_SCALING, .55);
set_hitbox_value(AT_EXTRA_2, 6, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 6, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_2, 6, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 6, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 7, HG_WINDOW, 9);
set_hitbox_value(AT_EXTRA_2, 7, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 7, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 7, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 7, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 7, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 7, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 7, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 7, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 7, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 7, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 7, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_EXTRA_2, 7, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 7, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 7, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 7, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 7, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 7, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 7, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 7, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 8, HG_WINDOW, 8);
set_hitbox_value(AT_EXTRA_2, 8, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 8, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 8, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 8, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 8, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 8, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 8, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 8, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 8, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 8, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_EXTRA_2, 8, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 8, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 8, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 8, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 8, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 8, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 8, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 8, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 10, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 10, HG_WINDOW, 7);
set_hitbox_value(AT_EXTRA_2, 10, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 10, HG_LIFETIME, 4); 
set_hitbox_value(AT_EXTRA_2, 10, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_2, 10, HG_HITBOX_Y, -32);
set_hitbox_value(AT_EXTRA_2, 10, HG_WIDTH, 138);
set_hitbox_value(AT_EXTRA_2, 10, HG_HEIGHT, 64);
set_hitbox_value(AT_EXTRA_2, 10, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_2, 10, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 10, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 10, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_2, 10, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_EXTRA_2, 10, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_2, 10, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_EXTRA_2, 10, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_EXTRA_2, 10, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 10, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 10, HG_HIT_SFX, sound_get("slicel"));
set_hitbox_value(AT_EXTRA_2, 10, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 10, HG_TECHABLE, 1);

set_hitbox_value(AT_EXTRA_2, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_2, 9, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_2, 9, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_EXTRA_2, 9, HG_LIFETIME, 27); 
set_hitbox_value(AT_EXTRA_2, 9, HG_HITBOX_X, 30);
set_hitbox_value(AT_EXTRA_2, 9, HG_HITBOX_Y, -62);
set_hitbox_value(AT_EXTRA_2, 9, HG_WIDTH, 50);
set_hitbox_value(AT_EXTRA_2, 9, HG_HEIGHT, 34);
set_hitbox_value(AT_EXTRA_2, 9, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_2, 9, HG_DAMAGE, 8);
set_hitbox_value(AT_EXTRA_2, 9, HG_ANGLE, 60);
set_hitbox_value(AT_EXTRA_2, 9, HG_SHAPE, 7);
set_hitbox_value(AT_EXTRA_2, 9, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_2, 9, HG_KNOCKBACK_SCALING, 1.0);
set_hitbox_value(AT_EXTRA_2, 9, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_2, 9, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 9, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_EXTRA_2, 9, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_2, 9, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_EXTRA_2, 9, HG_HITBOX_GROUP, 1);


