set_attack_value(AT_UTILT, AG_SPRITE, sprite_get("utilt"));
set_attack_value(AT_UTILT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_UTILT, AG_HURTBOX_SPRITE, sprite_get("utilt_hurt"));

set_window_value(AT_UTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_UTILT, 1, AG_WINDOW_LENGTH, 7);
set_window_value(AT_UTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);

set_window_value(AT_UTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_UTILT, 2, AG_WINDOW_LENGTH, 8);
set_window_value(AT_UTILT, 2, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_UTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_UTILT, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UTILT, 2, AG_WINDOW_SFX, sound_get("panswing"));
set_window_value(AT_UTILT, 2, AG_WINDOW_SFX_FRAME, 2);

set_window_value(AT_UTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_UTILT, 3, AG_WINDOW_LENGTH, 7);
set_window_value(AT_UTILT, 3, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_UTILT, 3, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_UTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 5);

set_num_hitboxes(AT_UTILT, 6);

set_hitbox_value(AT_UTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_Y, -36);
set_hitbox_value(AT_UTILT, 1, HG_HITBOX_X, -22);
set_hitbox_value(AT_UTILT, 1, HG_WIDTH, 24);
set_hitbox_value(AT_UTILT, 1, HG_HEIGHT, 23);
set_hitbox_value(AT_UTILT, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 1, HG_ANGLE, 80);
set_hitbox_value(AT_UTILT, 1, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 1, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 1, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 1, HG_HIT_SFX, sound_get("bash"));

set_hitbox_value(AT_UTILT, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 2, HG_LIFETIME, 1);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_Y, -57);
set_hitbox_value(AT_UTILT, 2, HG_HITBOX_X, -11);
set_hitbox_value(AT_UTILT, 2, HG_WIDTH, 27);
set_hitbox_value(AT_UTILT, 2, HG_HEIGHT, 29);
set_hitbox_value(AT_UTILT, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 2, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 2, HG_ANGLE, 80);
set_hitbox_value(AT_UTILT, 2, HG_SHAPE, 2);;
set_hitbox_value(AT_UTILT, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 2, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 2, HG_HIT_SFX, sound_get("bash"));

set_hitbox_value(AT_UTILT, 3, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 3, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 3, HG_LIFETIME, 1);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_Y, -57);
set_hitbox_value(AT_UTILT, 3, HG_HITBOX_X, 12);
set_hitbox_value(AT_UTILT, 3, HG_WIDTH, 23);
set_hitbox_value(AT_UTILT, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_UTILT, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 3, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 3, HG_ANGLE, 70);
set_hitbox_value(AT_UTILT, 3, HG_SHAPE, 2)
set_hitbox_value(AT_UTILT, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 3, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 3, HG_HIT_SFX, sound_get("bash"));

set_hitbox_value(AT_UTILT, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 4, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_Y, -57);
set_hitbox_value(AT_UTILT, 4, HG_HITBOX_X, 22);
set_hitbox_value(AT_UTILT, 4, HG_WIDTH, 24);
set_hitbox_value(AT_UTILT, 4, HG_HEIGHT, 35);
set_hitbox_value(AT_UTILT, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 4, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 4, HG_ANGLE, 70);
set_hitbox_value(AT_UTILT, 4, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 4, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 4, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 4, HG_HIT_SFX, sound_get("bash"));

set_hitbox_value(AT_UTILT, 5, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 5, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 5, HG_LIFETIME, 1);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_Y, -39);
set_hitbox_value(AT_UTILT, 5, HG_HITBOX_X, 35);
set_hitbox_value(AT_UTILT, 5, HG_WIDTH, 29);
set_hitbox_value(AT_UTILT, 5, HG_HEIGHT, 28);
set_hitbox_value(AT_UTILT, 5, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 5, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 5, HG_ANGLE, 60);
set_hitbox_value(AT_UTILT, 5, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 5, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 5, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 5, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 5, HG_HIT_SFX, sound_get("bash"));

set_hitbox_value(AT_UTILT, 6, HG_WINDOW_CREATION_FRAME, 7);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UTILT, 6, HG_WINDOW, 2);
set_hitbox_value(AT_UTILT, 6, HG_LIFETIME, 1);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_Y, -15);
set_hitbox_value(AT_UTILT, 6, HG_HITBOX_X, 35);
set_hitbox_value(AT_UTILT, 6, HG_WIDTH, 32);
set_hitbox_value(AT_UTILT, 6, HG_HEIGHT, 26);
set_hitbox_value(AT_UTILT, 6, HG_PRIORITY, 3);
set_hitbox_value(AT_UTILT, 6, HG_DAMAGE, 8);
set_hitbox_value(AT_UTILT, 6, HG_ANGLE, 60);
set_hitbox_value(AT_UTILT, 6, HG_SHAPE, 2);
set_hitbox_value(AT_UTILT, 6, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UTILT, 6, HG_KNOCKBACK_SCALING, 0.25);
set_hitbox_value(AT_UTILT, 6, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UTILT, 6, HG_HIT_SFX, sound_get("bash"));