dairtimer = 0;
charge_max = 100;
charge = charge_max;
charge_drain_rate = 0.05;
charge_anim = 0;         //sub-image variable for meter animation
charge_prev = 1;   
venom_anim = 0;         //sub-image variable for meter animation
venom_prev = 1;   
stat_drain = 0.001;
venom = 3;
venom_min = 0;
venom1_boost = 1.125;
venom2_boost = 1.25;
venom3_boost = 1.15;
venom_timer = 0;
venom_timer_min = 0;
venom_drain_rate = .15;
venom_current = 0;
short = 0;
short_anim = 0;         //sub-image variable for meter animation
short_timer = 100;
short_drain = .2;
short_min = 0;
short_timer_min = 0;
venom_recharge = 0;
venom_recharge_active = false;
venom_recharge_rate = 0.1;
venom_recharge_max = 300;
venom_recharge_min = 0;
venom_stack = 0;