set_attack_value(49, AG_SPRITE, sprite_get("fs"));
set_attack_value(49, AG_NUM_WINDOWS, 5);
set_attack_value(49, AG_HAS_LANDING_LAG, 3);
set_attack_value(49, AG_OFF_LEDGE, 1);
set_attack_value(49, AG_HURTBOX_SPRITE, sprite_get("ouchyidle"));

set_window_value(49,  1, AG_WINDOW_TYPE, 1);
set_window_value(49,  1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49,  1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49,  1, AG_WINDOW_LENGTH, 18);
set_window_value(49,  1, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(49,  1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(49,  1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49,  1, AG_WINDOW_SFX, sound_get("swipe2"));
set_window_value(49,  1, AG_WINDOW_SFX_FRAME, 5);

set_window_value(49,  2, AG_WINDOW_TYPE, 1);
set_window_value(49,  2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49,  2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49,  2, AG_WINDOW_LENGTH, 10);
set_window_value(49,  2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(49,  2, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(49,  2, AG_WINDOW_HAS_SFX, 1);
set_window_value(49,  2, AG_WINDOW_SFX, sound_get("hit_bonk"));

set_window_value(49,  3, AG_WINDOW_TYPE, 1);
set_window_value(49,  3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49,  3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49,  3, AG_WINDOW_LENGTH, 7);
set_window_value(49,  3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(49,  3, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(49,  3, AG_WINDOW_HAS_SFX, 1);
set_window_value(49,  3, AG_WINDOW_SFX, sound_get("split"));
set_window_value(49,  3, AG_WINDOW_SFX_FRAME, 3);

set_window_value(49,  4, AG_WINDOW_TYPE, 1);
set_window_value(49,  4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49,  4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49,  4, AG_WINDOW_LENGTH, 7);
set_window_value(49,  4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49,  4, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(49,  4, AG_WINDOW_HAS_SFX, 1);
set_window_value(49,  4, AG_WINDOW_SFX, sound_get("atomb"));

set_window_value(49,  5, AG_WINDOW_TYPE, 1);
set_window_value(49,  5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49,  5, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49,  5, AG_WINDOW_LENGTH, 30);
set_window_value(49,  5, AG_WINDOW_ANIM_FRAMES, 9);
set_window_value(49,  5, AG_WINDOW_ANIM_FRAME_START, 9);

set_num_hitboxes(49, 8);

set_hitbox_value(49, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(49, 1, HG_WINDOW, 99);
set_hitbox_value(49, 1, HG_LIFETIME, 25);
set_hitbox_value(49, 1, HG_HITBOX_Y, -0);
set_hitbox_value(49, 1, HG_WIDTH, 125);
set_hitbox_value(49, 1, HG_HEIGHT, 125);
set_hitbox_value(49, 1, HG_PRIORITY, 1);
set_hitbox_value(49, 1, HG_DAMAGE, 12);
set_hitbox_value(49, 1, HG_ANGLE, 70);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 20);
set_hitbox_value(49, 1, HG_KNOCKBACK_SCALING, .6);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 25);
set_hitbox_value(49, 1, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 143 );
set_hitbox_value(49, 1, HG_PROJECTILE_SPRITE, sprite_get("booom"));
set_hitbox_value(49, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(49, 1, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(49, 1, HG_PROJECTILE_AIR_FRICTION, 0.03);
set_hitbox_value(49, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(49, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(49, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(49, 1, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(49, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(49, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);


set_hitbox_value(49, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(49, 2, HG_WINDOW, 99);
set_hitbox_value(49, 2, HG_LIFETIME, 25);
set_hitbox_value(49, 2, HG_HITBOX_Y, -0);
set_hitbox_value(49, 2, HG_WIDTH, 125);
set_hitbox_value(49, 2, HG_HEIGHT, 125);
set_hitbox_value(49, 2, HG_PRIORITY, 1);
set_hitbox_value(49, 2, HG_DAMAGE, 12);
set_hitbox_value(49, 2, HG_ANGLE, 70);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 20);
set_hitbox_value(49, 2, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 25);
set_hitbox_value(49, 2, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT, 143 );
set_hitbox_value(49, 2, HG_PROJECTILE_SPRITE, sprite_get("booom2"));
set_hitbox_value(49, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(49, 2, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(49, 2, HG_PROJECTILE_AIR_FRICTION, 0.03);
set_hitbox_value(49, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(49, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(49, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(49, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(49, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(49, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);


set_hitbox_value(49, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(49, 3, HG_WINDOW, 4);
set_hitbox_value(49, 3, HG_LIFETIME, 30);
set_hitbox_value(49, 3, HG_HITBOX_Y, -0);
set_hitbox_value(49, 3, HG_WIDTH, 0);
set_hitbox_value(49, 3, HG_HEIGHT, 0);
set_hitbox_value(49, 3, HG_PROJECTILE_SPRITE, sprite_get("plat"));
set_hitbox_value(49, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(49, 3, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(49, 3, HG_PROJECTILE_AIR_FRICTION, 0.03);
set_hitbox_value(49, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(49, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(49, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(49, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(49, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(49, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);

set_hitbox_value(49, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(49, 4, HG_WINDOW, 99);
set_hitbox_value(49, 4, HG_LIFETIME, 23);
set_hitbox_value(49, 4, HG_HITBOX_Y, -0);
set_hitbox_value(49, 4, HG_WIDTH, 45);
set_hitbox_value(49, 4, HG_HEIGHT, 45);
set_hitbox_value(49, 4, HG_PRIORITY, 1);
set_hitbox_value(49, 4, HG_DAMAGE, 7);
set_hitbox_value(49, 4, HG_ANGLE, 70);
set_hitbox_value(49, 4, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 4, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(49, 4, HG_BASE_HITPAUSE, 25);
set_hitbox_value(49, 4, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(49, 4, HG_VISUAL_EFFECT, 143 );
set_hitbox_value(49, 4, HG_PROJECTILE_SPRITE, sprite_get("boom"));
set_hitbox_value(49, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(49, 4, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(49, 4, HG_PROJECTILE_AIR_FRICTION, 0.03);
set_hitbox_value(49, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(49, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(49, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(49, 4, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(49, 4, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(49, 4, HG_PROJECTILE_IS_TRANSCENDENT, 1);


set_hitbox_value(49, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(49, 5, HG_WINDOW, 99);
set_hitbox_value(49, 5, HG_LIFETIME, 23);
set_hitbox_value(49, 5, HG_HITBOX_Y, -0);
set_hitbox_value(49, 5, HG_WIDTH, 45);
set_hitbox_value(49, 5, HG_HEIGHT, 45);
set_hitbox_value(49, 5, HG_PRIORITY, 1);
set_hitbox_value(49, 5, HG_DAMAGE, 7);
set_hitbox_value(49, 5, HG_ANGLE, 70);
set_hitbox_value(49, 5, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 5, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(49, 5, HG_BASE_HITPAUSE, 25);
set_hitbox_value(49, 5, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(49, 5, HG_VISUAL_EFFECT, 143 );
set_hitbox_value(49, 5, HG_PROJECTILE_SPRITE, sprite_get("boomd"));
set_hitbox_value(49, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(49, 5, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(49, 5, HG_PROJECTILE_AIR_FRICTION, 0.03);
set_hitbox_value(49, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(49, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(49, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(49, 5, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(49, 5, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(49, 5, HG_PROJECTILE_IS_TRANSCENDENT, 1);