set_attack_value(AT_NAIR, AG_CATEGORY, 1);
set_attack_value(AT_NAIR, AG_SPRITE, sprite_get("nair"));
set_attack_value(AT_NAIR, AG_NUM_WINDOWS, 4);
set_attack_value(AT_NAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_NAIR, AG_LANDING_LAG, 4);
set_attack_value(AT_NAIR, AG_HURTBOX_SPRITE, sprite_get("nair_hurt"));

set_window_value(AT_NAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_SFX, sound_get("spin"));
set_window_value(AT_NAIR, 1, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_NAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_LENGTH, 25);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAMES, 13);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAME_START, 2);

set_window_value(AT_NAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAME_START, 19);

set_window_value(AT_NAIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_LENGTH, 10);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAME_START, 20);
set_window_value(AT_NAIR, 4, AG_WINDOW_HAS_WHIFFLAG, 4);
set_window_value(AT_NAIR, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_SFX, sound_get("hoop"));
set_window_value(AT_NAIR, 4, AG_WINDOW_SFX_FRAME, 0);

set_num_hitboxes(AT_NAIR, 7);

set_hitbox_value(AT_NAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_X, 4);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 1, HG_WIDTH, 93);
set_hitbox_value(AT_NAIR, 1, HG_HEIGHT, 30);
set_hitbox_value(AT_NAIR, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_NAIR, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE, 45);
set_hitbox_value(AT_NAIR, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_NAIR, 1, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_NAIR, 1, HG_VISUAL_EFFECT, 302);
set_hitbox_value(AT_NAIR, 1, HG_HIT_SFX, sound_get("hit_weak"));

set_hitbox_value(AT_NAIR, 2, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_NAIR, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_X, 4);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_NAIR, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_NAIR, 3, HG_LIFETIME, 6);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_X, 4);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 3, HG_WIDTH, 92);
set_hitbox_value(AT_NAIR, 3, HG_HEIGHT, 30);
set_hitbox_value(AT_NAIR, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_NAIR, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE, 70);
set_hitbox_value(AT_NAIR, 3, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_NAIR, 3, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_NAIR, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_NAIR, 3, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 3, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_NAIR, 3, HG_HIT_SFX, sound_get("hit_med"));
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_GROUP, 2);

set_hitbox_value(AT_NAIR, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 7, HG_WINDOW, 3);
set_hitbox_value(AT_NAIR, 7, HG_LIFETIME, 350);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_X, 0);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_Y, 0);
set_hitbox_value(AT_NAIR, 7, HG_WIDTH, 70);
set_hitbox_value(AT_NAIR, 7, HG_HEIGHT, 20);
set_hitbox_value(AT_NAIR, 7, HG_SHAPE, 1);
set_hitbox_value(AT_NAIR, 7, HG_PRIORITY, 3);
set_hitbox_value(AT_NAIR, 7, HG_DAMAGE, 4);
set_hitbox_value(AT_NAIR, 7, HG_ANGLE, 260);
set_hitbox_value(AT_NAIR, 7, HG_BASE_KNOCKBACK, 14);
set_hitbox_value(AT_NAIR, 7, HG_KNOCKBACK_SCALING, .105);
set_hitbox_value(AT_NAIR, 7, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_NAIR, 7, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_NAIR, 7, HG_HITSTUN_MULTIPLIER, .5);
set_hitbox_value(AT_NAIR, 7, HG_HIT_SFX, sound_get("hit_weak"));
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_SPRITE, sprite_get("hoop"));
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_GRAVITY, 0.4);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_HSPEED, -5);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_VSPEED, -11);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_DESTROY_EFFECT, poof);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_AIR_FRICTION, 0.05);