set_attack_value(AT_FSPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_FSPECIAL, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_NUM_WINDOWS, 3);
set_attack_value(AT_FSPECIAL, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_FSPECIAL, AG_OFF_LEDGE, 1);
set_attack_value(AT_FSPECIAL, AG_AIR_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));

set_window_value(AT_FSPECIAL, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_LENGTH, 18);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_SFX, sound_get("sfx_ex"));
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_SFX_FRAME, 16);

set_window_value(AT_FSPECIAL, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 3);

set_window_value(AT_FSPECIAL, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_ANIM_FRAME_START, 7);

//Peashooter EX - Mega Blast
set_hitbox_value(AT_FSPECIAL, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_FSPECIAL, 1, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_X, 32);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 1, HG_WIDTH, 90);
set_hitbox_value(AT_FSPECIAL, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_FSPECIAL, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 1, HG_DAMAGE, 15);
set_hitbox_value(AT_FSPECIAL, 1, HG_ANGLE, 50);
set_hitbox_value(AT_FSPECIAL, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, 1, HG_KNOCKBACK_SCALING, .95);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_SPRITE, sprite_get("ex_shot"));
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_MASK, sprite_get("ex_shot"));
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_HSPEED, 16);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);

//Spread EX - Eight Way

set_hitbox_value(AT_FSPECIAL, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 2, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 2, HG_ANGLE, 90);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_VSPEED, -2);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 3, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 3, HG_ANGLE, 45);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 3, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_VSPEED, -1.5);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_HSPEED, 1.5);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 4, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 4, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 5, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 5, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 5, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 5, HG_ANGLE, 315);
set_hitbox_value(AT_FSPECIAL, 5, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 5, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 5, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 5, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 5, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 5, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 5, HG_PROJECTILE_VSPEED, 1.5);
set_hitbox_value(AT_FSPECIAL, 5, HG_PROJECTILE_HSPEED, 1.5);
set_hitbox_value(AT_FSPECIAL, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 6, HG_PARENT_HITBOX, 6);
set_hitbox_value(AT_FSPECIAL, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 6, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 6, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 6, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 6, HG_ANGLE, 270);
set_hitbox_value(AT_FSPECIAL, 6, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 6, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 6, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 6, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 6, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 6, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 6, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 6, HG_PROJECTILE_VSPEED, 2);
set_hitbox_value(AT_FSPECIAL, 6, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_FSPECIAL, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 7, HG_PARENT_HITBOX, 7);
set_hitbox_value(AT_FSPECIAL, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 7, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 7, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 7, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 7, HG_ANGLE, 225);
set_hitbox_value(AT_FSPECIAL, 7, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 7, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 7, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 7, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 7, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 7, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 7, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 7, HG_PROJECTILE_VSPEED, 1.5);
set_hitbox_value(AT_FSPECIAL, 7, HG_PROJECTILE_HSPEED, -1.5);
set_hitbox_value(AT_FSPECIAL, 7, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 8, HG_PARENT_HITBOX, 8);
set_hitbox_value(AT_FSPECIAL, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 8, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 8, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 8, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 8, HG_ANGLE, 180);
set_hitbox_value(AT_FSPECIAL, 8, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 8, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 8, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 8, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 8, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 8, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 8, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 8, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_FSPECIAL, 8, HG_PROJECTILE_HSPEED, -2);
set_hitbox_value(AT_FSPECIAL, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 9, HG_PARENT_HITBOX, 9);
set_hitbox_value(AT_FSPECIAL, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 9, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 9, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 9, HG_DAMAGE, 7);
set_hitbox_value(AT_FSPECIAL, 9, HG_ANGLE, 135);
set_hitbox_value(AT_FSPECIAL, 9, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_FSPECIAL, 9, HG_KNOCKBACK_SCALING, .55);
set_hitbox_value(AT_FSPECIAL, 9, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 9, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 9, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 9, HG_PROJECTILE_SPRITE, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 9, HG_PROJECTILE_MASK, sprite_get("spread_ex"));
set_hitbox_value(AT_FSPECIAL, 9, HG_PROJECTILE_VSPEED, -1.5);
set_hitbox_value(AT_FSPECIAL, 9, HG_PROJECTILE_HSPEED, -1.5);
set_hitbox_value(AT_FSPECIAL, 9, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

//Chaser EX - Chaos Orbit

set_hitbox_value(AT_FSPECIAL, 11, HG_PARENT_HITBOX, 11);
set_hitbox_value(AT_FSPECIAL, 11, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 11, HG_LIFETIME, 2);
set_hitbox_value(AT_FSPECIAL, 11, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 11, HG_DAMAGE, 2);
set_hitbox_value(AT_FSPECIAL, 11, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL, 11, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, 11, HG_HITBOX_Y, -30);
set_hitbox_value(AT_FSPECIAL, 11, HG_WIDTH, 100);
set_hitbox_value(AT_FSPECIAL, 11, HG_HEIGHT, 100);
set_hitbox_value(AT_FSPECIAL, 11, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_FSPECIAL, 11, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_FSPECIAL, 11, HG_HIT_SFX, asset_get("sfx_blow_weak1"));
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 11, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_FSPECIAL, 11, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 11, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FSPECIAL, 11, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 11, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSPECIAL, 11, HG_HIT_LOCKOUT, 30);

//Lobber EX - Mega Kablooey
set_hitbox_value(AT_FSPECIAL, 12, HG_PARENT_HITBOX, 12);
set_hitbox_value(AT_FSPECIAL, 12, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 12, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 12, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_FSPECIAL, 12, HG_LIFETIME, 90);
set_hitbox_value(AT_FSPECIAL, 12, HG_HITBOX_X, 32);
set_hitbox_value(AT_FSPECIAL, 12, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 12, HG_WIDTH, 90);
set_hitbox_value(AT_FSPECIAL, 12, HG_HEIGHT, 60);
set_hitbox_value(AT_FSPECIAL, 12, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 12, HG_DAMAGE, 25);
set_hitbox_value(AT_FSPECIAL, 12, HG_ANGLE, 50);
set_hitbox_value(AT_FSPECIAL, 12, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_FSPECIAL, 12, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_FSPECIAL, 12, HG_KNOCKBACK_SCALING, .65);
set_hitbox_value(AT_FSPECIAL, 12, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL, 12, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_FSPECIAL, 12, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 12, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_SPRITE, sprite_get("kablooey"));
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_MASK, sprite_get("kablooey"));
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_HSPEED, 8);
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_GRAVITY, 0.7);
set_hitbox_value(AT_FSPECIAL, 12, HG_PROJECTILE_AIR_FRICTION, 0.05);

//Charge EX - Radical Barrage

set_hitbox_value(AT_FSPECIAL, 10, HG_PARENT_HITBOX, 10);
set_hitbox_value(AT_FSPECIAL, 10, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 10, HG_LIFETIME, 10);
set_hitbox_value(AT_FSPECIAL, 10, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 10, HG_DAMAGE, 15);
set_hitbox_value(AT_FSPECIAL, 10, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL, 10, HG_HITBOX_X, 40);
set_hitbox_value(AT_FSPECIAL, 10, HG_HITBOX_Y, -34);
set_hitbox_value(AT_FSPECIAL, 10, HG_WIDTH, 120);
set_hitbox_value(AT_FSPECIAL, 10, HG_HEIGHT, 120);
set_hitbox_value(AT_FSPECIAL, 10, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FSPECIAL, 10, HG_KNOCKBACK_SCALING, .45);
set_hitbox_value(AT_FSPECIAL, 10, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 10, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 10, HG_HITPAUSE_SCALING, 0.75);
set_hitbox_value(AT_FSPECIAL, 10, HG_HITSTUN_MULTIPLIER, 1);

set_hitbox_value(AT_FSPECIAL, 15, HG_PARENT_HITBOX, 15);
set_hitbox_value(AT_FSPECIAL, 15, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 15, HG_LIFETIME, 10);
set_hitbox_value(AT_FSPECIAL, 15, HG_PRIORITY, 6);
set_hitbox_value(AT_FSPECIAL, 15, HG_DAMAGE, 20);
set_hitbox_value(AT_FSPECIAL, 15, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL, 15, HG_HITBOX_X, 40);
set_hitbox_value(AT_FSPECIAL, 15, HG_HITBOX_Y, -34);
set_hitbox_value(AT_FSPECIAL, 15, HG_WIDTH, 50);
set_hitbox_value(AT_FSPECIAL, 15, HG_HEIGHT, 50);
set_hitbox_value(AT_FSPECIAL, 15, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FSPECIAL, 15, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSPECIAL, 15, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 15, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FSPECIAL, 15, HG_HITPAUSE_SCALING, 0.95);
set_hitbox_value(AT_FSPECIAL, 15, HG_HITSTUN_MULTIPLIER, 1);

//Roundabout EX - Jumbo Rebound
set_hitbox_value(AT_FSPECIAL, 13, HG_PARENT_HITBOX, 13);
set_hitbox_value(AT_FSPECIAL, 13, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 13, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 13, HG_WINDOW_CREATION_FRAME, 5);
set_hitbox_value(AT_FSPECIAL, 13, HG_LIFETIME, 300);
set_hitbox_value(AT_FSPECIAL, 13, HG_HITBOX_X, 32);
set_hitbox_value(AT_FSPECIAL, 13, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 13, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 13, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_SPRITE, sprite_get("rebound"));
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_MASK, sprite_get("rebound"));
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_HSPEED, 8);
set_hitbox_value(AT_FSPECIAL, 13, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 13, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);

set_hitbox_value(AT_FSPECIAL, 14, HG_PARENT_HITBOX, 14);
set_hitbox_value(AT_FSPECIAL, 14, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 14, HG_LIFETIME, 2);
set_hitbox_value(AT_FSPECIAL, 14, HG_PRIORITY, 3);
set_hitbox_value(AT_FSPECIAL, 14, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL, 14, HG_ANGLE, 361);
set_hitbox_value(AT_FSPECIAL, 14, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_FSPECIAL, 14, HG_HITBOX_Y, -30);
set_hitbox_value(AT_FSPECIAL, 14, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 14, HG_HEIGHT, 60);
set_hitbox_value(AT_FSPECIAL, 14, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FSPECIAL, 14, HG_KNOCKBACK_SCALING, .35);
set_hitbox_value(AT_FSPECIAL, 14, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FSPECIAL, 14, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FSPECIAL, 14, HG_HITPAUSE_SCALING, 0.4);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 14, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FSPECIAL, 14, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_FSPECIAL, 14, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_FSPECIAL, 14, HG_HIT_LOCKOUT, 2);
