set_attack_value(49, AG_CATEGORY, 2);
set_attack_value(49, AG_SPRITE, sprite_get("azula_ultimate"));
set_attack_value(49, AG_NUM_WINDOWS, 4);
set_attack_value(49, AG_OFF_LEDGE, true);
set_attack_value(49, AG_HAS_LANDING_LAG, 10);
set_attack_value(49, AG_AIR_SPRITE, sprite_get("azula_ultimate"));
set_attack_value(49, AG_HURTBOX_SPRITE, sprite_get("azula_ultimate_hurt"));
set_attack_value(49, AG_USES_CUSTOM_GRAVITY, true);

set_window_value(49, 1, AG_WINDOW_LENGTH, 8);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(49, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 1, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(49, 2, AG_WINDOW_VSPEED, -1.5);
set_window_value(49, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_LENGTH, 6);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(49, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 2, AG_WINDOW_SFX_FRAME, get_window_value(49, 2, AG_WINDOW_LENGTH) - 1);
set_window_value(49, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(49, 2, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(49, 3, AG_WINDOW_LENGTH, 16);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(49, 3, AG_WINDOW_HSPEED, 16);
set_window_value(49, 3, AG_WINDOW_VSPEED, -5);
set_window_value(49, 3, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(49, 3, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(49, 3, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(49, 4, AG_WINDOW_LENGTH, 16);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(49, 4, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_window_value(49, 5, AG_WINDOW_LENGTH, 100);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAMES, 47);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAME_START, 13);
set_window_value(49, 5, AG_WINDOW_CUSTOM_GRAVITY, 0.05);
set_window_value(49, 5, AG_WINDOW_INVINCIBILITY, 1);

set_window_value(49, 6, AG_WINDOW_LENGTH, 45);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAME_START, 60);
set_window_value(49, 6, AG_WINDOW_CUSTOM_GRAVITY, 0);

set_window_value(49, 7, AG_WINDOW_LENGTH, 20);
set_window_value(49, 7, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 7, AG_WINDOW_ANIM_FRAME_START, 64);
set_window_value(49, 7, AG_WINDOW_CUSTOM_GRAVITY, 1);

set_num_hitboxes(49, 8);

set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 1, HG_WINDOW, 3);
set_hitbox_value(49, 1, HG_LIFETIME, 18);
set_hitbox_value(49, 1, HG_HITBOX_X, 7);
set_hitbox_value(49, 1, HG_HITBOX_Y, -42);
set_hitbox_value(49, 1, HG_WIDTH, 70);
set_hitbox_value(49, 1, HG_HEIGHT, 75);
set_hitbox_value(49, 1, HG_PRIORITY, 2);
set_hitbox_value(49, 1, HG_DAMAGE, 5);
set_hitbox_value(49, 1, HG_ANGLE, 45);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 1, HG_KNOCKBACK_SCALING, .5);
set_hitbox_value(49, 1, HG_EFFECT, 6);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 1, HG_HIT_SFX, sound_get("ElectricHit"));
set_hitbox_value(49, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 1, HG_HITBOX_GROUP, 1);

set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 2, HG_WINDOW, 5);
set_hitbox_value(49, 2, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(49, 2, HG_LIFETIME, 4);
set_hitbox_value(49, 2, HG_HITBOX_X, 42);
set_hitbox_value(49, 2, HG_HITBOX_Y, -25);
set_hitbox_value(49, 2, HG_WIDTH, 80);
set_hitbox_value(49, 2, HG_HEIGHT, 80);
set_hitbox_value(49, 2, HG_PRIORITY, 2);
set_hitbox_value(49, 2, HG_DAMAGE, 1);
set_hitbox_value(49, 2, HG_TECHABLE, 1);
set_hitbox_value(49, 2, HG_ANGLE, 200);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(49, 2, HG_EFFECT, 6);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 2, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 2, HG_HITBOX_GROUP, 2);

set_hitbox_value(49, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 3, HG_WINDOW, 5);
set_hitbox_value(49, 3, HG_WINDOW_CREATION_FRAME, 32);
set_hitbox_value(49, 3, HG_LIFETIME, 4);
set_hitbox_value(49, 3, HG_HITBOX_X, 42);
set_hitbox_value(49, 3, HG_HITBOX_Y, -25);
set_hitbox_value(49, 3, HG_WIDTH, 80);
set_hitbox_value(49, 3, HG_HEIGHT, 80);
set_hitbox_value(49, 3, HG_PRIORITY, 2);
set_hitbox_value(49, 3, HG_DAMAGE, 1);
set_hitbox_value(49, 3, HG_TECHABLE, 1);
set_hitbox_value(49, 3, HG_ANGLE, 60);
set_hitbox_value(49, 3, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(49, 3, HG_EFFECT, 6);
set_hitbox_value(49, 3, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 3, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 3, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 3, HG_HITBOX_GROUP, 3);

set_hitbox_value(49, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 4, HG_WINDOW, 5);
set_hitbox_value(49, 4, HG_WINDOW_CREATION_FRAME, 49);
set_hitbox_value(49, 4, HG_LIFETIME, 4);
set_hitbox_value(49, 4, HG_HITBOX_X, 42);
set_hitbox_value(49, 4, HG_HITBOX_Y, -25);
set_hitbox_value(49, 4, HG_WIDTH, 80);
set_hitbox_value(49, 4, HG_HEIGHT, 80);
set_hitbox_value(49, 4, HG_PRIORITY, 2);
set_hitbox_value(49, 4, HG_DAMAGE, 1);
set_hitbox_value(49, 4, HG_TECHABLE, 1);
set_hitbox_value(49, 4, HG_ANGLE, 270);
set_hitbox_value(49, 4, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(49, 4, HG_EFFECT, 6);
set_hitbox_value(49, 4, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 4, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 4, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 4, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 4, HG_HITBOX_GROUP, 4);

set_hitbox_value(49, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 5, HG_WINDOW, 5);
set_hitbox_value(49, 5, HG_WINDOW_CREATION_FRAME, 66);
set_hitbox_value(49, 5, HG_LIFETIME, 4);
set_hitbox_value(49, 5, HG_HITBOX_X, 42);
set_hitbox_value(49, 5, HG_HITBOX_Y, -25);
set_hitbox_value(49, 5, HG_WIDTH, 80);
set_hitbox_value(49, 5, HG_HEIGHT, 80);
set_hitbox_value(49, 5, HG_PRIORITY, 2);
set_hitbox_value(49, 5, HG_DAMAGE, 1);
set_hitbox_value(49, 5, HG_TECHABLE, 1);
set_hitbox_value(49, 5, HG_ANGLE, 130);
set_hitbox_value(49, 5, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 5, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(49, 5, HG_EFFECT, 6);
set_hitbox_value(49, 5, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 5, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 5, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 5, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 5, HG_HITBOX_GROUP, 5);

set_hitbox_value(49, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 6, HG_WINDOW, 5);
set_hitbox_value(49, 6, HG_WINDOW_CREATION_FRAME, 83);
set_hitbox_value(49, 6, HG_LIFETIME, 4);
set_hitbox_value(49, 6, HG_HITBOX_X, 42);
set_hitbox_value(49, 6, HG_HITBOX_Y, -25);
set_hitbox_value(49, 6, HG_WIDTH, 80);
set_hitbox_value(49, 6, HG_HEIGHT, 80);
set_hitbox_value(49, 6, HG_PRIORITY, 2);
set_hitbox_value(49, 6, HG_DAMAGE, 1);
set_hitbox_value(49, 6, HG_TECHABLE, 1);
set_hitbox_value(49, 6, HG_ANGLE, 352);
set_hitbox_value(49, 6, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 6, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(49, 6, HG_EFFECT, 6);
set_hitbox_value(49, 6, HG_BASE_HITPAUSE, 1);
set_hitbox_value(49, 6, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 6, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 6, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 6, HG_HITBOX_GROUP, 6);

set_hitbox_value(49, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 8, HG_WINDOW, 7);
set_hitbox_value(49, 8, HG_LIFETIME, 4);
set_hitbox_value(49, 8, HG_SHAPE, 0);
set_hitbox_value(49, 8, HG_HITBOX_X, 60);
set_hitbox_value(49, 8, HG_HITBOX_Y, -45);
set_hitbox_value(49, 8, HG_WIDTH, 150);
set_hitbox_value(49, 8, HG_HEIGHT, 70);
set_hitbox_value(49, 8, HG_PRIORITY, 2);
set_hitbox_value(49, 8, HG_DAMAGE, 17);
set_hitbox_value(49, 8, HG_ANGLE, 45);
set_hitbox_value(49, 8, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 8, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(49, 8, HG_EFFECT, 6);
set_hitbox_value(49, 8, HG_BASE_HITPAUSE, 12);
set_hitbox_value(49, 8, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(49, 8, HG_VISUAL_EFFECT, elec_vfx);
set_hitbox_value(49, 8, HG_HIT_SFX, sound_get("ElectricHit"));
set_hitbox_value(49, 8, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 8, HG_HITBOX_GROUP, 8);