set_attack_value(AT_BAIR, AG_CATEGORY, 2);
set_attack_value(AT_BAIR, AG_SPRITE, sprite_get("bair"));
set_attack_value(AT_BAIR, AG_NUM_WINDOWS, 5);
set_attack_value(AT_BAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_BAIR, AG_LANDING_LAG, 4);
set_attack_value(AT_BAIR, AG_HURTBOX_SPRITE, sprite_get("bair_hurt"));

set_window_value(AT_BAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_BAIR, 1, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_BAIR, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_BAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_BAIR, 1, AG_WINDOW_SFX, asset_get("sfx_clairen_spin"));
set_window_value(AT_BAIR, 1, AG_WINDOW_SFX_FRAME, 5);

set_window_value(AT_BAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 2, AG_WINDOW_LENGTH, 8);
set_window_value(AT_BAIR, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_BAIR, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_BAIR, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_BAIR, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_BAIR, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .04);
set_window_value(AT_BAIR, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, .04);
set_window_value(AT_BAIR, 2, AG_WINDOW_ANIM_FRAME_START, 6);

set_window_value(AT_BAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_BAIR, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_BAIR, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_BAIR, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_BAIR, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, .04);
set_window_value(AT_BAIR, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, .04);
//set_window_value(AT_BAIR, 3, AG_WINDOW_HSPEED_TYPE, 1);
//set_window_value(AT_BAIR, 3, AG_WINDOW_HSPEED, 5);
set_window_value(AT_BAIR, 3, AG_WINDOW_ANIM_FRAME_START, 8);

set_window_value(AT_BAIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 4, AG_WINDOW_LENGTH, 16);
set_window_value(AT_BAIR, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_BAIR, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_BAIR, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_BAIR, 4, AG_WINDOW_CUSTOM_GROUND_FRICTION, .04);
set_window_value(AT_BAIR, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, .04);
//set_window_value(AT_BAIR, 4, AG_WINDOW_HSPEED_TYPE, 1);
//set_window_value(AT_BAIR, 4, AG_WINDOW_HSPEED, 5);
set_window_value(AT_BAIR, 4, AG_WINDOW_ANIM_FRAME_START, 8);

set_window_value(AT_BAIR, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_BAIR, 5, AG_WINDOW_LENGTH, 7);
set_window_value(AT_BAIR, 5, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_BAIR, 5, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_BAIR, 5, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_BAIR, 8);

set_hitbox_value(AT_BAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 1, HG_WINDOW, 3);
set_hitbox_value(AT_BAIR, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_BAIR, 1, HG_WIDTH, 66);
set_hitbox_value(AT_BAIR, 1, HG_HEIGHT, 47);
set_hitbox_value(AT_BAIR, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_BAIR, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_BAIR, 1, HG_ANGLE, 0);
set_hitbox_value(AT_BAIR, 1, HG_BASE_KNOCKBACK, 6);
//set_hitbox_value(AT_BAIR, 1, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_BAIR, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_BAIR, 1, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT, 111);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, -32);
set_hitbox_value(AT_BAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_BAIR, 1, HG_HIT_SFX, asset_get("sfx_clairen_tip_weak"));
//set_hitbox_value(AT_BAIR, 1, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_BAIR, 2, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 2, HG_WINDOW, 3);
set_hitbox_value(AT_BAIR, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_BAIR, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 2, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 3, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 3, HG_WINDOW, 3);
set_hitbox_value(AT_BAIR, 3, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_BAIR, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 3, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 4, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 4, HG_WINDOW, 3);
set_hitbox_value(AT_BAIR, 4, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_BAIR, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 4, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 5, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 5, HG_WINDOW, 4);
set_hitbox_value(AT_BAIR, 5, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_BAIR, 5, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 5, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 6, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 6, HG_WINDOW, 4);
set_hitbox_value(AT_BAIR, 6, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_BAIR, 6, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 6, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 6, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 6, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 7, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_BAIR, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 7, HG_WINDOW, 4);
set_hitbox_value(AT_BAIR, 7, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_BAIR, 7, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 7, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 7, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 7, HG_HITBOX_GROUP, -1);

set_hitbox_value(AT_BAIR, 8, HG_PARENT_HITBOX, 8);
set_hitbox_value(AT_BAIR, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_BAIR, 8, HG_WINDOW, 4);
set_hitbox_value(AT_BAIR, 8, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_BAIR, 8, HG_LIFETIME, 2);
set_hitbox_value(AT_BAIR, 8, HG_HITBOX_X, -77);
set_hitbox_value(AT_BAIR, 8, HG_HITBOX_Y, -44);
set_hitbox_value(AT_BAIR, 8, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_BAIR, 8, HG_WIDTH, 66);
set_hitbox_value(AT_BAIR, 8, HG_HEIGHT, 47);
set_hitbox_value(AT_BAIR, 8, HG_PRIORITY, 2);
set_hitbox_value(AT_BAIR, 8, HG_DAMAGE, 3);
set_hitbox_value(AT_BAIR, 8, HG_ANGLE, 160);
set_hitbox_value(AT_BAIR, 8, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_BAIR, 8, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_BAIR, 8, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_BAIR, 8, HG_VISUAL_EFFECT, 112);
set_hitbox_value(AT_BAIR, 8, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_BAIR, 8, HG_VISUAL_EFFECT_X_OFFSET, -32);
set_hitbox_value(AT_BAIR, 8, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_BAIR, 8, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
//set_hitbox_value(AT_BAIR, 8, HG_ANGLE_FLIPPER, 6);