//draw_debug_text(x,y,"GAUGE = " + string(meter_current) + "/" + string(meter_max));
//draw_debug_text(x,y+12,"Meter Activated: " + string(meter_activated));
//draw_debug_text(x,y+24,"Free: " + string(free));
//draw_debug_text(x,y+36,"Duration: " + string(boost_duration) + " s");
//draw_debug_text(x, y + 12, "" + string(enemy_hitboxID) + string(sprite_index));
//draw_debug_text(x, y + 12, "" + string(hsp) /*+ string(sprite_index)*/);
//with oPlayer draw_debug_text(x, y + 12, string (free));
//var stage_x = get_stage_data( SD_X_POS );
//var stage_y = get_stage_data( SD_Y_POS );
//draw_debug_text(x, y + 12, string(joy_dir));
//draw_debug_text(x, y + 24, "y = " + string(y));
//draw_debug_text(x, y + 36, "x = " + string(x));
//draw_debug_text(x, y + 48, "sty = " + string(stage_y));
//draw_debug_text(x, y + 60, "rw = " + string(room_width));