set_attack_value(AT_USTRONG, AG_SPRITE, sprite_get("ustrong"));
set_attack_value(AT_USTRONG, AG_HURTBOX_SPRITE, sprite_get("ustrong_hurt"));
set_attack_value(AT_USTRONG, AG_NUM_WINDOWS, 3);
set_attack_value(AT_USTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_num_hitboxes(AT_USTRONG, 3);

set_window_value(AT_USTRONG, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_USTRONG, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_USTRONG, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_USTRONG, 1, AG_WINDOW_SFX, asset_get("sfx_absa_cloud_crackle"));
set_window_value(AT_USTRONG, 1, AG_WINDOW_HAS_SFX, true);

set_window_value(AT_USTRONG, 2, AG_WINDOW_LENGTH, 18);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_SFX, true);
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX, sound_get("ustrong"));
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX_FRAME, 13);

set_window_value(AT_USTRONG, 3, AG_WINDOW_LENGTH, 25);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 7);

set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW_CREATION_FRAME, 7);
set_hitbox_value(AT_USTRONG, 1, HG_SHAPE, 1);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_USTRONG, 1, HG_HITPAUSE_SCALING, 0.01);
set_hitbox_value(AT_USTRONG, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_USTRONG, 1, HG_BASE_KNOCKBACK, 4.9);
set_hitbox_value(AT_USTRONG, 1, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_USTRONG, 1, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_Y, -125);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_X, 10);
set_hitbox_value(AT_USTRONG, 1, HG_WIDTH, 20);
set_hitbox_value(AT_USTRONG, 1, HG_HEIGHT, 100);
set_hitbox_value(AT_USTRONG, 1, HG_ANGLE, 270);
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_USTRONG, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 1, HG_TECHABLE, 3);
set_hitbox_value(AT_USTRONG, 1, HG_HIT_SFX, asset_get("sfx_absa_singlezap1"));
set_hitbox_value(AT_USTRONG, 1, HG_VISUAL_EFFECT, HFX_ABS_ZAP_DIR);

set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 2, HG_LIFETIME, 5);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW_CREATION_FRAME, 14);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_HITPAUSE, 20);
set_hitbox_value(AT_USTRONG, 2, HG_HITPAUSE_SCALING, 1.15);
set_hitbox_value(AT_USTRONG, 2, HG_DAMAGE, 12);
set_hitbox_value(AT_USTRONG, 2, HG_BASE_KNOCKBACK, 7.15);
set_hitbox_value(AT_USTRONG, 2, HG_KNOCKBACK_SCALING, 0.985);
set_hitbox_value(AT_USTRONG, 2, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_Y, -75);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_USTRONG, 2, HG_WIDTH, 70);
set_hitbox_value(AT_USTRONG, 2, HG_HEIGHT, 60);
set_hitbox_value(AT_USTRONG, 2, HG_ANGLE, 85);
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_USTRONG, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_USTRONG, 2, HG_HIT_SFX, asset_get("sfx_absa_whip3"));
set_hitbox_value(AT_USTRONG, 2, HG_VISUAL_EFFECT, HFX_ABS_SWEET_BIG);

set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_USTRONG, 3, HG_LIFETIME, 6);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW, 2);
set_hitbox_value(AT_USTRONG, 3, HG_WINDOW_CREATION_FRAME, 7);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_USTRONG, 3, HG_HITPAUSE_SCALING, 0.01);
set_hitbox_value(AT_USTRONG, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_USTRONG, 3, HG_BASE_KNOCKBACK, 5.2);
set_hitbox_value(AT_USTRONG, 3, HG_KNOCKBACK_SCALING, 0.05);
set_hitbox_value(AT_USTRONG, 3, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_X, 10);
set_hitbox_value(AT_USTRONG, 3, HG_WIDTH, 20);
set_hitbox_value(AT_USTRONG, 3, HG_HEIGHT, 60);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_USTRONG, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_USTRONG, 3, HG_TECHABLE, 3);
set_hitbox_value(AT_USTRONG, 3, HG_HIT_SFX, asset_get("sfx_absa_singlezap1"));
set_hitbox_value(AT_USTRONG, 3, HG_VISUAL_EFFECT, HFX_ABS_ZAP_DIR);
set_hitbox_value(AT_USTRONG, 3, HG_HITBOX_Y, -35);
set_hitbox_value(AT_USTRONG, 3, HG_SHAPE, 0);
set_hitbox_value(AT_USTRONG, 3, HG_WIDTH, 75);
set_hitbox_value(AT_USTRONG, 3, HG_ANGLE_FLIPPER, 4);
set_hitbox_value(AT_USTRONG, 3, HG_ANGLE, 45);
