set_attack_value(AT_EXTRA_2, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_2, AG_SPRITE, sprite_get("uspecial2"));
set_attack_value(AT_EXTRA_2, AG_NUM_WINDOWS, 4);
set_attack_value(AT_EXTRA_2, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_EXTRA_2, AG_AIR_SPRITE, sprite_get("uspecial2"));
set_attack_value(AT_EXTRA_2, AG_HURTBOX_SPRITE, sprite_get("uspecial_hurt"));

// startup
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_2, 1, AG_WINDOW_HAS_SFX, 1);


set_num_hitboxes(AT_EXTRA_2, 3);

//revert!
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_LIFETIME, 500);
set_hitbox_value(AT_EXTRA_2, 1, HG_WIDTH, 45);
set_hitbox_value(AT_EXTRA_2, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_2, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_2, 1, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_EXTRA_2, 1, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_EXTRA_2, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT_X_OFFSET, 32);
set_hitbox_value(AT_EXTRA_2, 1, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_SPRITE, sprite_get("go_gaga_and_die"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_MASK, sprite_get("go_gaga_and_die"));
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_2, 1, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_EXTRA_2, 1, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 1, HG_HIT_LOCKOUT, 5);
set_hitbox_value(AT_EXTRA_2, 1, HG_PROJECTILE_GROUND_FRICTION, 500);
set_hitbox_value(AT_EXTRA_2, 1, HG_HITSTUN_MULTIPLIER, 0.8);

set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_LIFETIME, 15);
set_hitbox_value(AT_EXTRA_2, 2, HG_WIDTH, 50);
set_hitbox_value(AT_EXTRA_2, 2, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_2, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_2, 2, HG_VISUAL_EFFECT, 3);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_SPRITE, sprite_get("blank_sheet"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_MASK, sprite_get("blank_sheet"));
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_SFX, asset_get("sfx_ell_steam_hit"));
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_2, 2, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_EXTRA_2, 2, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 2, HG_HIT_LOCKOUT, 12);

set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_LIFETIME, 12);
//
set_hitbox_value(AT_EXTRA_2, 3, HG_WIDTH, 65);
set_hitbox_value(AT_EXTRA_2, 3, HG_HEIGHT, 150);
set_hitbox_value(AT_EXTRA_2, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_2, 3, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_EXTRA_2, 3, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITPAUSE_SCALING, 1.2);
set_hitbox_value(AT_EXTRA_2, 3, HG_VISUAL_EFFECT, 148);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_SPRITE, sprite_get("blank_sheet"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_MASK, sprite_get("blank_sheet"));
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_SFX, asset_get("sfx_waterhit_heavy"));
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_2, 3, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_EXTRA_2, 3, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_2, 3, HG_HIT_LOCKOUT, 10);
