set_attack_value(AT_NSPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_NSPECIAL_2, AG_SPRITE, sprite_get("nspecial2"));
set_attack_value(AT_NSPECIAL_2, AG_NUM_WINDOWS, 4);
set_attack_value(AT_NSPECIAL_2, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_NSPECIAL_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_NSPECIAL_2, AG_AIR_SPRITE, sprite_get("nspecial2_air"));
set_attack_value(AT_NSPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("nspecial2_hurt"));
set_attack_value(AT_NSPECIAL_2, AG_HURTBOX_AIR_SPRITE, sprite_get("nspecial2_air_hurt"));

set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_LENGTH, 16);
set_window_value(AT_NSPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 1);

set_window_value(AT_NSPECIAL_2, 2, AG_WINDOW_LENGTH, 3);

set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_LENGTH, 9);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_SFX, asset_get("sfx_frog_dspecial_spit"));
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NSPECIAL_2, 3, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_LENGTH, 18);
set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_NSPECIAL_2, 4, AG_WINDOW_ANIM_FRAMES, 2);

set_window_value(AT_NSPECIAL_2, 5, AG_WINDOW_LENGTH, 20);
set_window_value(AT_NSPECIAL_2, 5, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_NSPECIAL_2, 5, AG_WINDOW_ANIM_FRAMES, 4);

set_num_hitboxes(AT_NSPECIAL_2, 3);

set_hitbox_value(AT_NSPECIAL_2, 1, HG_WINDOW, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_X, 26);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_WIDTH, 24);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HEIGHT, 24);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_ANGLE, 65);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HITPAUSE_SCALING, .1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_poison_hit_weak"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_SPRITE, sprite_get("sludge"));
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_DESTROY_EFFECT, poison_fx);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_VISUAL_EFFECT, stinghit);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HIT_PARTICLE_NUM, 1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_HSPEED, 6);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

set_hitbox_value(AT_NSPECIAL_2, 2, HG_WINDOW, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_LIFETIME, 5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_WIDTH, 70);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HEIGHT, 70);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_DAMAGE, 7);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_ANGLE, 90);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_EXTRA_HITPAUSE, 27);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HITPAUSE_SCALING, 0.1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_poison_hit_weak"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_SPRITE, sprite_get("empty"));
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_DESTROY_EFFECT, poison_fx);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_VISUAL_EFFECT, stinghit);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HIT_PARTICLE_NUM, 1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_HIT_LOCKOUT, 9);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);

set_hitbox_value(AT_NSPECIAL_2, 3, HG_WINDOW, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_LIFETIME, 5);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_WIDTH, 86);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HEIGHT, 86);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_DAMAGE, 8);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_ANGLE, 90);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_EXTRA_HITPAUSE, 34);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HITPAUSE_SCALING, 0.1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HIT_SFX, asset_get("sfx_poison_hit_weak"));
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_SPRITE, sprite_get("empty"));
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_DESTROY_EFFECT, poison_fx);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_VISUAL_EFFECT, stinghit);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HIT_PARTICLE_NUM, 1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_HIT_LOCKOUT, 11);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);

set_hitbox_value(AT_NSPECIAL_2, 4, HG_WINDOW, 0);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_LIFETIME, 5);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_WIDTH, 120);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HEIGHT, 120);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_DAMAGE, 12);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_ANGLE, 90);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_EXTRA_HITPAUSE, 42);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HITPAUSE_SCALING, 0.1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HIT_SFX, asset_get("sfx_poison_hit_weak"));
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_SPRITE, sprite_get("empty"));
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_DESTROY_EFFECT, poison_fx);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_VISUAL_EFFECT, stinghit);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HIT_PARTICLE_NUM, 1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_HIT_LOCKOUT, 12);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_NSPECIAL_2, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);