set_num_hitboxes(AT_EXTRA_1, 999);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 1 );
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_GROUP, -1 );
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 80);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 40);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_EXTRA_1, 1, HG_SHAPE, 2 );
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITPAUSE_SCALING, 0.1);
set_hitbox_value(AT_EXTRA_1, 1, HG_EFFECT, 19);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITSTUN_MULTIPLIER, 0.8);
set_hitbox_value(AT_EXTRA_1, 1, HG_GROUNDEDNESS, 1 );
set_hitbox_value(AT_EXTRA_1, 1, HG_THROWS_ROCK, 1 );
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT, 303 );
set_hitbox_value(AT_EXTRA_1, 1, HG_EXTRA_CAMERA_SHAKE, 1 );


set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 2 );
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1 );
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 80);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 40);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_EXTRA_1, 2, HG_SHAPE, 2 );
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, 0.2);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITPAUSE_SCALING, 0.1);
set_hitbox_value(AT_EXTRA_1, 2, HG_EFFECT, 626);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITSTUN_MULTIPLIER, 0.8);
set_hitbox_value(AT_EXTRA_1, 2, HG_GROUNDEDNESS, 1 );
set_hitbox_value(AT_EXTRA_1, 2, HG_THROWS_ROCK, 2 );
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT, 303 );
set_hitbox_value(AT_EXTRA_1, 2, HG_EXTRA_CAMERA_SHAKE, 1 );
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_MASK, -1);
