set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));
set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));
set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 3);

set_window_value(AT_FTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX_FRAME, 8);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));

set_window_value(AT_FTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED, 2);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 13);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FTILT, 5);

set_hitbox_value(AT_FTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X, 125);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 60);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_FTILT, 1, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 5);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 40);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FTILT, 1, HG_HITPAUSE_SCALING, .3);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FTILT, 1, HG_IGNORES_PROJECTILES, true);

set_hitbox_value(AT_FTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X, 70);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 80);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 55);
set_hitbox_value(AT_FTILT, 2, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 6);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 45);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, .85);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FTILT, 2, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, 302);
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_shovel_hit_heavy2"));
set_hitbox_value(AT_FTILT, 2, HG_IGNORES_PROJECTILES, true);

set_hitbox_value(AT_FTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_X, 65);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_Y, -75);
set_hitbox_value(AT_FTILT, 3, HG_WIDTH, 70);
set_hitbox_value(AT_FTILT, 3, HG_HEIGHT, 45);
set_hitbox_value(AT_FTILT, 3, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_FTILT, 3, HG_ANGLE, 50);
set_hitbox_value(AT_FTILT, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FTILT, 3, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_FTILT, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_FTILT, 3, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_FTILT, 3, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_FTILT, 3, HG_IGNORES_PROJECTILES, true);

//deflect hitbox (hold)
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FTILT, 4, HG_WINDOW, 20);
set_hitbox_value(AT_FTILT, 4, HG_LIFETIME, 999);
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_X, 115);
set_hitbox_value(AT_FTILT, 4, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 4, HG_WIDTH, 50);
set_hitbox_value(AT_FTILT, 4, HG_HEIGHT, 60);
set_hitbox_value(AT_FTILT, 4, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 4, HG_PRIORITY, 0);
set_hitbox_value(AT_FTILT, 4, HG_DAMAGE, 0);
set_hitbox_value(AT_FTILT, 4, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FTILT, 4, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_FTILT, 4, HG_IGNORES_PROJECTILES, true);

//deflect hitbox
set_hitbox_value(AT_FTILT, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FTILT, 5, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 5, HG_LIFETIME, 10);
set_hitbox_value(AT_FTILT, 5, HG_HITBOX_X, 120);
set_hitbox_value(AT_FTILT, 5, HG_HITBOX_Y, -35);
set_hitbox_value(AT_FTILT, 5, HG_WIDTH, 60);
set_hitbox_value(AT_FTILT, 5, HG_HEIGHT, 70);
set_hitbox_value(AT_FTILT, 5, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 5, HG_PRIORITY, 0);
set_hitbox_value(AT_FTILT, 5, HG_DAMAGE, 0);
set_hitbox_value(AT_FTILT, 5, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_PLASMA_SAFE, true);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_FTILT, 5, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_FTILT, 5, HG_IGNORES_PROJECTILES, true);