set_attack_value(AT_UAIR, AG_CATEGORY, 1);
set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_UAIR, AG_LANDING_LAG, 4);

set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 3);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED, -1);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 11);

set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 3);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAME_START, 3);

set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_UAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_UAIR, 6);

set_hitbox_value(AT_UAIR, 1, HG_MUNO_HITBOX_NAME, "Sourspot 1");
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, 30);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -44);
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 64);
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 84);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium3"));

set_hitbox_value(AT_UAIR, 2, HG_MUNO_HITBOX_NAME, "Sweetspot 1");
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -46);
set_hitbox_value(AT_UAIR, 2, HG_WIDTH, 48);
set_hitbox_value(AT_UAIR, 2, HG_HEIGHT, 54);
set_hitbox_value(AT_UAIR, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_UAIR, 2, HG_DAMAGE, 8);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_UAIR, 2, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_UAIR, 2, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_UAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));

set_hitbox_value(AT_UAIR, 3, HG_MUNO_HITBOX_NAME, "Sourspot 2");
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_UAIR, 3, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_X, 6);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_Y, -76);
set_hitbox_value(AT_UAIR, 3, HG_WIDTH, 100);
set_hitbox_value(AT_UAIR, 3, HG_HEIGHT, 64);
set_hitbox_value(AT_UAIR, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_UAIR, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_UAIR, 3, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UAIR, 3, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UAIR, 3, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_UAIR, 3, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 4, HG_MUNO_HITBOX_NAME, "Sweetspot 2");
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_UAIR, 4, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_Y, -64);
set_hitbox_value(AT_UAIR, 4, HG_WIDTH, 52);
set_hitbox_value(AT_UAIR, 4, HG_HEIGHT, 44);
set_hitbox_value(AT_UAIR, 4, HG_PRIORITY, 4);
set_hitbox_value(AT_UAIR, 4, HG_DAMAGE, 8);
set_hitbox_value(AT_UAIR, 4, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_UAIR, 4, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_UAIR, 4, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 4, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_UAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_UAIR, 4, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 5, HG_MUNO_HITBOX_NAME, "Sourspot 3");
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_UAIR, 5, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_X, 4);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_Y, -72);
set_hitbox_value(AT_UAIR, 5, HG_WIDTH, 100);
set_hitbox_value(AT_UAIR, 5, HG_HEIGHT, 60);
set_hitbox_value(AT_UAIR, 5, HG_PRIORITY, 3);
set_hitbox_value(AT_UAIR, 5, HG_DAMAGE, 5);
set_hitbox_value(AT_UAIR, 5, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 5, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UAIR, 5, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 5, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_UAIR, 5, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_UAIR, 5, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_UAIR, 6, HG_MUNO_HITBOX_NAME, "Sweetspot 3");
set_hitbox_value(AT_UAIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_UAIR, 6, HG_WINDOW, 2);
set_hitbox_value(AT_UAIR, 6, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_UAIR, 6, HG_LIFETIME, 1);
set_hitbox_value(AT_UAIR, 6, HG_HITBOX_X, 0);
set_hitbox_value(AT_UAIR, 6, HG_HITBOX_Y, -64);
set_hitbox_value(AT_UAIR, 6, HG_WIDTH, 52);
set_hitbox_value(AT_UAIR, 6, HG_HEIGHT, 44);
set_hitbox_value(AT_UAIR, 6, HG_PRIORITY, 4);
set_hitbox_value(AT_UAIR, 6, HG_DAMAGE, 8);
set_hitbox_value(AT_UAIR, 6, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 6, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_UAIR, 6, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_UAIR, 6, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_UAIR, 6, HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_UAIR, 6, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_UAIR, 6, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_UAIR, 6, HG_ANGLE_FLIPPER, 6);