set_attack_value(AT_USPECIAL_2, AG_CATEGORY, 2);
set_attack_value(AT_USPECIAL_2, AG_SPRITE, sprite_get("uspecial2"));
set_attack_value(AT_USPECIAL_2, AG_HURTBOX_SPRITE, sprite_get("uspecial2_hurt"));
set_attack_value(AT_USPECIAL_2, AG_OFF_LEDGE, 1);
set_attack_value(AT_USPECIAL_2, AG_LANDING_LAG, 10);
set_attack_value(AT_USPECIAL_2, AG_MUNO_ATTACK_USES_ROLES, 1);

set_attack_value(AT_USPECIAL_2, AG_NUM_WINDOWS, 3);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_LENGTH, 9);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.1);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.5);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_SFX, asset_get("sfx_bird_upspecial"));
set_window_value(AT_USPECIAL_2, 1, AG_WINDOW_SFX_FRAME, 8);
set_window_value(AT_USPECIAL_2, 1, AG_MUNO_WINDOW_ROLE, 1);

set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_LENGTH, 16);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_VSPEED, -8);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_USPECIAL_2, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.07);
set_window_value(AT_USPECIAL_2, 2, AG_MUNO_WINDOW_ROLE, 1);

set_window_value(AT_USPECIAL_2, 3, AG_WINDOW_LENGTH, 28);
set_window_value(AT_USPECIAL_2, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_USPECIAL_2, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_USPECIAL_2, 3, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_USPECIAL_2, 3, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USPECIAL_2, 3, AG_MUNO_WINDOW_ROLE, 3);

var appear_frame = get_window_value(AT_USPECIAL_2, 1, AG_WINDOW_LENGTH) + get_window_value(AT_USPECIAL_2, 2, AG_WINDOW_LENGTH);
var attack_cancel_frame = get_window_value(AT_USPECIAL_2, 1, AG_WINDOW_LENGTH) + get_window_value(AT_USPECIAL_2, 2, AG_WINDOW_LENGTH);
var cancel_hitstun =  floor(get_window_value(AT_USPECIAL_2, 3, AG_WINDOW_LENGTH) / 2);
var cancel_no_hitstun =  floor(get_window_value(AT_USPECIAL_2, 3, AG_WINDOW_LENGTH) / 1.5);

set_attack_value(AT_USPECIAL_2, AG_MUNO_ATTACK_MISC_ADD, "Attack and jump cancelable frame " + string(attack_cancel_frame + cancel_no_hitstun) + " onwards (" + string(attack_cancel_frame + cancel_hitstun) + " onwards if marked opponent is in hitstun)");


set_num_hitboxes(AT_USPECIAL_2, 2);

set_hitbox_value(AT_USPECIAL_2, 1, HG_MUNO_HITBOX_NAME, "Smoke (Air)");
set_hitbox_value(AT_USPECIAL_2, 1, HG_MUNO_HITBOX_ACTIVE, string(3 * 2));
set_hitbox_value(AT_USPECIAL_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL_2, 1, HG_WINDOW, 2);
set_hitbox_value(AT_USPECIAL_2, 1, HG_WINDOW_CREATION_FRAME, get_window_value(AT_USPECIAL_2, 2, AG_WINDOW_LENGTH) - 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_LIFETIME, 24);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_USPECIAL_2, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_USPECIAL_2, 1, HG_ANGLE, 70);
set_hitbox_value(AT_USPECIAL_2, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USPECIAL_2, 1, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_USPECIAL_2, 1, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HITSTUN_MULTIPLIER, 0.5);
set_hitbox_value(AT_USPECIAL_2, 1, HG_VISUAL_EFFECT, hfx_leaf);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_forsburn_reappear_hit"));
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_SPRITE, sprite_get("hfx_mamizou_smoke"));
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_MASK, sprite_get("hfx_mamizou_smoke_mask"));
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_ANIM_SPEED, 0.333);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);

set_hitbox_value(AT_USPECIAL_2, 2, HG_MUNO_HITBOX_NAME, "Smoke (Teleport)");
set_hitbox_value(AT_USPECIAL_2, 2, HG_MUNO_HITBOX_ACTIVE, string(3 * 2));
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL_2, 2, HG_WINDOW, 3);
set_hitbox_value(AT_USPECIAL_2, 2, HG_LIFETIME, 24);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITBOX_Y, -32);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PRIORITY, 5);
set_hitbox_value(AT_USPECIAL_2, 2, HG_DAMAGE, 0);
set_hitbox_value(AT_USPECIAL_2, 2, HG_ANGLE, 70);
set_hitbox_value(AT_USPECIAL_2, 2, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_USPECIAL_2, 2, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_USPECIAL_2, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(AT_USPECIAL_2, 2, HG_EXTRA_HITPAUSE, 6);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITSTUN_MULTIPLIER, 0.5);
set_hitbox_value(AT_USPECIAL_2, 2, HG_EFFECT, 9);
set_hitbox_value(AT_USPECIAL_2, 2, HG_VISUAL_EFFECT, hfx_leaf);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_forsburn_reappear_hit"));
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_SPRITE, sprite_get("hfx_mamizou_smoke"));
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_MASK, sprite_get("hfx_mamizou_smoke_mask"));
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, 0.333);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
