//Attack Scripts
AT_JAB_2 = AT_EXTRA_1;
AT_FTILT_2 = AT_EXTRA_2;
AT_UTILT_2 = AT_EXTRA_3;
AT_DTILT_2 = AT_TAUNT_2;
AT_DATTACK_2 = AT_USPECIAL_GROUND;
AT_NAIR_2 = AT_FTHROW;
AT_FAIR_2 = AT_UTHROW;
AT_BAIR_2 = AT_DTHROW;
AT_UAIR_2 = AT_NTHROW;
AT_DAIR_2 = AT_NSPECIAL_2;
AT_TRICK = AT_FSPECIAL_2;
AT_TRICK_2 = AT_USPECIAL_2;
AT_TRICK_AIR = AT_NSPECIAL_AIR;
AT_TRICK_2_AIR = AT_FSPECIAL_AIR;
AT_QUICKSILVER = AT_DSPECIAL_AIR;
AT_VICERAL = AT_DSPECIAL_2;