set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));
set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));
set_attack_value(AT_FTILT, AG_CATEGORY, 0);
set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 3);

set_window_value(AT_FTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);

set_window_value(AT_FTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 18);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED, 2);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_SFX, sound_get("ftilt"));

set_window_value(AT_FTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes (AT_FTILT, 3);

set_hitbox_value(AT_FTILT, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X, 20);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -14);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 60);
set_hitbox_value(AT_FTILT, 1, HG_TECHABLE, 1);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 40);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_abyss_hazard_hit"));
set_hitbox_value(AT_FTILT, 1, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 1, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 30);
set_hitbox_value(AT_FTILT, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 10);

set_hitbox_value(AT_FTILT, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X, 30);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -14);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 40);
set_hitbox_value(AT_FTILT, 2, HG_TECHABLE, 1);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 40);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_abyss_hazard_hit"));
set_hitbox_value(AT_FTILT, 2, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 2, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 170);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 1);

set_hitbox_value(AT_FTILT, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FTILT, 3, HG_LIFETIME, 9);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_X, 20);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_Y, -14);
set_hitbox_value(AT_FTILT, 3, HG_WIDTH, 60);
set_hitbox_value(AT_FTILT, 3, HG_TECHABLE, 1);
set_hitbox_value(AT_FTILT, 3, HG_HEIGHT, 40);
set_hitbox_value(AT_FTILT, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT, 302);
set_hitbox_value(AT_FTILT, 3, HG_HIT_SFX, asset_get("sfx_frog_ustrong"));
set_hitbox_value(AT_FTILT, 3, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 3, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_FTILT, 3, HG_ANGLE, 60);
set_hitbox_value(AT_FTILT, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_FTILT, 3, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_FTILT, 3, HG_BASE_HITPAUSE, 10);