set_attack_value(AT_UAIR, AG_CATEGORY, 1);
set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"));
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_UAIR, AG_LANDING_LAG, 5);
set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 1);
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair_hurt"));

set_window_value(AT_UAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 31);
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED, -9);
set_window_value(AT_UAIR, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, asset_get("sfx_bird_nspecial"));

set_num_hitboxes (AT_UAIR, 5);

set_hitbox_value(AT_UAIR, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 1);
set_hitbox_value(AT_UAIR, 1, HG_WINDOW_CREATION_FRAME, 10);
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 80);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_SPRITE, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_MASK, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, -40);
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -100);
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT, 194);
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_ell_utilt_hit"));
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_VSPEED, -.1);
set_hitbox_value(AT_UAIR, 1, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_GRAVITY, -.11);
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_DESTROY_EFFECT, 194);
set_hitbox_value(AT_UAIR, 1, HG_FINAL_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_UAIR, 1, HG_HIT_LOCKOUT, 7);
set_hitbox_value(AT_UAIR, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);

set_hitbox_value(AT_UAIR, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 1);
set_hitbox_value(AT_UAIR, 2, HG_HIT_LOCKOUT, 7);
set_hitbox_value(AT_UAIR, 2, HG_WINDOW_CREATION_FRAME, 11);
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 80);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_SPRITE, sprite_get ("blank"));
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_MASK, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 2, HG_PRIORITY, 6);
set_hitbox_value(AT_UAIR, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, -40);
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -100);
set_hitbox_value(AT_UAIR, 2, HG_VISUAL_EFFECT, 194);
set_hitbox_value(AT_UAIR, 2, HG_HIT_SFX, asset_get("sfx_ell_utilt_hit"));
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_VSPEED, -.1);
set_hitbox_value(AT_UAIR, 2, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_GRAVITY, -.11);
set_hitbox_value(AT_UAIR, 2, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 2, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_UAIR, 2, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_UAIR, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_UAIR, 2, HG_FINAL_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_DESTROY_EFFECT, 194);
set_hitbox_value(AT_UAIR, 2, HG_HIT_LOCKOUT, 4);
set_hitbox_value(AT_UAIR, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);

set_hitbox_value(AT_UAIR, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW, 1);
set_hitbox_value(AT_UAIR, 3, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_UAIR, 3, HG_LIFETIME, 80);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_SPRITE, sprite_get ("blank"));
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_MASK, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 3, HG_PRIORITY, 6);
set_hitbox_value(AT_UAIR, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_X, -40);
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_Y, -100);
set_hitbox_value(AT_UAIR, 3, HG_VISUAL_EFFECT, 194);
set_hitbox_value(AT_UAIR, 3, HG_HIT_SFX, asset_get("sfx_ell_utilt_hit"));
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_VSPEED, -.1);
set_hitbox_value(AT_UAIR, 3, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_GRAVITY, -.11);
set_hitbox_value(AT_UAIR, 3, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 3, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UAIR, 3, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_UAIR, 3, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_UAIR, 3, HG_FINAL_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_DESTROY_EFFECT, 194);
set_hitbox_value(AT_UAIR, 3, HG_HIT_LOCKOUT, 7);
set_hitbox_value(AT_UAIR, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);

set_hitbox_value(AT_UAIR, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_GROUP, 4);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW, 1);
set_hitbox_value(AT_UAIR, 4, HG_WINDOW_CREATION_FRAME, 13);
set_hitbox_value(AT_UAIR, 4, HG_LIFETIME, 80);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_SPRITE, sprite_get ("blank"));
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_MASK, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 4, HG_PRIORITY, 6);
set_hitbox_value(AT_UAIR, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_X, -40);
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_Y, -100);
set_hitbox_value(AT_UAIR, 4, HG_VISUAL_EFFECT, 194);
set_hitbox_value(AT_UAIR, 4, HG_HIT_SFX, asset_get("sfx_ell_utilt_hit"));
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_VSPEED, -.1);
set_hitbox_value(AT_UAIR, 4, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_GRAVITY, -.11);
set_hitbox_value(AT_UAIR, 4, HG_ANGLE, 90);
set_hitbox_value(AT_UAIR, 4, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_UAIR, 4, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_UAIR, 4, HG_BASE_HITPAUSE, 9);
set_hitbox_value(AT_UAIR, 4, HG_FINAL_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_DESTROY_EFFECT, 194);
set_hitbox_value(AT_UAIR, 4, HG_HIT_LOCKOUT, 1);
set_hitbox_value(AT_UAIR, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);

set_hitbox_value(AT_UAIR, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_GROUP, 5);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW, 1);
set_hitbox_value(AT_UAIR, 5, HG_WINDOW_CREATION_FRAME, 14);
set_hitbox_value(AT_UAIR, 5, HG_LIFETIME, 80);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_SPRITE, sprite_get ("blank"));
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_MASK, sprite_get ("uair_proj"));
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_ANIM_SPEED, .3);
set_hitbox_value(AT_UAIR, 5, HG_PRIORITY, 6);
set_hitbox_value(AT_UAIR, 5, HG_DAMAGE, 2);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_X, -40);
set_hitbox_value(AT_UAIR, 5, HG_HITBOX_Y, -100);
set_hitbox_value(AT_UAIR, 5, HG_VISUAL_EFFECT, 194);
set_hitbox_value(AT_UAIR, 5, HG_HIT_SFX, asset_get("sfx_ell_utilt_hit"));
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_VSPEED, -.1);
set_hitbox_value(AT_UAIR, 5, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_GRAVITY, -.11);
set_hitbox_value(AT_UAIR, 5, HG_ANGLE, 80);
set_hitbox_value(AT_UAIR, 5, HG_TECHABLE, 0);
set_hitbox_value(AT_UAIR, 5, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_UAIR, 5, HG_KNOCKBACK_SCALING, .3);
set_hitbox_value(AT_UAIR, 5, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_UAIR, 5, HG_FINAL_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_UAIR, 5, HG_PROJECTILE_DESTROY_EFFECT, 194);
set_hitbox_value(AT_UAIR, 5, HG_HIT_LOCKOUT, 1);