set_attack_value(AT_USPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_USPECIAL, AG_SPRITE, sprite_get("uspecial"));
set_attack_value(AT_USPECIAL, AG_NUM_WINDOWS, 3);
set_attack_value(AT_USPECIAL, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_USPECIAL, AG_OFF_LEDGE, 1);
set_attack_value(AT_USPECIAL, AG_HURTBOX_SPRITE, sprite_get("uspecial_hurt"));

set_window_value(AT_USPECIAL, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_VSPEED, -5);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_USPECIAL, 1, AG_WINDOW_SFX, sound_get("barrel_enter"));

set_window_value(AT_USPECIAL, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_LENGTH, 1);
set_window_value(AT_USPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 1);
//set_window_value(AT_USPECIAL, 2, AG_WINDOW_HAS_SFX, 1);
//set_window_value(AT_USPECIAL, 2, AG_WINDOW_SFX, sound_get("barrel_enter"));

set_window_value(AT_USPECIAL, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_LENGTH, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_USPECIAL, 3, AG_WINDOW_VSPEED, 0);


set_num_hitboxes(AT_USPECIAL, 1);

set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 1, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 1, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 1, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 1, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 1, HG_ANGLE, 90);
set_hitbox_value(AT_USPECIAL, 1, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_KNOCKBACK, 14);
set_hitbox_value(AT_USPECIAL, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 1, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 1, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 1, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 1, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 2, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 2, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 2, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 2, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 2, HG_ANGLE, 60);
set_hitbox_value(AT_USPECIAL, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 2, HG_BASE_KNOCKBACK, 14);
set_hitbox_value(AT_USPECIAL, 2, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 2, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 2, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 2, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 3, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 3, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 3, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 3, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 3, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 3, HG_ANGLE, 30);
set_hitbox_value(AT_USPECIAL, 3, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 3, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_USPECIAL, 3, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 3, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 3, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 3, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 4, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 4, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 4, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 4, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 4, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 4, HG_ANGLE, 340);
set_hitbox_value(AT_USPECIAL, 4, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 4, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USPECIAL, 4, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 4, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 4, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 4, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 5, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 5, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 5, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 5, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 5, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 5, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 5, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 5, HG_ANGLE, 270);
set_hitbox_value(AT_USPECIAL, 5, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 5, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USPECIAL, 5, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 5, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 5, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 5, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 6, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 6, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 6, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 6, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 6, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 6, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 6, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 6, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 6, HG_ANGLE, 200);
set_hitbox_value(AT_USPECIAL, 6, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 6, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USPECIAL, 6, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 6, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 6, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 6, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 7, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 7, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 7, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 7, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 7, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 7, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 7, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 7, HG_ANGLE, 150);
set_hitbox_value(AT_USPECIAL, 7, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 7, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(AT_USPECIAL, 7, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 7, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 7, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 7, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL, 8, HG_WINDOW, 9);
set_hitbox_value(AT_USPECIAL, 8, HG_LIFETIME, 9999);
set_hitbox_value(AT_USPECIAL, 8, HG_PROJECTILE_SPRITE, sprite_get("nothing"));
set_hitbox_value(AT_USPECIAL, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL, 8, HG_HITBOX_X, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_HITBOX_Y, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_WIDTH, 45);
set_hitbox_value(AT_USPECIAL, 8, HG_HEIGHT, 45);
set_hitbox_value(AT_USPECIAL, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL, 8, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL, 8, HG_ANGLE, 120);
set_hitbox_value(AT_USPECIAL, 8, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_USPECIAL, 8, HG_BASE_KNOCKBACK, 14);
set_hitbox_value(AT_USPECIAL, 8, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_VISUAL_EFFECT, 162);
set_hitbox_value(AT_USPECIAL, 8, HG_HIT_SFX, sound_get("barrel_shot"));
set_hitbox_value(AT_USPECIAL, 8, HG_PROJECTILE_IS_TRANSCENDENT, false);
set_hitbox_value(AT_USPECIAL, 8, HG_PROJECTILE_PLASMA_SAFE, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_DRIFT_MULTIPLIER, 0);

set_hitbox_value(AT_USPECIAL, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_EXTRA_HITPAUSE, 0);

set_hitbox_value(AT_USPECIAL, 1, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 4, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 5, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 6, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 7, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_USPECIAL, 8, HG_PROJECTILE_PARRY_STUN, 0);