set_attack_value(AT_DTILT, AG_SPRITE, sprite_get("dtilt"));
set_attack_value(AT_DTILT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DTILT, AG_HURTBOX_SPRITE, sprite_get("dtilt_hurt"));

set_window_value(AT_DTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_LENGTH, 5);
set_window_value(AT_DTILT, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX, asset_get("sfx_blow_medium3"));
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX_FRAME, 4);

set_window_value(AT_DTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DTILT, 2, AG_WINDOW_HSPEED, 3);
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_DTILT, 2, AG_WINDOW_HAS_WHIFFLAG, 1);

set_window_value(AT_DTILT, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DTILT, 3, AG_WINDOW_LENGTH, 8);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_DTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_DTILT,2);

set_hitbox_value(AT_DTILT, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 1, HG_LIFETIME, 6);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_X, 24);
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_Y, -22);
set_hitbox_value(AT_DTILT, 1, HG_WIDTH, 62);
set_hitbox_value(AT_DTILT, 1, HG_HEIGHT, 48);
set_hitbox_value(AT_DTILT, 1, HG_SHAPE, 2);
set_hitbox_value(AT_DTILT, 1, HG_PRIORITY, 3);
set_hitbox_value(AT_DTILT, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_DTILT, 1, HG_ANGLE, 87);
set_hitbox_value(AT_DTILT, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DTILT, 1, HG_KNOCKBACK_SCALING, .1);
set_hitbox_value(AT_DTILT, 1, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DTILT, 1, HG_HITPAUSE_SCALING, .4);
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_DTILT, 1, HG_HITSTUN_MULTIPLIER, 0.8);
set_hitbox_value(AT_DTILT, 1, HG_VISUAL_EFFECT, 303);

set_hitbox_value(AT_DTILT, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 2, HG_WINDOW, 20);
set_hitbox_value(AT_DTILT, 2, HG_LIFETIME, 100);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_X, 42);
set_hitbox_value(AT_DTILT, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_DTILT, 2, HG_WIDTH, 78);
set_hitbox_value(AT_DTILT, 2, HG_HEIGHT, 30);
set_hitbox_value(AT_DTILT, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_DTILT, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_DTILT, 2, HG_ANGLE, 90);
set_hitbox_value(AT_DTILT, 2, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 2, HG_KNOCKBACK_SCALING, .1);
set_hitbox_value(AT_DTILT, 2, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DTILT, 2, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_DTILT, 2, HG_HIT_SFX, sound_get("cheese"));
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_SPRITE, sprite_get("cheese"));
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 2, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_DTILT, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_DTILT, 2, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_DTILT, 2, HG_PROJECTILE_UNBASHABLE, true);

set_hitbox_value(AT_DTILT, 3,HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 3,HG_WINDOW, 4);
set_hitbox_value(AT_DTILT, 3,HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_DTILT, 3,HG_LIFETIME, 99999);
set_hitbox_value(AT_DTILT, 3,HG_HITBOX_X, 6);
set_hitbox_value(AT_DTILT, 3,HG_HITBOX_Y, -6);
set_hitbox_value(AT_DTILT, 3,HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_SPRITE, sprite_get("gun2"));
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_AIR_FRICTION, 0.1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_GROUND_FRICTION, 0.1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_GRAVITY, 0.3);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_ANIM_SPEED, 0.15);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_DESTROY_EFFECT, 304);
set_hitbox_value(AT_DTILT, 3,HG_WIDTH, 30);
set_hitbox_value(AT_DTILT, 3,HG_HEIGHT, 20);
set_hitbox_value(AT_DTILT, 3,HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 3,HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 3,HG_DAMAGE, 10);
set_hitbox_value(AT_DTILT, 3,HG_ANGLE, 90);
set_hitbox_value(AT_DTILT, 3,HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DTILT, 3,HG_BASE_KNOCKBACK, 11);
set_hitbox_value(AT_DTILT, 3,HG_KNOCKBACK_SCALING, 0.9);
set_hitbox_value(AT_DTILT, 3,HG_BASE_HITPAUSE, 11);
set_hitbox_value(AT_DTILT, 3,HG_HITPAUSE_SCALING, 0.9);
set_hitbox_value(AT_DTILT, 3,HG_HIT_SFX, sound_get("exp2"));
set_hitbox_value(AT_DTILT, 3,HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 3,HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_DTILT, 3,HG_VISUAL_EFFECT, exp2);

set_hitbox_value(AT_DTILT, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 4, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DTILT, 4, HG_LIFETIME, 120);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_X, 40);
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_Y, 20);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_SPRITE, sprite_get("dairs1"));
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_HSPEED, 9);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_VSPEED, 9);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_DESTROY_EFFECT, 305);
set_hitbox_value(AT_DTILT, 4, HG_WIDTH, 50);
set_hitbox_value(AT_DTILT, 4, HG_HEIGHT, 50);
set_hitbox_value(AT_DTILT, 4, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_DTILT, 4, HG_DAMAGE, 9);
set_hitbox_value(AT_DTILT, 4, HG_ANGLE, 65);
set_hitbox_value(AT_DTILT, 4, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DTILT, 4, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 4, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_DTILT, 4, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 4, HG_HIT_SFX, sound_get("exp2"));
set_hitbox_value(AT_DTILT, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 4, HG_VISUAL_EFFECT, exp2);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 4, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_DTILT, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 5, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 5, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DTILT, 5, HG_LIFETIME, 300);
set_hitbox_value(AT_DTILT, 5, HG_HITBOX_X, 40);
set_hitbox_value(AT_DTILT, 5, HG_HITBOX_Y, 20);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_SPRITE, sprite_get("Kat"));
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_VSPEED, -6);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_DESTROY_EFFECT, 305);
set_hitbox_value(AT_DTILT, 5, HG_WIDTH, 0);
set_hitbox_value(AT_DTILT, 5, HG_HEIGHT, 0);
set_hitbox_value(AT_DTILT, 5, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 5, HG_PRIORITY, 0);
set_hitbox_value(AT_DTILT, 5, HG_DAMAGE, 9);
set_hitbox_value(AT_DTILT, 5, HG_ANGLE, 65);
set_hitbox_value(AT_DTILT, 5, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DTILT, 5, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 5, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 5, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_DTILT, 5, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 5, HG_HIT_SFX, sound_get("exp2"));
set_hitbox_value(AT_DTILT, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 5, HG_VISUAL_EFFECT, exp2);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 5, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_DTILT, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 6, HG_WINDOW, 2);
set_hitbox_value(AT_DTILT, 6, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DTILT, 6, HG_LIFETIME, 200);
set_hitbox_value(AT_DTILT, 6, HG_HITBOX_X, 40);
set_hitbox_value(AT_DTILT, 6, HG_HITBOX_Y, 20);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_SPRITE, sprite_get("Oboa"));
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_ANIM_SPEED, 0.6);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_DESTROY_EFFECT, 305);
set_hitbox_value(AT_DTILT, 6, HG_WIDTH, 0);
set_hitbox_value(AT_DTILT, 6, HG_HEIGHT, 0);
set_hitbox_value(AT_DTILT, 6, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 6, HG_PRIORITY, 0);
set_hitbox_value(AT_DTILT, 6, HG_DAMAGE, 9);
set_hitbox_value(AT_DTILT, 6, HG_ANGLE, 65);
set_hitbox_value(AT_DTILT, 6, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DTILT, 6, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 6, HG_KNOCKBACK_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 6, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_DTILT, 6, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_DTILT, 6, HG_HIT_SFX, sound_get("exp2"));
set_hitbox_value(AT_DTILT, 6, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 6, HG_VISUAL_EFFECT, exp2);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 6, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_DTILT, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 7, HG_WINDOW, 7);
set_hitbox_value(AT_DTILT, 7, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DTILT, 7, HG_LIFETIME, 60);
set_hitbox_value(AT_DTILT, 7, HG_HITBOX_X, 0);
set_hitbox_value(AT_DTILT, 7, HG_HITBOX_Y, -18);
set_hitbox_value(AT_DTILT, 7, HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_SPRITE, sprite_get("dattacks1"));
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_AIR_FRICTION, 0.00);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_HSPEED, 50);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_GRAVITY, 0.0);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_DESTROY_EFFECT, 303);
set_hitbox_value(AT_DTILT, 7, HG_WIDTH, 90);
set_hitbox_value(AT_DTILT, 7, HG_HEIGHT, 50);
set_hitbox_value(AT_DTILT, 7, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 7, HG_DAMAGE, 8);
set_hitbox_value(AT_DTILT, 7, HG_ANGLE, 55);
set_hitbox_value(AT_DTILT, 7, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DTILT, 7, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 7, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_DTILT, 7, HG_BASE_HITPAUSE, 14);
set_hitbox_value(AT_DTILT, 7, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_DTILT, 7, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_DTILT, 7, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 7, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 7, HG_PROJECTILE_DOES_NOT_REFLECT, true);

set_hitbox_value(AT_DTILT, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DTILT, 8, HG_WINDOW, 7);
set_hitbox_value(AT_DTILT, 8, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DTILT, 8, HG_LIFETIME, 60);
set_hitbox_value(AT_DTILT, 8, HG_HITBOX_X, 0);
set_hitbox_value(AT_DTILT, 8, HG_HITBOX_Y, -18);
set_hitbox_value(AT_DTILT, 8, HG_PRIORITY, 1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_SPRITE, sprite_get("dattacks1"));
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_AIR_FRICTION, 0.00);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_HSPEED, 50);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_GRAVITY, 0.0);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_DESTROY_EFFECT, 303);
set_hitbox_value(AT_DTILT, 8, HG_WIDTH, 90);
set_hitbox_value(AT_DTILT, 8, HG_HEIGHT, 50);
set_hitbox_value(AT_DTILT, 8, HG_SHAPE, 0);
set_hitbox_value(AT_DTILT, 8, HG_DAMAGE, 8);
set_hitbox_value(AT_DTILT, 8, HG_ANGLE, 125);
set_hitbox_value(AT_DTILT, 8, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DTILT, 8, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_DTILT, 8, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_DTILT, 8, HG_BASE_HITPAUSE, 14);
set_hitbox_value(AT_DTILT, 8, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_DTILT, 8, HG_HIT_SFX, sound_get("slice"));
set_hitbox_value(AT_DTILT, 8, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_PARRY_STUN, 1);
set_hitbox_value(AT_DTILT, 8, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DTILT, 8, HG_PROJECTILE_DOES_NOT_REFLECT, true);