set_attack_value(AT_FTILT, AG_SPRITE, sprite_get("ftilt"));
set_attack_value(AT_FTILT, AG_HURTBOX_SPRITE, sprite_get("ftilt_hurt"));
set_attack_value(AT_FTILT, AG_NUM_WINDOWS, 9);
set_attack_value(AT_FTILT, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_FTILT, AG_OFF_LEDGE, 0);
set_attack_value(AT_FTILT, AG_CATEGORY, 0);

set_window_value(AT_FTILT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"));
set_window_value(AT_FTILT, 1, AG_WINDOW_SFX_FRAME, 0);

set_window_value(AT_FTILT, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED, 7);
set_window_value(AT_FTILT, 2, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FTILT, 3, AG_WINDOW_TYPE, 3);
set_window_value(AT_FTILT, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FTILT, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_CANCEL_TYPE, 1);
set_window_value(AT_FTILT, 3, AG_WINDOW_CANCEL_FRAME, 3);
set_window_value(AT_FTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_window_value(AT_FTILT, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_FTILT, 4, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FTILT, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_FTILT, 4, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_FTILT, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 4, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 4, AG_WINDOW_SFX, asset_get("sfx_ori_dtilt_perform"));
set_window_value(AT_FTILT, 4, AG_WINDOW_SFX_FRAME, 0);

set_window_value(AT_FTILT, 5, AG_WINDOW_TYPE, 2);
set_window_value(AT_FTILT, 5, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 5, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 5, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_FTILT, 5, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 5, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 5, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 5, AG_WINDOW_HITPAUSE_FRAME, 0);
set_window_value(AT_FTILT, 5, AG_WINDOW_HSPEED, 4);
set_window_value(AT_FTILT, 5, AG_WINDOW_HSPEED_TYPE, 2);

set_window_value(AT_FTILT, 6, AG_WINDOW_TYPE, 3);
set_window_value(AT_FTILT, 6, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FTILT, 6, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 6, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_FTILT, 6, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 6, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 6, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 6, AG_WINDOW_CANCEL_TYPE, 1);
set_window_value(AT_FTILT, 6, AG_WINDOW_CANCEL_FRAME, 1);

set_window_value(AT_FTILT, 7, AG_WINDOW_TYPE, 3);
set_window_value(AT_FTILT, 7, AG_WINDOW_LENGTH, 6);
set_window_value(AT_FTILT, 7, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FTILT, 7, AG_WINDOW_ANIM_FRAME_START, 13);
set_window_value(AT_FTILT, 7, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 7, AG_WINDOW_CUSTOM_AIR_FRICTION, .2);
set_window_value(AT_FTILT, 7, AG_WINDOW_CUSTOM_GROUND_FRICTION, .2);
set_window_value(AT_FTILT, 7, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FTILT, 7, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_light1"));
set_window_value(AT_FTILT, 7, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_FTILT, 8, AG_WINDOW_TYPE, 3);
set_window_value(AT_FTILT, 8, AG_WINDOW_LENGTH, 9);
set_window_value(AT_FTILT, 8, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 8, AG_WINDOW_ANIM_FRAME_START, 15);
set_window_value(AT_FTILT, 8, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 8, AG_WINDOW_HSPEED, 4);
set_window_value(AT_FTILT, 8, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_FTILT, 8, AG_WINDOW_CUSTOM_AIR_FRICTION, .1);
set_window_value(AT_FTILT, 8, AG_WINDOW_CUSTOM_GROUND_FRICTION, .1);

set_window_value(AT_FTILT, 9, AG_WINDOW_TYPE, 2);
set_window_value(AT_FTILT, 9, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FTILT, 9, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FTILT, 9, AG_WINDOW_ANIM_FRAME_START, 18);
set_window_value(AT_FTILT, 9, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_FTILT, 9, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);
set_window_value(AT_FTILT, 9, AG_WINDOW_CUSTOM_GROUND_FRICTION, 1);
set_window_value(AT_FTILT, 9, AG_WINDOW_HITPAUSE_FRAME, 0);
set_window_value(AT_FTILT, 9, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FTILT, 3);
set_hitbox_value(AT_FTILT, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FTILT, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_X, 48);
set_hitbox_value(AT_FTILT, 1, HG_HITBOX_Y, -25);
set_hitbox_value(AT_FTILT, 1, HG_WIDTH, 70);
set_hitbox_value(AT_FTILT, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_FTILT, 1, HG_SHAPE, 0);
set_hitbox_value(AT_FTILT, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_FTILT, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE, 78);
set_hitbox_value(AT_FTILT, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_FTILT, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FTILT, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_FTILT, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_FTILT, 1, HG_VISUAL_EFFECT_Y_OFFSET, 10);
set_hitbox_value(AT_FTILT, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_FTILT, 1, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 1, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(AT_FTILT, 1, HG_ANGLE_FLIPPER, 1);
set_hitbox_value(AT_FTILT, 1, HG_TECHABLE, 1);

set_hitbox_value(AT_FTILT, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW, 5);
set_hitbox_value(AT_FTILT, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 2, HG_LIFETIME, 6);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_X, 60);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_Y, -27);
set_hitbox_value(AT_FTILT, 2, HG_WIDTH, 80);
set_hitbox_value(AT_FTILT, 2, HG_HEIGHT, 50);
set_hitbox_value(AT_FTILT, 2, HG_SHAPE, 2);
set_hitbox_value(AT_FTILT, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_FTILT, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_FTILT, 2, HG_ANGLE, 78);
set_hitbox_value(AT_FTILT, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FTILT, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FTILT, 2, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_FTILT, 2, HG_HITSTUN_MULTIPLIER, 1.2);
set_hitbox_value(AT_FTILT, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT, 302);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_FTILT, 2, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FTILT, 2, HG_ANGLE_FLIPPER, 1);
set_hitbox_value(AT_FTILT, 2, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FTILT, 2, HG_SDI_MULTIPLIER, 1.3);
set_hitbox_value(AT_FTILT, 2, HG_TECHABLE, 1);

set_hitbox_value(AT_FTILT, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW, 8);
set_hitbox_value(AT_FTILT, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_FTILT, 3, HG_LIFETIME, 9);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_X, 48);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_Y, -36);
set_hitbox_value(AT_FTILT, 3, HG_WIDTH, 70);
set_hitbox_value(AT_FTILT, 3, HG_HEIGHT, 64);
set_hitbox_value(AT_FTILT, 3, HG_SHAPE, 1);
set_hitbox_value(AT_FTILT, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_FTILT, 3, HG_DAMAGE, 6);
set_hitbox_value(AT_FTILT, 3, HG_ANGLE, 57);
set_hitbox_value(AT_FTILT, 3, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_FTILT, 3, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_FTILT, 3, HG_BASE_HITPAUSE, 12);
set_hitbox_value(AT_FTILT, 3, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_FTILT, 3, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_FTILT, 3, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
set_hitbox_value(AT_FTILT, 3, HG_EXTRA_CAMERA_SHAKE, 2);
set_hitbox_value(AT_FTILT, 3, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_FTILT, 3, HG_HITBOX_GROUP, 2);