set_attack_value(AT_TAUNT, AG_SPRITE, sprite_get("taunt"));
set_attack_value(AT_TAUNT, AG_NUM_WINDOWS, 3);
set_attack_value(AT_TAUNT, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_TAUNT, AG_OFF_LEDGE, 1);
set_attack_value(AT_TAUNT, AG_HURTBOX_SPRITE, asset_get("idle_hurt"));


set_window_value(AT_TAUNT, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_TAUNT, 1, AG_WINDOW_LENGTH, 18);
set_window_value(AT_TAUNT, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_TAUNT, 1, AG_WINDOW_HAS_SFX, 1);

set_window_value(AT_TAUNT, 2, AG_WINDOW_TYPE, 2);
set_window_value(AT_TAUNT, 2, AG_WINDOW_LENGTH, 30);
set_window_value(AT_TAUNT, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_TAUNT, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_TAUNT, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_TAUNT, 2, AG_WINDOW_SFX, sound_get("click"));

set_window_value(AT_TAUNT, 3, AG_WINDOW_TYPE, 3);
set_window_value(AT_TAUNT, 3, AG_WINDOW_LENGTH, 35);
set_window_value(AT_TAUNT, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_TAUNT, 3, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_TAUNT, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_TAUNT, 3, AG_WINDOW_SFX, sound_get("swipe5"));
set_window_value(AT_TAUNT, 3, AG_WINDOW_SFX_FRAME, 13);

set_num_hitboxes(AT_TAUNT, 4);

set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_TAUNT, 1, HG_WINDOW, 7);
set_hitbox_value(AT_TAUNT, 1, HG_LIFETIME, 20);
set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_TAUNT, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_TAUNT, 1, HG_WIDTH, 64);
set_hitbox_value(AT_TAUNT, 1, HG_HEIGHT, 64);
set_hitbox_value(AT_TAUNT, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_SPRITE, sprite_get("star1"));
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_PLASMA_SAFE, 1);
set_hitbox_value(AT_TAUNT, 1, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_TAUNT, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_TAUNT, 2, HG_WINDOW, 7);
set_hitbox_value(AT_TAUNT, 2, HG_LIFETIME, 20);
set_hitbox_value(AT_TAUNT, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_TAUNT, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_TAUNT, 2, HG_WIDTH, 64);
set_hitbox_value(AT_TAUNT, 2, HG_HEIGHT, 64);
set_hitbox_value(AT_TAUNT, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_SPRITE, sprite_get("star2"));
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_PLASMA_SAFE, 1);
set_hitbox_value(AT_TAUNT, 2, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_TAUNT, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_TAUNT, 3, HG_WINDOW, 7);
set_hitbox_value(AT_TAUNT, 3, HG_LIFETIME, 20);
set_hitbox_value(AT_TAUNT, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_TAUNT, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_TAUNT, 3, HG_WIDTH, 64);
set_hitbox_value(AT_TAUNT, 3, HG_HEIGHT, 64);
set_hitbox_value(AT_TAUNT, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_SPRITE, sprite_get("star3"));
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_ANIM_SPEED, 0.4);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 0);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_PLASMA_SAFE, 1);
set_hitbox_value(AT_TAUNT, 3, HG_PROJECTILE_UNBASHABLE, 1);

set_hitbox_value(AT_TAUNT, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_TAUNT, 4, HG_WINDOW, 7);
set_hitbox_value(AT_TAUNT, 4, HG_LIFETIME, 999);
set_hitbox_value(AT_TAUNT, 4, HG_HITBOX_X, -2);
set_hitbox_value(AT_TAUNT, 4, HG_HITBOX_Y, 3);
set_hitbox_value(AT_TAUNT, 4, HG_WIDTH, 11);
set_hitbox_value(AT_TAUNT, 4, HG_HEIGHT, 18);
set_hitbox_value(AT_TAUNT, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_TAUNT, 4, HG_DAMAGE, 4);
set_hitbox_value(AT_TAUNT, 4, HG_ANGLE, 270);
set_hitbox_value(AT_TAUNT, 4, HG_SHAPE, 2);
set_hitbox_value(AT_TAUNT, 4, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_TAUNT, 4, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_TAUNT, 4, HG_BASE_HITPAUSE, 20);
set_hitbox_value(AT_TAUNT, 4, HG_HITPAUSE_SCALING, .7);
set_hitbox_value(AT_TAUNT, 4, HG_HIT_SFX, sound_get("cut"));
set_hitbox_value(AT_TAUNT, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_TAUNT, 4, HG_HIT_LOCKOUT, 14);
