sprite_change_offset("idle", 32, 47);
sprite_change_offset("crouch", 32, 47);
sprite_change_offset("walk", 32, 47);
sprite_change_offset("walkturn", 32, 47);
sprite_change_offset("dash", 32, 47);
sprite_change_offset("dashstart", 32, 47);
sprite_change_offset("dashstop", 32, 47);
sprite_change_offset("dashturn", 32, 47);

sprite_change_offset("jumpstart", 32, 47);
sprite_change_offset("jump", 32, 47);
sprite_change_offset("doublejump", 32, 47);
sprite_change_offset("walljump", 32, 47);
sprite_change_offset("pratfall", 16, 47);
sprite_change_offset("land", 32, 47);
sprite_change_offset("landinglag", 32, 47);

sprite_change_offset("parry", 32, 47);
sprite_change_offset("roll_forward", 32, 47);
sprite_change_offset("roll_backward", 32, 47);
sprite_change_offset("airdodge", 32, 47);
sprite_change_offset("waveland", 32, 47);
sprite_change_offset("tech", 32, 47);

sprite_change_offset("hurt", 32, 47);
sprite_change_offset("bighurt", 32, 47);
sprite_change_offset("hurtground", 32, 47);
sprite_change_offset("bouncehurt", 32, 47);
sprite_change_offset("uphurt", 32, 47);
sprite_change_offset("downhurt", 32, 47);
sprite_change_offset("spinhurt", 32, 47);

sprite_change_offset("jab", 32, 47, true);
sprite_change_offset("dattack", 48, 47, true);
sprite_change_offset("ftilt", 32, 47, true);
sprite_change_offset("dtilt", 48, 31, true);
sprite_change_offset("utilt", 48, 63, true);
sprite_change_offset("nair", 48, 47, true);
sprite_change_offset("fair", 48, 47, true);
sprite_change_offset("bair", 48, 63, true);
sprite_change_offset("uair", 32, 63, true);
sprite_change_offset("dair", 32, 63, true);
sprite_change_offset("fstrong_1", 32, 47, true);
sprite_change_offset("ustrong_1", 32, 79, true);
sprite_change_offset("dstrong_1", 48, 47, true);
sprite_change_offset("fstrong_2", 32, 47, true);
sprite_change_offset("ustrong_2", 32, 63, true);
sprite_change_offset("dstrong_2", 48, 47, true);
sprite_change_offset("fstrong_3", 32, 47, true);
sprite_change_offset("ustrong_3", 32, 79, true);
sprite_change_offset("dstrong_3", 32, 47, true);
sprite_change_offset("fstrong_4", 32, 47, true);
sprite_change_offset("ustrong_4", 32, 63, true);
sprite_change_offset("dstrong_4", 48, 47, true);
sprite_change_offset("fstrong_5", 48, 63, true);
sprite_change_offset("ustrong_5", 64, 63, true);
sprite_change_offset("dstrong_5", 64, 47, true);
sprite_change_offset("nspecial_1", 32, 47, true);
sprite_change_offset("nspecial_2", 32, 47, true);
sprite_change_offset("nspecial_3", 32, 47, true);
sprite_change_offset("fspecial_1", 48, 47, true);
sprite_change_offset("fspecial_2", 32, 47, true);
sprite_change_offset("fspecial_3", 32, 47, true);
sprite_change_offset("fspecial_3_air", 32, 47, true);
sprite_change_offset("uspecial_1", 48, 47, true);
sprite_change_offset("uspecial_1_ground", 48, 47, true);
sprite_change_offset("uspecial_2", 32, 47, true);
sprite_change_offset("uspecial_3", 32, 47, true);
sprite_change_offset("dspecial", 32, 47);
sprite_change_offset("taunt", 32, 63);

sprite_change_offset("plat", 32, 31);
sprite_change_offset("plat_b", 32, 31);

sprite_change_offset("dspecial_chest", 48, 94);
sprite_change_offset("therese", 64, 126);
sprite_change_offset("marsha", 64, 126);
sprite_change_offset("lucius", 32, 126);
sprite_change_offset("yanfly", 32, 94);
sprite_change_offset("dspecial_chest_mask", 48, 94);
sprite_change_offset("hud_exp_player", 12, 0);
sprite_change_offset("mamizou", 16, 31);

sprite_change_offset("fx_magic_small1", 96, 96);
sprite_change_offset("fx_magic_medium", 96, 96);
sprite_change_offset("fx_magic_ground", 64, 96);
sprite_change_offset("fx_arrow", 96, 16);
sprite_change_offset("fx_arrow_mask", 96, 16);
sprite_change_offset("fx_arrow_u", 32, 64);
sprite_change_offset("fx_arrow_u_mask", 32, 64);
sprite_change_offset("fx_slashproj", 64, 36);
sprite_change_offset("fx_slashproj2", 48, 32);
sprite_change_offset("fx_slashproj_e", 96, 64);
sprite_change_offset("fx_fireproj1", 48, 16);
sprite_change_offset("fx_fireproj2", 48, 32);
sprite_change_offset("fx_fireproj2_e", 48, 94);
sprite_change_offset("fx_fireproj3", 80, 64);
sprite_change_offset("fx_fireproj3_e", 96, 160);
sprite_change_offset("fx_iceproj1", 16, 16);
sprite_change_offset("fx_iceproj1_e", 64, 94);
sprite_change_offset("fx_darkproj1", 80, 80);
sprite_change_offset("fx_levelup", 64, 128);
sprite_change_offset("fx_levelup_fg", 64, 128);
sprite_change_offset("fx_sparkle", 16, 16);
sprite_change_offset("fx_windproj1a", 96, 64);
sprite_change_offset("fx_windproj1b", 96, 64);
sprite_change_offset("fx_crit", 192, 192);
sprite_change_collision_mask("fx_arrow_mask", 1, 0,0,0,0,0,0);
sprite_change_collision_mask("fx_arrow_u_mask", 1, 0,0,0,0,0,0);
sprite_change_collision_mask("fx_fireproj2_e", 1, 0,0,0,0,0,0);
sprite_change_collision_mask("fx_fireproj3_e", 1, 0,0,0,0,0,0);