set_attack_value(AT_EXTRA_1, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("Wateridle"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 3);
set_attack_value(AT_EXTRA_1, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_EXTRA_1, AG_OFF_LEDGE, 1);
set_attack_value(AT_EXTRA_1, AG_AIR_SPRITE, sprite_get("Wateridle"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("Wateridle"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_AIR_SPRITE, sprite_get("Wateridle"));

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 5);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .1);

set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX, asset_get("sfx_kragg_throw"));
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .1);

set_window_value(AT_EXTRA_1, 3, AG_WINDOW_LENGTH, 3);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, .5);;

set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 30);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_HSPEED, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_VSPEED, -3);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 40);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_HSPEED, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_VSPEED, -1);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 60);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 3, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 3, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_VSPEED, -0.3);

set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_LIFETIME, 60);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 4, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 4, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 4, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITSTUN_MULTIPLIER, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_HSPEED, -0.3);
set_hitbox_value(AT_EXTRA_1, 4, HG_PROJECTILE_VSPEED, -0.8);

set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_LIFETIME, 45);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 5, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 5, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 5, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITSTUN_MULTIPLIER, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_HSPEED, 0.5);
set_hitbox_value(AT_EXTRA_1, 5, HG_PROJECTILE_VSPEED, -0.1);

set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_LIFETIME, 80);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 6, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 6, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 6, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 6, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 6, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITSTUN_MULTIPLIER, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_HSPEED, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_PROJECTILE_VSPEED, -0.1);

set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_LIFETIME, 60);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_X, 10);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_Y, -45);
set_hitbox_value(AT_EXTRA_1, 7, HG_WIDTH, 17);
set_hitbox_value(AT_EXTRA_1, 7, HG_HEIGHT, 9);
set_hitbox_value(AT_EXTRA_1, 7, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_KNOCKBACK_SCALING, .25);
set_hitbox_value(AT_EXTRA_1, 7, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 7, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_ANGLE, 50);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT, 6);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT_Y_OFFSET, -16);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITSTUN_MULTIPLIER, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_SPRITE, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_MASK, sprite_get("Uteki bubble"));
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_ANIM_SPEED, .2);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_HSPEED, 3.3);
set_hitbox_value(AT_EXTRA_1, 7, HG_PROJECTILE_VSPEED, -2);