set_attack_value(49, AG_CATEGORY, 2);
set_attack_value(49, AG_SPRITE, sprite_get("final_smash"));
set_attack_value(49, AG_NUM_WINDOWS, 4);
set_attack_value(49, AG_HAS_LANDING_LAG, 1);
set_attack_value(49, AG_LANDING_LAG, 4);
set_attack_value(49, AG_HURTBOX_SPRITE, sprite_get("final_smash_hurt"));

set_window_value(49, 1, AG_WINDOW_LENGTH, 32);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(49, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_SFX, sound_get("sfx_charge_2"));
set_window_value(49, 1, AG_WINDOW_SFX_FRAME, 24);

set_window_value(49, 2, AG_WINDOW_LENGTH, 24);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(49, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 2, AG_WINDOW_SFX, asset_get("sfx_boss_laser"));
set_window_value(49, 2, AG_WINDOW_SFX_FRAME, 23);

set_window_value(49, 3, AG_WINDOW_LENGTH, 34);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 14);
set_window_value(49, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(49, 4, AG_WINDOW_LENGTH, 35);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 20);
set_window_value(49, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_HSPEED_TYPE, 1);

set_num_hitboxes(49,4);

set_hitbox_value(49, 1, HG_TECHABLE, 1);
set_hitbox_value(49, 2, HG_TECHABLE, 1);
set_hitbox_value(49, 3, HG_TECHABLE, 1);
set_hitbox_value(49, 4, HG_TECHABLE, 1);

set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 1, HG_WINDOW, 3);
//set_hitbox_value(49, 3, HG_WINDOW_CREATION_FRAME, 32);
set_hitbox_value(49, 1, HG_LIFETIME, 6);
set_hitbox_value(49, 1, HG_HITBOX_Y, -50);
set_hitbox_value(49, 1, HG_HITBOX_X, 300);
set_hitbox_value(49, 1, HG_HIT_LOCKOUT, 2);
set_hitbox_value(49, 1, HG_WIDTH, 380);
set_hitbox_value(49, 1, HG_HEIGHT, 150);
set_hitbox_value(49, 1, HG_SHAPE, 1);
set_hitbox_value(49, 1, HG_PRIORITY, 2);
set_hitbox_value(49, 1, HG_DAMAGE, 2);
set_hitbox_value(49, 1, HG_ANGLE, 10);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 3);
//set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 1, HG_HIT_SFX, sound_get("sfx_hit_kirby"));

set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 2, HG_WINDOW, 3);
set_hitbox_value(49, 2, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(49, 2, HG_LIFETIME, 6);
set_hitbox_value(49, 2, HG_HITBOX_Y, -50);
set_hitbox_value(49, 2, HG_HITBOX_X, 500);
set_hitbox_value(49, 2, HG_HIT_LOCKOUT, 2);
set_hitbox_value(49, 2, HG_WIDTH, 600);
set_hitbox_value(49, 2, HG_HEIGHT, 150);
set_hitbox_value(49, 2, HG_SHAPE, 1);
set_hitbox_value(49, 2, HG_PRIORITY, 2);
set_hitbox_value(49, 2, HG_DAMAGE, 2);
set_hitbox_value(49, 2, HG_ANGLE, 10);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 3);
//set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 2, HG_HIT_SFX, sound_get("sfx_hit_kirby"));


set_hitbox_value(49, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 3, HG_HITBOX_GROUP, -1);
//set_hitbox_value(49, 3, HG_WINDOW, 3);
//set_hitbox_value(49, 3, HG_WINDOW_CREATION_FRAME, 32);
set_hitbox_value(49, 3, HG_LIFETIME, 2);
set_hitbox_value(49, 3, HG_HITBOX_Y, -50);
set_hitbox_value(49, 3, HG_HITBOX_X, 640);
set_hitbox_value(49, 3, HG_HIT_LOCKOUT, 2);
set_hitbox_value(49, 3, HG_WIDTH, 1000);
set_hitbox_value(49, 3, HG_HEIGHT, 150);
set_hitbox_value(49, 3, HG_SHAPE, 1);
set_hitbox_value(49, 3, HG_PRIORITY, 2);
set_hitbox_value(49, 3, HG_DAMAGE, 1);
set_hitbox_value(49, 3, HG_ANGLE, 10);
set_hitbox_value(49, 3, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 3, HG_BASE_HITPAUSE, 3);
//set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 3, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 3, HG_HIT_SFX, sound_get("sfx_hit_kirby"));

set_hitbox_value(49, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 4, HG_WINDOW, 3);
set_hitbox_value(49, 4, HG_WINDOW_CREATION_FRAME, 30);
set_hitbox_value(49, 4, HG_LIFETIME, 4);
set_hitbox_value(49, 4, HG_HITBOX_Y, -50);
set_hitbox_value(49, 4, HG_HITBOX_X, 640);
set_hitbox_value(49, 4, HG_WIDTH, 1000);
set_hitbox_value(49, 4, HG_HEIGHT, 150);
set_hitbox_value(49, 4, HG_SHAPE, 1);
set_hitbox_value(49, 4, HG_PRIORITY, 2);
set_hitbox_value(49, 4, HG_DAMAGE, 15);
set_hitbox_value(49, 4, HG_ANGLE, 45);
set_hitbox_value(49, 4, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 4, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(49, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(49, 4, HG_HITPAUSE_SCALING, .5);
//set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 4, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 4, HG_HIT_SFX, sound_get("sfx_hit_magic_heavy"));