set_attack_value(AT_FSTRONG_2, AG_SPRITE, sprite_get("fstrong_smol"));
set_attack_value(AT_FSTRONG_2, AG_NUM_WINDOWS, 4);
set_attack_value(AT_FSTRONG_2, AG_HAS_LANDING_LAG, 3);
set_attack_value(AT_FSTRONG_2, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_FSTRONG_2, AG_HURTBOX_SPRITE, sprite_get("fstrong_hurt"));

set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_LENGTH, 33);
set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_ANIM_FRAMES, 11);
//set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
//set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .1);
set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_SFX_FRAME, 18);
set_window_value(AT_FSTRONG_2, 1, AG_WINDOW_SFX, sound_get("sfx_usword_charge"));

set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_SFX_FRAME, 9);
set_window_value(AT_FSTRONG_2, 2, AG_WINDOW_SFX, sound_get("sfx_usword_swing"));

set_window_value(AT_FSTRONG_2, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_FSTRONG_2, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FSTRONG_2, 3, AG_WINDOW_ANIM_FRAME_START, 14);

set_window_value(AT_FSTRONG_2, 4, AG_WINDOW_LENGTH, 25);
set_window_value(AT_FSTRONG_2, 4, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_FSTRONG_2, 4, AG_WINDOW_ANIM_FRAME_START, 17);
set_window_value(AT_FSTRONG_2, 4, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FSTRONG_2, 5);

set_hitbox_value(AT_FSTRONG_2, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG_2, 1, HG_WINDOW, 3);
set_hitbox_value(AT_FSTRONG_2, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HITBOX_X, -20);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HITBOX_Y, -172);
set_hitbox_value(AT_FSTRONG_2, 1, HG_SHAPE, 2);
set_hitbox_value(AT_FSTRONG_2, 1, HG_WIDTH, 272);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HEIGHT, 130);
set_hitbox_value(AT_FSTRONG_2, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_FSTRONG_2, 1, HG_DAMAGE, 9);
set_hitbox_value(AT_FSTRONG_2, 1, HG_ANGLE, 80);
set_hitbox_value(AT_FSTRONG_2, 1, HG_BASE_KNOCKBACK, 8.5);
set_hitbox_value(AT_FSTRONG_2, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSTRONG_2, 1, HG_BASE_HITPAUSE, 15);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG_2, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSTRONG_2, 1, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_FSTRONG_2, 1, HG_HIT_SFX, sound_get("sfx_hit_sharp"));
set_hitbox_value(AT_FSTRONG_2, 1, HG_HIT_LOCKOUT, 10);
set_hitbox_value(AT_FSTRONG_2, 1, HG_EXTENDED_PARRY_STUN, 1);

set_hitbox_value(AT_FSTRONG_2, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG_2, 2, HG_WINDOW, 3);
set_hitbox_value(AT_FSTRONG_2, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_FSTRONG_2, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG_2, 2, HG_SHAPE, 2);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HITBOX_X, 140);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HITBOX_Y, -74);
set_hitbox_value(AT_FSTRONG_2, 2, HG_WIDTH, 150);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HEIGHT, 180);
set_hitbox_value(AT_FSTRONG_2, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_FSTRONG_2, 2, HG_DAMAGE, 12);
set_hitbox_value(AT_FSTRONG_2, 2, HG_ANGLE, 361);
set_hitbox_value(AT_FSTRONG_2, 2, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_FSTRONG_2, 2, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSTRONG_2, 2, HG_BASE_HITPAUSE, 15);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG_2, 2, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSTRONG_2, 2, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_FSTRONG_2, 2, HG_HIT_SFX, sound_get("sfx_hit_sharp"));
set_hitbox_value(AT_FSTRONG_2, 2, HG_HIT_LOCKOUT, 10);
set_hitbox_value(AT_FSTRONG_2, 2, HG_EXTENDED_PARRY_STUN, 1);

set_hitbox_value(AT_FSTRONG_2, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FSTRONG_2, 3, HG_WINDOW, 3);
set_hitbox_value(AT_FSTRONG_2, 3, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_FSTRONG_2, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_FSTRONG_2, 3, HG_SHAPE, 2);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HITBOX_X, 140);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HITBOX_Y, 8);
set_hitbox_value(AT_FSTRONG_2, 3, HG_WIDTH, 140);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HEIGHT, 120);
set_hitbox_value(AT_FSTRONG_2, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_FSTRONG_2, 3, HG_DAMAGE, 8);
set_hitbox_value(AT_FSTRONG_2, 3, HG_ANGLE, 60);
set_hitbox_value(AT_FSTRONG_2, 3, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_FSTRONG_2, 3, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_FSTRONG_2, 3, HG_BASE_HITPAUSE, 15);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSTRONG_2, 3, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_FSTRONG_2, 3, HG_VISUAL_EFFECT_Y_OFFSET, -10);
set_hitbox_value(AT_FSTRONG_2, 3, HG_HIT_SFX, sound_get("sfx_hit_sharp"));
set_hitbox_value(AT_FSTRONG_2, 3, HG_HIT_LOCKOUT, 10);
set_hitbox_value(AT_FSTRONG_2, 3, HG_EXTENDED_PARRY_STUN, 1);