set_attack_value(43, AG_CATEGORY, 2);
set_attack_value(43, AG_SPRITE, sprite_get("greatsword_slash"));
set_attack_value(43, AG_AIR_SPRITE, sprite_get("greatsword_slash"));
set_attack_value(43, AG_HURTBOX_SPRITE, -1/*sprite_get("hurtbox")*/);

set_attack_value(43, AG_NUM_WINDOWS, 5);

set_window_value(43, 1, AG_WINDOW_LENGTH, 6);
set_window_value(43, 1, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(43, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(43, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, .120);

set_window_value(43, 2, AG_WINDOW_LENGTH, 3);
set_window_value(43, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(43, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(43, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(43, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, .120);

set_window_value(43, 3, AG_WINDOW_LENGTH, 8);
set_window_value(43, 3, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(43, 3, AG_WINDOW_ANIM_FRAME_START, 4);
//set_window_value(43, 3, AG_WINDOW_VSPEED, -1);
//set_window_value(43, 3, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(43, 4, AG_WINDOW_LENGTH, 12);
set_window_value(43, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(43, 4, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(43, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(43, 4, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));
set_window_value(43, 4, AG_WINDOW_SFX_FRAME, 1);

set_window_value(43, 5, AG_WINDOW_LENGTH, 10);
set_window_value(43, 5, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(43, 5, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(43, 5, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(43, 5);

set_hitbox_value(43, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(43, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(43, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(43, 1, HG_WINDOW, 4);
set_hitbox_value(43, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(43, 1, HG_LIFETIME, 6);
set_hitbox_value(43, 1, HG_HITBOX_X, 54);
set_hitbox_value(43, 1, HG_HITBOX_Y, -18);
set_hitbox_value(43, 1, HG_SHAPE, 1);
set_hitbox_value(43, 1, HG_WIDTH, 90);
set_hitbox_value(43, 1, HG_HEIGHT, 40);
set_hitbox_value(43, 1, HG_PRIORITY, 1);
set_hitbox_value(43, 1, HG_DAMAGE, 6);
set_hitbox_value(43, 1, HG_ANGLE, 269);
set_hitbox_value(43, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(43, 1, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(43, 1, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(43, 1, HG_BASE_HITPAUSE, 10);
set_hitbox_value(43, 1, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(43, 1, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(43, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));

set_hitbox_value(43, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(43, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(43, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(43, 2, HG_WINDOW, 4);
set_hitbox_value(43, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(43, 2, HG_LIFETIME, 3);
set_hitbox_value(43, 2, HG_HITBOX_X, 58);
set_hitbox_value(43, 2, HG_HITBOX_Y, -54);
set_hitbox_value(43, 2, HG_SHAPE, 0);
set_hitbox_value(43, 2, HG_WIDTH, 70);
set_hitbox_value(43, 2, HG_HEIGHT, 70);
set_hitbox_value(43, 2, HG_PRIORITY, 1);
set_hitbox_value(43, 2, HG_DAMAGE, 6);
set_hitbox_value(43, 2, HG_ANGLE, 65);
set_hitbox_value(43, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(43, 2, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(43, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(43, 2, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(43, 2, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(43, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));

set_hitbox_value(43, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(43, 3, HG_HITBOX_GROUP, 1);
set_hitbox_value(43, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(43, 3, HG_WINDOW, 4);
set_hitbox_value(43, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(43, 3, HG_LIFETIME, 3);
set_hitbox_value(43, 3, HG_HITBOX_X, 14);
set_hitbox_value(43, 3, HG_HITBOX_Y, -88);
set_hitbox_value(43, 3, HG_SHAPE, 0);
set_hitbox_value(43, 3, HG_WIDTH, 75);
set_hitbox_value(43, 3, HG_HEIGHT, 60);
set_hitbox_value(43, 3, HG_PRIORITY, 1);
set_hitbox_value(43, 3, HG_DAMAGE, 6);
set_hitbox_value(43, 3, HG_ANGLE, 65);
set_hitbox_value(43, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(43, 3, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(43, 3, HG_BASE_HITPAUSE, 10);
set_hitbox_value(43, 3, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(43, 3, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(43, 3, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));

set_hitbox_value(43, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(43, 4, HG_HITBOX_GROUP, 1);
set_hitbox_value(43, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(43, 4, HG_WINDOW, 4);
set_hitbox_value(43, 4, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(43, 4, HG_LIFETIME, 3);
set_hitbox_value(43, 4, HG_HITBOX_X, -28);
set_hitbox_value(43, 4, HG_HITBOX_Y, -68);
set_hitbox_value(43, 4, HG_SHAPE, 0);
set_hitbox_value(43, 4, HG_WIDTH, 50);
set_hitbox_value(43, 4, HG_HEIGHT, 50);
set_hitbox_value(43, 4, HG_PRIORITY, 1);
set_hitbox_value(43, 4, HG_DAMAGE, 6);
set_hitbox_value(43, 4, HG_ANGLE, 65);
set_hitbox_value(43, 4, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(43, 4, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(43, 4, HG_BASE_HITPAUSE, 10);
set_hitbox_value(43, 4, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(43, 4, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(43, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));


set_hitbox_value(43, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(43, 5, HG_HITBOX_GROUP, 1);
set_hitbox_value(43, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(43, 5, HG_WINDOW, 4);
set_hitbox_value(43, 5, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(43, 5, HG_LIFETIME, 6);
set_hitbox_value(43, 5, HG_HITBOX_X, 54);
set_hitbox_value(43, 5, HG_HITBOX_Y, -18);
set_hitbox_value(43, 5, HG_SHAPE, 1);
set_hitbox_value(43, 5, HG_WIDTH, 90);
set_hitbox_value(43, 5, HG_HEIGHT, 40);
set_hitbox_value(43, 5, HG_PRIORITY, 1);
set_hitbox_value(43, 5, HG_DAMAGE, 4);
set_hitbox_value(43, 5, HG_ANGLE, 65);
set_hitbox_value(43, 5, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(43, 5, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(43, 5, HG_BASE_HITPAUSE, 10);
set_hitbox_value(43, 5, HG_HITSTUN_MULTIPLIER, 1.1);
set_hitbox_value(43, 5, HG_EXTENDED_PARRY_STUN, 1);
set_hitbox_value(43, 5, HG_HIT_SFX, asset_get("sfx_blow_medium3"));
