set_attack_value(AT_EXTRA_1, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("nspecial_3"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 6);
set_attack_value(AT_EXTRA_1, AG_HAS_LANDING_LAG, 4);
set_attack_value(AT_EXTRA_1, AG_AIR_SPRITE, sprite_get("nspecial_3"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("nspecial_3_hurt"));
set_attack_value(AT_EXTRA_1, AG_USES_CUSTOM_GRAVITY, 1);

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 12);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_CUSTOM_AIR_FRICTION, 2);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.8);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_CUSTOM_GRAVITY, 0.1);

set_window_value(AT_EXTRA_1, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, 18);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX, sound_get("charged-shot"));
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 2);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.8);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_CUSTOM_GRAVITY, 0.2);

set_window_value(AT_EXTRA_1, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_LENGTH, 12);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_SFX, sound_get("charged-shot"));
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 2);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.8);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_CUSTOM_GRAVITY, 0.2);

set_window_value(AT_EXTRA_1, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_LENGTH, 12);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_SFX, asset_get("sfx_clairen_swing_strong"));
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 2);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.8);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_CUSTOM_GRAVITY, 0.2);

set_window_value(AT_EXTRA_1, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_LENGTH, 15);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAME_START, 15);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.8);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_CUSTOM_GRAVITY, 0.2);

set_num_hitboxes(AT_EXTRA_1, 3);
//Uncharged shot
set_hitbox_value(AT_EXTRA_1, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 90);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 18);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -20);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_SPRITE, sprite_get("nspecial_proj3"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_MASK, sprite_get("nspecial_proj3"));
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_HSPEED, 16);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 80);
set_hitbox_value(AT_EXTRA_1, 1, HG_EFFECT, 11);
set_hitbox_value(AT_EXTRA_1, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, sound_get("lv1shothit"));

set_hitbox_value(AT_EXTRA_1, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 16);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 90);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 18);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -20);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_SPRITE, sprite_get("nspecial_proj3"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_MASK, sprite_get("nspecial_proj3"));
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_HSPEED, 16);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 55);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 80);
set_hitbox_value(AT_EXTRA_1, 2, HG_EFFECT, 11);
set_hitbox_value(AT_EXTRA_1, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, sound_get("lv1shothit"));

set_hitbox_value(AT_EXTRA_1, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 4);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 90);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, 18);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -20);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_SPRITE, sprite_get("nspecial_proj4"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_MASK, sprite_get("nspecial_proj4"));
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_HSPEED, 16);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 8);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 8);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 45);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_1, 3, HG_KNOCKBACK_SCALING, 0.9);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_HITPAUSE, 15);
set_hitbox_value(AT_EXTRA_1, 3, HG_EFFECT, 11);
set_hitbox_value(AT_EXTRA_1, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, sound_get("lv1shothit"));