set_attack_value(AT_NAIR, AG_CATEGORY, 1);
set_attack_value(AT_NAIR, AG_SPRITE, sprite_get("jump"));
set_attack_value(AT_NAIR, AG_NUM_WINDOWS, 5);
set_attack_value(AT_NAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_NAIR, AG_LANDING_LAG, 5);
set_attack_value(AT_NAIR, AG_HURTBOX_SPRITE, sprite_get("idle_hurt"));

set_window_value(AT_NAIR, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 1, AG_WINDOW_LENGTH, 18); //12 -> 20
set_window_value(AT_NAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_NAIR, 1, AG_WINDOW_ANIM_FRAME_START, 5);

//shot 1
set_window_value(AT_NAIR, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_NAIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NAIR, 2, AG_WINDOW_SFX, sound_get("backfire2"));
set_window_value(AT_NAIR, 2, AG_WINDOW_HSPEED, 0);

set_window_value(AT_NAIR, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_NAIR, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_NAIR, 3, AG_WINDOW_SFX, sound_get("cannonball2"));

set_window_value(AT_NAIR, 4, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_LENGTH, 5);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 4, AG_WINDOW_ANIM_FRAME_START, 1);

set_window_value(AT_NAIR, 5, AG_WINDOW_TYPE, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_LENGTH, 4);
set_window_value(AT_NAIR, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_NAIR, 5, AG_WINDOW_ANIM_FRAME_START, 3);

set_num_hitboxes(AT_NAIR, 9);

//forward
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 1, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 1, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 1, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 1, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 1, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 1, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 1, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 1, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 1, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_ANIM_SPEED, .95);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_HSPEED, 7);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

set_hitbox_value(AT_NAIR, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 2, HG_LIFETIME, 25);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_X, 20);
set_hitbox_value(AT_NAIR, 2, HG_HITBOX_Y, -90);
set_hitbox_value(AT_NAIR, 2, HG_WIDTH, 40);
set_hitbox_value(AT_NAIR, 2, HG_HEIGHT, 40);
set_hitbox_value(AT_NAIR, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 2, HG_DAMAGE, 0);
set_hitbox_value(AT_NAIR, 2, HG_ANGLE, 0);
set_hitbox_value(AT_NAIR, 2, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 2, HG_PROJECTILE_SPRITE, sprite_get("cloud"));
set_hitbox_value(AT_NAIR, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 2, HG_PROJECTILE_ANIM_SPEED, 0.5);
set_hitbox_value(AT_NAIR, 2, HG_PROJECTILE_HSPEED, 0);

//forward up
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 3, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 3, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 3, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 3, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 3, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 3, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 3, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 3, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 3, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 3, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 3, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_ANIM_SPEED, .90);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_VSPEED, -5);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//up
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 4, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 4, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 4, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 4, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 4, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 4, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 4, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 4, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 4, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 4, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 4, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 4, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_ANIM_SPEED, .80);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_VSPEED, -7);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//left up
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 5, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 5, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 5, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 5, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 5, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 5, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 5, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 5, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 5, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 5, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 5, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 5, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 5, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_ANIM_SPEED, .70);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_HSPEED, -5);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_VSPEED, -5);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 5, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//left
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 6, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 6, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 6, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 6, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 6, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 6, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 6, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 6, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 6, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 6, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 6, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 6, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 6, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 6, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_ANIM_SPEED, .60);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_HSPEED, -7);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 6, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//left down
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 7, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 7, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 7, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 7, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 7, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 7, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 7, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 7, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 7, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 7, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 7, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 7, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 7, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 7, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_ANIM_SPEED, .90);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_HSPEED, -5);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_VSPEED, 5);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 7, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//down
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 8, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 8, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 8, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 8, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 8, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 8, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 8, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 8, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 8, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 8, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 8, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 8, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 8, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 8, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_ANIM_SPEED, .80);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_VSPEED, 7);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);

//down forward
set_hitbox_value(AT_NAIR, 9, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_NAIR, 9, HG_WINDOW, 2);
set_hitbox_value(AT_NAIR, 9, HG_LIFETIME, 10);
set_hitbox_value(AT_NAIR, 9, HG_HITBOX_X, 30);
set_hitbox_value(AT_NAIR, 9, HG_HITBOX_Y, -27);
set_hitbox_value(AT_NAIR, 9, HG_WIDTH, 80);
set_hitbox_value(AT_NAIR, 9, HG_HEIGHT, 80);
set_hitbox_value(AT_NAIR, 9, HG_PRIORITY, 4);
set_hitbox_value(AT_NAIR, 9, HG_DAMAGE, 2);
set_hitbox_value(AT_NAIR, 9, HG_ANGLE, 60);
set_hitbox_value(AT_NAIR, 9, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_NAIR, 9, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_NAIR, 9, HG_BASE_HITPAUSE, 0.1);
set_hitbox_value(AT_NAIR, 9, HG_HITPAUSE_SCALING, .2);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_NAIR, 9, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_NAIR, 9, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_SPRITE, sprite_get("shard"));
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_ANIM_SPEED, .90);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_HSPEED, 5);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_VSPEED, 5);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_NAIR, 9, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);