sprite_change_offset("idle", 64, 94);
sprite_change_offset("wait", 64, 94);
sprite_change_offset("hurt", 64, 94);
sprite_change_offset("spinhurt", 64, 94);
sprite_change_offset("bighurt", 64, 94);
sprite_change_offset("uphurt", 64, 94);
sprite_change_offset("hurtground", 64, 94);
sprite_change_offset("crouch", 64, 94);
sprite_change_offset("walk", 64, 94);
sprite_change_offset("walkturn", 64, 94);
sprite_change_offset("dash", 64, 94);
sprite_change_offset("dashstart", 64, 94);
sprite_change_offset("dashstop", 64, 94);
sprite_change_offset("dashturn", 64, 94);

sprite_change_offset("jumpstart", 64, 94);
sprite_change_offset("jump", 64, 94);
sprite_change_offset("doublejump", 64, 94);
sprite_change_offset("walljump", 64, 94);
sprite_change_offset("pratfall", 64, 94);
sprite_change_offset("land", 64, 94);
sprite_change_offset("landinglag", 64, 94);

sprite_change_offset("parry", 64, 94);
sprite_change_offset("roll_forward", 64, 94);
sprite_change_offset("roll_backward", 64, 94);
sprite_change_offset("airdodge", 64, 94);
sprite_change_offset("waveland", 64, 94);
sprite_change_offset("tech", 64, 94);

sprite_change_offset("particles", 4, 14);
sprite_change_offset("sweet", 64,64);
sprite_change_offset("smallhit", 32, 42);

sprite_change_offset("jab", 64, 94);
sprite_change_offset("dattack", 64, 94);
sprite_change_offset("ftilt", 64, 94);
sprite_change_offset("dtilt", 64, 94);
sprite_change_offset("utilt", 64, 94);
sprite_change_offset("nair", 64, 94);
sprite_change_offset("fair", 64, 94);
sprite_change_offset("bair", 64, 94);
sprite_change_offset("uair", 64, 94);
sprite_change_offset("dair", 64, 94);
sprite_change_offset("fstrong", 64, 94);
sprite_change_offset("ustrong", 64, 94);
sprite_change_offset("dstrong", 64, 94);
sprite_change_offset("nspecial", 64, 94);
sprite_change_offset("nspecial2", 64, 94);
sprite_change_offset("fspecial", 64, 94);
sprite_change_offset("fspecial2", 64, 94);
sprite_change_offset("uspecial", 64, 94);
sprite_change_offset("uspecial2", 64, 94);
sprite_change_offset("dspecial2", 64, 94);
sprite_change_offset("dspecial", 64, 94);
sprite_change_offset("ewgf", 64, 94);
sprite_change_offset("pewgf", 64, 94);
sprite_change_offset("taunt", 64, 94);
sprite_change_offset("taunt2", 64, 94);
sprite_change_offset("genesistaunt", 64, 94);
sprite_change_offset("star", 10,10);

sprite_change_offset("fs", 64, 94);
sprite_change_offset("beamfs", 64, 128);

sprite_change_offset("kinnikubehind", 140, 190);
sprite_change_offset("kinnikufront", 140, 190);

sprite_change_offset("plat", 64, 94);
sprite_change_offset("uspecial_proj", 64, 64);
sprite_change_offset("bubble_proj", 64, 64);
sprite_change_offset("nspecial_proj", 64, 64);
sprite_change_offset("nspecial_proj2", 64, 64);
sprite_change_offset("nspecial_projfire", 64, 64);
sprite_change_offset("nspecial2_proj", 64, 64);
sprite_change_offset("nspecialriptide_proj", 64, 64);
sprite_change_offset("nspecialbighouse_proj", 64, 64);
sprite_change_offset("nspecial2_glow", 64, 64);
sprite_change_offset("arrow_indi", 64, 110);
sprite_change_offset("nspecial2_proj_death", 64, 64);
sprite_change_offset("nspecial2_proj_detonatesmall", 64, 64);
sprite_change_offset("nspecial2_proj_detonatebig", 64, 64);
sprite_change_offset("ewgfhit", 64, 64);
sprite_change_offset("anglarahitfx", 64, 64);
sprite_change_offset("orbhitfx_large", 106, 98);
sprite_change_offset("cooldown", 64, 94);
sprite_change_offset("offscreen_indicator", -12, 18);
sprite_change_offset("orb_indicator", -12, 18);
sprite_change_offset("go", 32, 32);