//final_smash
set_attack_value(49, AG_SPRITE, sprite_get("final_smash"));
set_attack_value(49, AG_NUM_WINDOWS, 7);
set_attack_value(49, AG_HURTBOX_SPRITE, asset_get("empty_sprite"));
set_attack_value(49, AG_HAS_LANDING_LAG, 0);
set_attack_value(49, AG_LANDING_LAG, 0);

set_window_value(49, 1, AG_WINDOW_LENGTH, 62);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 13);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(49, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 1, AG_WINDOW_SFX, sound_get("fsmash_start"));
set_window_value(49, 1, AG_WINDOW_SFX_FRAME, 1);
set_window_value(49, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_HSPEED, 0);

set_window_value(49, 2, AG_WINDOW_TYPE, 9);
set_window_value(49, 2, AG_WINDOW_LENGTH, 10);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 12);
set_window_value(49, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_HSPEED, 6);

set_window_value(49, 3, AG_WINDOW_LENGTH, 34);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 10);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 14);
set_window_value(49, 3, AG_WINDOW_HSPEED, 3);

//TUBATUBATUBATUBA
set_window_value(49, 4, AG_WINDOW_LENGTH, 12);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 23);

set_window_value(49, 5, AG_WINDOW_LENGTH, 12);
set_window_value(49, 5, AG_WINDOW_TYPE, 9);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAME_START, 26);
set_window_value(49, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 5, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 5, AG_WINDOW_SFX, asset_get("sfx_swipe_medium2"));
set_window_value(49, 5, AG_WINDOW_SFX_FRAME, 1);
set_window_value(49, 5, AG_WINDOW_HSPEED, 0.25);

set_window_value(49, 6, AG_WINDOW_LENGTH, 18);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAME_START, 33);
set_window_value(49, 6, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 6, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 6, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));
set_window_value(49, 6, AG_WINDOW_SFX_FRAME, 5);
set_window_value(49, 6, AG_WINDOW_HSPEED, 3);

set_window_value(49, 7, AG_WINDOW_LENGTH, 36);
set_window_value(49, 7, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(49, 7, AG_WINDOW_ANIM_FRAME_START, 40);
set_window_value(49, 7, AG_WINDOW_HSPEED, 0);


set_num_hitboxes(49, 5);

set_hitbox_value(49, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(49, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 1, HG_WINDOW, 2);
set_hitbox_value(49, 1, HG_LIFETIME, 4);
set_hitbox_value(49, 1, HG_HITBOX_Y, -80);
set_hitbox_value(49, 1, HG_HITBOX_X, 0);
set_hitbox_value(49, 1, HG_WIDTH, 180);
set_hitbox_value(49, 1, HG_HEIGHT, 180);
set_hitbox_value(49, 1, HG_SHAPE, 0);
set_hitbox_value(49, 1, HG_PRIORITY, 10);
set_hitbox_value(49, 1, HG_DAMAGE, 4);
set_hitbox_value(49, 1, HG_ANGLE, 50);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 2);
set_hitbox_value(49, 1, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(49, 1, HG_TECHABLE, 0);

set_hitbox_value(49, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(49, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(49, 2, HG_WINDOW, 3);
set_hitbox_value(49, 2, HG_LIFETIME, 6);
set_hitbox_value(49, 2, HG_HITBOX_Y, -80);
set_hitbox_value(49, 2, HG_HITBOX_X, 0);
set_hitbox_value(49, 2, HG_WIDTH, 180);
set_hitbox_value(49, 2, HG_HEIGHT, 180);
set_hitbox_value(49, 2, HG_SHAPE, 0);
set_hitbox_value(49, 2, HG_PRIORITY, 10);
set_hitbox_value(49, 2, HG_DAMAGE, 12);
set_hitbox_value(49, 2, HG_ANGLE, 40);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 10);
set_hitbox_value(49, 2, HG_KNOCKBACK_SCALING, .70);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 2);
set_hitbox_value(49, 2, HG_EXTRA_HITPAUSE, 16);
set_hitbox_value(49, 2, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 2, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 2, HG_HIT_SFX, sound_get("biglaunch"));
set_hitbox_value(49, 2, HG_TECHABLE, 0);

set_hitbox_value(49, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(49, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 3, HG_WINDOW, 5);
set_hitbox_value(49, 3, HG_LIFETIME, 2);
set_hitbox_value(49, 3, HG_HITBOX_Y, -60);
set_hitbox_value(49, 3, HG_HITBOX_X, 80);
set_hitbox_value(49, 3, HG_WIDTH, 200);
set_hitbox_value(49, 3, HG_HEIGHT, 120);
set_hitbox_value(49, 3, HG_SHAPE, 2);
set_hitbox_value(49, 3, HG_PRIORITY, 10);
set_hitbox_value(49, 3, HG_DAMAGE, 2);
set_hitbox_value(49, 3, HG_ANGLE, 50);
set_hitbox_value(49, 3, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(49, 3, HG_EXTRA_HITPAUSE, 4);
set_hitbox_value(49, 3, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(49, 3, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 3, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(49, 3, HG_TECHABLE, 0);
set_hitbox_value(49, 3, HG_SDI_MULTIPLIER, 0);

set_hitbox_value(49, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(49, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 4, HG_WINDOW, 5);
set_hitbox_value(49, 4, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(49, 4, HG_LIFETIME, 2);
set_hitbox_value(49, 4, HG_HITBOX_Y, -60);
set_hitbox_value(49, 4, HG_HITBOX_X, 80);
set_hitbox_value(49, 4, HG_WIDTH, 200);
set_hitbox_value(49, 4, HG_HEIGHT, 120);
set_hitbox_value(49, 4, HG_SHAPE, 2);
set_hitbox_value(49, 4, HG_PRIORITY, 10);
set_hitbox_value(49, 4, HG_DAMAGE, 2);
set_hitbox_value(49, 4, HG_ANGLE, 50);
set_hitbox_value(49, 4, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(49, 4, HG_EXTRA_HITPAUSE, 4);
set_hitbox_value(49, 4, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(49, 4, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 4, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 4, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(49, 4, HG_TECHABLE, 0);
set_hitbox_value(49, 4, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(49, 4, HG_SDI_MULTIPLIER, 0);

set_hitbox_value(49, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(49, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 5, HG_WINDOW, 6);
set_hitbox_value(49, 5, HG_WINDOW_CREATION_FRAME, 11);
set_hitbox_value(49, 5, HG_LIFETIME, 6);
set_hitbox_value(49, 5, HG_HITBOX_Y, -60);
set_hitbox_value(49, 5, HG_HITBOX_X, 80);
set_hitbox_value(49, 5, HG_WIDTH, 200);
set_hitbox_value(49, 5, HG_HEIGHT, 120);
set_hitbox_value(49, 5, HG_SHAPE, 2);
set_hitbox_value(49, 5, HG_PRIORITY, 10);
set_hitbox_value(49, 5, HG_DAMAGE, 8);
set_hitbox_value(49, 5, HG_ANGLE, 40);
set_hitbox_value(49, 5, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(49, 5, HG_KNOCKBACK_SCALING, 1.50);
set_hitbox_value(49, 5, HG_BASE_HITPAUSE, 8);
set_hitbox_value(49, 5, HG_EXTRA_HITPAUSE, 20);
set_hitbox_value(49, 5, HG_HITPAUSE_SCALING, 4.25);
set_hitbox_value(49, 5, HG_VISUAL_EFFECT, 197);
set_hitbox_value(49, 5, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(49, 5, HG_HIT_SFX, sound_get("biglaunch"));
set_hitbox_value(49, 5, HG_TECHABLE, 0);
set_hitbox_value(49, 5, HG_SDI_MULTIPLIER, 0);