set_attack_value(AT_FSPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_FSPECIAL, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_NUM_WINDOWS, 2);
set_attack_value(AT_FSPECIAL, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));

set_window_value(AT_FSPECIAL, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 4);

set_window_value(AT_FSPECIAL, 2, AG_WINDOW_LENGTH, 8);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_SFX, sound_get("elu"));//sound_get("jack_grunt"));

var lifetime = 10;
var damage = 8;
var angle = 90;
var bkb = 6;
var kbg = 0.4;
var hp = 6;
var hpg = 0.4;
var vfx = 304;
var sfx = asset_get("sfx_blow_heavy2");

// bottom
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_LIFETIME, lifetime);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_X, 64);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_Y, 110);
set_hitbox_value(AT_FSPECIAL, 1, HG_WIDTH, 100);
set_hitbox_value(AT_FSPECIAL, 1, HG_HEIGHT, 180);
set_hitbox_value(AT_FSPECIAL, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_DAMAGE, damage);
set_hitbox_value(AT_FSPECIAL, 1, HG_ANGLE, angle);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_KNOCKBACK, bkb);
set_hitbox_value(AT_FSPECIAL, 1, HG_KNOCKBACK_SCALING, kbg);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_HITPAUSE, hp);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITPAUSE_SCALING, hpg);
set_hitbox_value(AT_FSPECIAL, 1, HG_VISUAL_EFFECT, vfx);
set_hitbox_value(AT_FSPECIAL, 1, HG_HIT_SFX, sfx);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 1, HG_PROJECTILE_IS_TRANSCENDENT, true);

var angle = 135;
// right
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_LIFETIME, lifetime);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_X, 110);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_Y, -64);
set_hitbox_value(AT_FSPECIAL, 2, HG_WIDTH, 180);
set_hitbox_value(AT_FSPECIAL, 2, HG_HEIGHT, 100);
set_hitbox_value(AT_FSPECIAL, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, 2, HG_DAMAGE, damage);
set_hitbox_value(AT_FSPECIAL, 2, HG_ANGLE, angle);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_KNOCKBACK, bkb);
set_hitbox_value(AT_FSPECIAL, 2, HG_KNOCKBACK_SCALING, kbg);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_HITPAUSE, hp);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITPAUSE_SCALING, hpg);
set_hitbox_value(AT_FSPECIAL, 2, HG_VISUAL_EFFECT, vfx);
set_hitbox_value(AT_FSPECIAL, 2, HG_HIT_SFX, sfx);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 2, HG_PROJECTILE_IS_TRANSCENDENT, true);

var angle = 270;
// top
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_LIFETIME, lifetime);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_X, -64);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_Y, -110);
set_hitbox_value(AT_FSPECIAL, 3, HG_WIDTH, 100);
set_hitbox_value(AT_FSPECIAL, 3, HG_HEIGHT, 180);
set_hitbox_value(AT_FSPECIAL, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, 3, HG_DAMAGE, damage);
set_hitbox_value(AT_FSPECIAL, 3, HG_ANGLE, angle);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_KNOCKBACK, bkb);
set_hitbox_value(AT_FSPECIAL, 3, HG_KNOCKBACK_SCALING, kbg);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_HITPAUSE, hp);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITPAUSE_SCALING, hpg);
set_hitbox_value(AT_FSPECIAL, 3, HG_VISUAL_EFFECT, vfx);
set_hitbox_value(AT_FSPECIAL, 3, HG_HIT_SFX, sfx);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 3, HG_PROJECTILE_IS_TRANSCENDENT, true);

var angle = 45;
// left
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_LIFETIME, lifetime);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_X, -110);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_Y, 64);
set_hitbox_value(AT_FSPECIAL, 4, HG_WIDTH, 180);
set_hitbox_value(AT_FSPECIAL, 4, HG_HEIGHT, 100);
set_hitbox_value(AT_FSPECIAL, 4, HG_PRIORITY, 1);
set_hitbox_value(AT_FSPECIAL, 4, HG_DAMAGE, damage);
set_hitbox_value(AT_FSPECIAL, 4, HG_ANGLE, angle);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_KNOCKBACK, bkb);
set_hitbox_value(AT_FSPECIAL, 4, HG_KNOCKBACK_SCALING, kbg);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_HITPAUSE, hp);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITPAUSE_SCALING, hpg);
set_hitbox_value(AT_FSPECIAL, 4, HG_VISUAL_EFFECT, vfx);
set_hitbox_value(AT_FSPECIAL, 4, HG_HIT_SFX, sfx);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_PARRY_STUN, false);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_DOES_NOT_REFLECT, true);
set_hitbox_value(AT_FSPECIAL, 4, HG_PROJECTILE_IS_TRANSCENDENT, true);