//attack properties
set_attack_value(AT_EXTRA_3, AG_CATEGORY, 0);
set_attack_value(AT_EXTRA_3, AG_SPRITE, 0);
set_attack_value(AT_EXTRA_3, AG_AIR_SPRITE, 0);
set_attack_value(AT_EXTRA_3, AG_HURTBOX_SPRITE, 0);
set_attack_value(AT_EXTRA_3, AG_HURTBOX_AIR_SPRITE, 0);
set_attack_value(AT_EXTRA_3, AG_NUM_WINDOWS, 1);
set_attack_value(AT_EXTRA_3, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_EXTRA_3, AG_OFF_LEDGE, 0);
set_attack_value(AT_EXTRA_3, AG_LANDING_LAG, 0);
set_attack_value(AT_EXTRA_3, AG_STRONG_CHARGE_WINDOW, 0);
set_attack_value(AT_EXTRA_3, AG_USES_CUSTOM_GRAVITY, 0);

//attack window properties
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_TYPE, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_LENGTH, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_ANIM_FRAMES, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_ANIM_FRAME_START, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_CUSTOM_AIR_FRICTION, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_CUSTOM_GRAVITY, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HAS_WHIFFLAG, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_INVINCIBILITY, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HITPAUSE_FRAME, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_CANCEL_TYPE, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_CANCEL_FRAME, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_HAS_SFX, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_SFX, 0);
set_window_value(AT_EXTRA_3, 1, AG_WINDOW_SFX_FRAME, 0);

//attack hitbox properties
set_num_hitboxes(AT_EXTRA_3, 3);

//individual hitbox properties
set_hitbox_value(AT_EXTRA_3, 1, HG_PARENT_HITBOX, 0); // fire breath
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_LIFETIME, 10);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_BASE_KNOCKBACK, 0.6);
set_hitbox_value(AT_EXTRA_3, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_EFFECT, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HIT_SFX, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_EXTRA_HITPAUSE, 10);
set_hitbox_value(AT_EXTRA_3, 1, HG_GROUNDEDNESS, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HIT_LOCKOUT, 5);
set_hitbox_value(AT_EXTRA_3, 1, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_TECHABLE, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_FORCE_FLINCH, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_FINAL_BASE_KNOCKBACK , 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_THROWS_ROCK, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_SPRITE, asset_get("zet_proj_spr"));
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_MASK, asset_get("zet_proj_spr"));
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_ANIM_SPEED, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_HSPEED, 10);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_VSPEED, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_GRAVITY, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_AIR_FRICTION, 0.5);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_3, 1, HG_PROJECTILE_DESTROY_EFFECT, 3);

//individual hitbox properties
set_hitbox_value(AT_EXTRA_3, 2, HG_PARENT_HITBOX, 0); // rain
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 2, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_LIFETIME, 160);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_ANGLE, 270);
set_hitbox_value(AT_EXTRA_3, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_EFFECT, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT, 10);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HIT_SFX, asset_get("sfx_watergun_splash"));
set_hitbox_value(AT_EXTRA_3, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_GROUNDEDNESS, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_TECHABLE, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_FINAL_BASE_KNOCKBACK, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_SPRITE, asset_get("big_bubble_spr"));
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_MASK, asset_get("big_bubble_spr"));
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_GRAVITY, 0.1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_3, 2, HG_PROJECTILE_DESTROY_EFFECT, 6);

//individual hitbox properties
set_hitbox_value(AT_EXTRA_3, 3, HG_PARENT_HITBOX, 0); // pillar
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_EXTRA_3, 3, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_WINDOW_CREATION_FRAME, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_LIFETIME, 200);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_Y, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_WIDTH, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HEIGHT, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_DAMAGE, 30);
set_hitbox_value(AT_EXTRA_3, 3, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_3, 3, HG_BASE_KNOCKBACK, 100);
set_hitbox_value(AT_EXTRA_3, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_EFFECT, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_VISUAL_EFFECT, 155);
set_hitbox_value(AT_EXTRA_3, 3, HG_VISUAL_EFFECT_X_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HIT_SFX, asset_get("sfx_kragg_rock_shatter"));
set_hitbox_value(AT_EXTRA_3, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_GROUNDEDNESS, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_EXTRA_CAMERA_SHAKE, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_IGNORES_PROJECTILES, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_EXTENDED_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITBOX_GROUP, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_HITSTUN_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_SDI_MULTIPLIER, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_TECHABLE, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_FORCE_FLINCH, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_FINAL_BASE_KNOCKBACK, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_THROWS_ROCK, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_SPRITE, asset_get("rock_pillar_spr"));
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_MASK, asset_get("rock_pillar_spr"));
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_VSPEED, -2);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_UNBASHABLE, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_PARRY_STUN, 0);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_DOES_NOT_REFLECT, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_IS_TRANSCENDENT, 1);
set_hitbox_value(AT_EXTRA_3, 3, HG_PROJECTILE_DESTROY_EFFECT, 0);

set_hitbox_value(AT_EXTRA_3, 4, HG_HITBOX_TYPE, 2); // particle effect
set_hitbox_value(AT_EXTRA_3, 4, HG_WINDOW, 0);
set_hitbox_value(AT_EXTRA_3, 4, HG_LIFETIME, 60);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_SPRITE, sprite_get("particle"));
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_GRAVITY, .3);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_GROUND_FRICTION, 10);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_WALL_BEHAVIOR, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_GROUND_BEHAVIOR, 2);
set_hitbox_value(AT_EXTRA_3, 4, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);