set_attack_value(49, AG_CATEGORY, 2);
set_attack_value(49, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(49, AG_NUM_WINDOWS, 6);
set_attack_value(49, AG_AIR_SPRITE, sprite_get("fspecial"));
set_attack_value(49, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));

set_window_value(49, 1, AG_WINDOW_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_LENGTH, 12);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 1, AG_WINDOW_HSPEED, 0);
set_window_value(49, 1, AG_WINDOW_VSPEED, 0);
set_window_value(49, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 1, AG_WINDOW_SFX, asset_get("sfx_zetter_fireball_fire"));
set_window_value(49, 1, AG_WINDOW_SFX_FRAME, 2);

set_window_value(49, 2, AG_WINDOW_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_LENGTH, 32);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(49, 2, AG_WINDOW_HSPEED, 0);
set_window_value(49, 2, AG_WINDOW_VSPEED, 0);
set_window_value(49, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(49, 3, AG_WINDOW_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_LENGTH, 3);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(49, 3, AG_WINDOW_HSPEED, 0);
set_window_value(49, 3, AG_WINDOW_VSPEED, 0);
set_window_value(49, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(49, 4, AG_WINDOW_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_LENGTH, 64);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(49, 4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(49, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 4, AG_WINDOW_SFX, sound_get("blink"));
set_window_value(49, 4, AG_WINDOW_SFX_FRAME, 1);

set_window_value(49, 5, AG_WINDOW_TYPE, 1);
set_window_value(49, 5, AG_WINDOW_LENGTH, 20);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(49, 5, AG_WINDOW_HSPEED, 0);
set_window_value(49, 5, AG_WINDOW_VSPEED, 0);
set_window_value(49, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 5, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(49, 6, AG_WINDOW_TYPE, 1);
set_window_value(49, 6, AG_WINDOW_LENGTH, 10);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAME_START, 11);
set_window_value(49, 6, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(49, 6, AG_WINDOW_HSPEED, 3);
set_window_value(49, 6, AG_WINDOW_VSPEED, -3);
set_window_value(49, 6, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(49, 6, AG_WINDOW_VSPEED_TYPE, 2);

set_num_hitboxes(49, 2);

set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 1, HG_WINDOW, 5);
set_hitbox_value(49, 1, HG_LIFETIME, 6);
set_hitbox_value(49, 1, HG_HITBOX_X, 0);
set_hitbox_value(49, 1, HG_HITBOX_Y, -0);
set_hitbox_value(49, 1, HG_SHAPE, 1);
set_hitbox_value(49, 1, HG_WIDTH, room_width);
set_hitbox_value(49, 1, HG_HEIGHT, room_height);
set_hitbox_value(49, 1, HG_PRIORITY, 9);
set_hitbox_value(49, 1, HG_DAMAGE, 18);
set_hitbox_value(49, 1, HG_ANGLE, 40);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 20);
set_hitbox_value(49, 1, HG_HITSTUN_MULTIPLIER, 1.5);
set_hitbox_value(49, 1, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT, flash_effect);
set_hitbox_value(49, 1, HG_VISUAL_EFFECT_Y_OFFSET, 0);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 14);
set_hitbox_value(49, 1, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 1, HG_HIT_SFX, sound_get("boss_down"));
set_hitbox_value(49, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 1, HG_TECHABLE, 0);
set_hitbox_value(49, 1, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(49, 1, HG_HITBOX_GROUP, -1);

set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(49, 2, HG_WINDOW, 4);
set_hitbox_value(49, 2, HG_LIFETIME, 1);
set_hitbox_value(49, 2, HG_HITBOX_X, 0);
set_hitbox_value(49, 2, HG_HITBOX_Y, 0);
set_hitbox_value(49, 2, HG_SHAPE, 1);
set_hitbox_value(49, 2, HG_WIDTH, room_width);
set_hitbox_value(49, 2, HG_HEIGHT, room_height);
set_hitbox_value(49, 2, HG_PRIORITY, 9);
set_hitbox_value(49, 2, HG_DAMAGE, 1);
set_hitbox_value(49, 2, HG_ANGLE, 40);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 2, HG_EXTRA_HITPAUSE, 5);
set_hitbox_value(49, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(49, 2, HG_TECHABLE, 0);
set_hitbox_value(49, 2, HG_DRIFT_MULTIPLIER, 0);
set_hitbox_value(49, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 2, HG_HIT_SFX, asset_get("sfx_blow_weak1"));