set_attack_value(AT_EXTRA_1, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_1, AG_OFF_LEDGE, 1);;
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("fspecialroll"));
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("fspecialroll_hurt"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 5);

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 14);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX, asset_get("sfx_ori_stomp_spin"));
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 0);
//set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAME_START, 7);

set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, 4);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy1"));
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_EXTRA_1, 3, AG_WINDOW_TYPE, 10);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_LENGTH, 5);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_VSPEED, 10);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAME_START, 10);

set_window_value(AT_EXTRA_1, 4, AG_WINDOW_LENGTH, 8);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAME_START, 15);

set_window_value(AT_EXTRA_1, 5, AG_WINDOW_LENGTH, 12);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAME_START, 17);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_EXTRA_1, 1);

set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 3);
//set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 5);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -33);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 60);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 60);
set_hitbox_value(AT_EXTRA_1, 1, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 270);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_EXTRA_1, 1, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 6);
//set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE_FLIPPER, 10);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get ("sfx_blow_heavy1"));
set_hitbox_value(AT_EXTRA_1, 1, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_SDI_MULTIPLIER, 1);
//set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
//set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_LOCKOUT, 2);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -11);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 64);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 34);
set_hitbox_value(AT_EXTRA_1, 2, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 8);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 45);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_EXTRA_1, 2, HG_KNOCKBACK_SCALING, .7);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITPAUSE_SCALING, .7);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get ("sfx_blow_weak1"));
set_hitbox_value(AT_EXTRA_1, 2, HG_DRIFT_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_SDI_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
