set_attack_value(AT_DAIR, AG_CATEGORY, 2);
set_attack_value(AT_DAIR, AG_SPRITE, sprite_get("dair"));
set_attack_value(AT_DAIR, AG_HAS_LANDING_LAG, 0);
set_attack_value(AT_DAIR, AG_LANDING_LAG, 7);
set_attack_value(AT_DAIR, AG_NUM_WINDOWS, 7);
set_attack_value(AT_DAIR, AG_HURTBOX_SPRITE, sprite_get("dair"));

set_window_value(AT_DAIR, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DAIR, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DAIR, 1, AG_WINDOW_VSPEED, -10);
set_window_value(AT_DAIR, 1, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DAIR, 1, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_DAIR, 1, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_DAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 1, AG_WINDOW_SFX, sound_get("blip"));
set_window_value(AT_DAIR, 1, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_DAIR, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_DAIR, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_DAIR, 2, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DAIR, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_DAIR, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DAIR, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_DAIR, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);

set_window_value(AT_DAIR, 3, AG_WINDOW_LENGTH, 2);
set_window_value(AT_DAIR, 3, AG_WINDOW_TYPE, 8);
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_DAIR, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_VSPEED, 12);
set_window_value(AT_DAIR, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DAIR, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 3, AG_WINDOW_SFX, sound_get("bouncefall"));

set_window_value(AT_DAIR, 4, AG_WINDOW_LENGTH, 40);
set_window_value(AT_DAIR, 4, AG_WINDOW_TYPE, 8);
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAME_START, 6);
set_window_value(AT_DAIR, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_DAIR, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 1);
set_window_value(AT_DAIR, 4, AG_WINDOW_VSPEED, 4);
set_window_value(AT_DAIR, 4, AG_WINDOW_VSPEED_TYPE, 0);
set_window_value(AT_DAIR, 4, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DAIR, 4, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_DAIR, 5, AG_WINDOW_LENGTH, 2);
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_DAIR, 5, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DAIR, 5, AG_WINDOW_SFX, sound_get("buttbounce"));

set_window_value(AT_DAIR, 6, AG_WINDOW_LENGTH, 4);
set_window_value(AT_DAIR, 6, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DAIR, 6, AG_WINDOW_ANIM_FRAME_START, 8);
set_window_value(AT_DAIR, 6, AG_WINDOW_HAS_WHIFFLAG, 1);

set_window_value(AT_DAIR, 7, AG_WINDOW_LENGTH, 7);
set_window_value(AT_DAIR, 7, AG_WINDOW_HAS_WHIFFLAG, 1);
set_window_value(AT_DAIR, 7, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DAIR, 7, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DAIR, 7, AG_WINDOW_VSPEED, -10);
set_window_value(AT_DAIR, 7, AG_WINDOW_HSPEED, 0);
set_window_value(AT_DAIR, 7, AG_WINDOW_VSPEED_TYPE, 2);
set_window_value(AT_DAIR, 7, AG_WINDOW_HSPEED_TYPE, 2);

set_num_hitboxes(AT_DAIR, 2);

set_hitbox_value(AT_DAIR, 1, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 1, HG_WINDOW, 3);
set_hitbox_value(AT_DAIR, 1, HG_LIFETIME, 999);
set_hitbox_value(AT_DAIR, 1, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_X, -2);
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_Y, -16);
set_hitbox_value(AT_DAIR, 1, HG_PRIORITY, 6);
set_hitbox_value(AT_DAIR, 1, HG_WIDTH, 36);
set_hitbox_value(AT_DAIR, 1, HG_HEIGHT, 36);
set_hitbox_value(AT_DAIR, 1, HG_SHAPE, 0);
set_hitbox_value(AT_DAIR, 1, HG_DAMAGE, 8);
set_hitbox_value(AT_DAIR, 1, HG_ANGLE, -90);
set_hitbox_value(AT_DAIR, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_DAIR, 1, HG_KNOCKBACK_SCALING, .45);
set_hitbox_value(AT_DAIR, 1, HG_BASE_HITPAUSE, 25);
set_hitbox_value(AT_DAIR, 1, HG_HITPAUSE_SCALING, .5);
set_hitbox_value(AT_DAIR, 1, HG_HIT_SFX, sound_get("megahit"));

set_hitbox_value(AT_DAIR, 2, HG_PARENT_HITBOX, 0);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DAIR, 2, HG_WINDOW, 5);
set_hitbox_value(AT_DAIR, 2, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(AT_DAIR, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_DAIR, 2, HG_PRIORITY, 10);
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_Y, -22);
set_hitbox_value(AT_DAIR, 2, HG_WIDTH, 100);
set_hitbox_value(AT_DAIR, 2, HG_HEIGHT, 46);
set_hitbox_value(AT_DAIR, 2, HG_SHAPE, 1);
set_hitbox_value(AT_DAIR, 2, HG_DAMAGE, 6);
set_hitbox_value(AT_DAIR, 2, HG_ANGLE, 361);
set_hitbox_value(AT_DAIR, 2, HG_ANGLE_FLIPPER, 3);
set_hitbox_value(AT_DAIR, 2, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DAIR, 2, HG_KNOCKBACK_SCALING, .65);
set_hitbox_value(AT_DAIR, 2, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DAIR, 2, HG_HITPAUSE_SCALING, .55);
set_hitbox_value(AT_DAIR, 2, HG_HIT_SFX, sound_get("hardhit"));
set_hitbox_value(AT_DAIR, 2, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_DAIR, 2, HG_VISUAL_EFFECT_X_OFFSET, 20);
set_hitbox_value(AT_DAIR, 2, HG_VISUAL_EFFECT, 0);
set_hitbox_value(AT_DAIR, 2, HG_EXTRA_CAMERA_SHAKE, 1);




set_hitbox_value(AT_DAIR, 8, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_DAIR, 8, HG_WINDOW, 100);
set_hitbox_value(AT_DAIR, 8, HG_LIFETIME, 999);
set_hitbox_value(AT_DAIR, 8, HG_HITBOX_X, 60);
set_hitbox_value(AT_DAIR, 8, HG_HITBOX_Y, -30);
set_hitbox_value(AT_DAIR, 8, HG_PRIORITY, 3);
set_hitbox_value(AT_DAIR, 8, HG_WIDTH, 28);
set_hitbox_value(AT_DAIR, 8, HG_HEIGHT, 28);
set_hitbox_value(AT_DAIR, 8, HG_DAMAGE, 4);
set_hitbox_value(AT_DAIR, 8, HG_ANGLE, 30);
set_hitbox_value(AT_DAIR, 8, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_DAIR, 8, HG_KNOCKBACK_SCALING, 0.4);
set_hitbox_value(AT_DAIR, 8, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_DAIR, 8, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_DAIR, 8, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DAIR, 8, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DAIR, 8, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_SPRITE, sprite_get("water"));
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_ANIM_SPEED, 0.2);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_HSPEED, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_VSPEED, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_GRAVITY, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_UNBASHABLE, true);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_DESTROY_EFFECT, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_GROUND_FRICTION, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_AIR_FRICTION, 0);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_IS_TRANSCENDENT, true);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_DAIR, 8, HG_PROJECTILE_DOES_NOT_REFLECT, true);