set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("jab"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 9);
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("jab_hurt"));

set_num_hitboxes(AT_EXTRA_1, 2);

set_hitbox_value(AT_EXTRA_1, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, hitbox_rate);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, -16);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -26);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 25);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 29);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 70);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE_FLIPPER, 7);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_EXTRA_1, 1, HG_FORCE_FLINCH, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 1, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_SDI_MULTIPLIER, 1.25);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, hitbox_rate);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, -22);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -25);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 36);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 36);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 45);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE_FLIPPER, 7);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_EXTRA_1, 2, HG_FORCE_FLINCH, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_SDI_MULTIPLIER, 1.25);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, hitbox_rate);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, -12);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -26);
set_hitbox_value(AT_EXTRA_1, 3, HG_WIDTH, 28);
set_hitbox_value(AT_EXTRA_1, 3, HG_HEIGHT, 40);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE_FLIPPER, 7);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_EXTRA_1, 3, HG_FORCE_FLINCH, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 3, HG_IGNORES_PROJECTILES, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_SDI_MULTIPLIER, 1.25);