set_attack_value(AT_DATTACK, AG_SPRITE, sprite_get("dattack"));
set_attack_value(AT_DATTACK, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DATTACK, AG_AIR_SPRITE, sprite_get("dattack"));
set_attack_value(AT_DATTACK, AG_HURTBOX_SPRITE, sprite_get("dattack_hurt"));

set_window_value(AT_DATTACK, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DATTACK, 1, AG_WINDOW_LENGTH, 8);
set_window_value(AT_DATTACK, 1, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DATTACK, 1, AG_WINDOW_HSPEED, 2.5);
set_window_value(AT_DATTACK, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DATTACK, 1, AG_WINDOW_SFX, asset_get("sfx_spin"));
set_window_value(AT_DATTACK, 1, AG_WINDOW_SFX_FRAME, 6);

set_window_value(AT_DATTACK, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DATTACK, 2, AG_WINDOW_LENGTH, 10);
set_window_value(AT_DATTACK, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_DATTACK, 2, AG_WINDOW_ANIM_FRAME_START, 4);
set_window_value(AT_DATTACK, 2, AG_WINDOW_HSPEED, 6);
set_window_value(AT_DATTACK, 2, AG_WINDOW_HSPEED_TYPE, 1);

set_window_value(AT_DATTACK, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DATTACK, 3, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DATTACK, 3, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_DATTACK, 3, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DATTACK, 3, AG_WINDOW_HSPEED, 2.8);
set_window_value(AT_DATTACK, 3, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_DATTACK, 3, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_DATTACK, 5);

var multihit_base_kb = 6;
var multihit_hitpause = 4;

set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 1, HG_MUNO_HITBOX_NAME, "Multihit Hitbox 1");
set_hitbox_value(AT_DATTACK, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_X, 2);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_Y, -31);
set_hitbox_value(AT_DATTACK, 1, HG_WIDTH, 102);
set_hitbox_value(AT_DATTACK, 1, HG_HEIGHT, 33);
set_hitbox_value(AT_DATTACK, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_DATTACK, 1, HG_DAMAGE, 1);
set_hitbox_value(AT_DATTACK, 1, HG_ANGLE, 45);
set_hitbox_value(AT_DATTACK, 1, HG_ANGLE_FLIPPER, 10);
set_hitbox_value(AT_DATTACK, 1, HG_BASE_KNOCKBACK, multihit_base_kb);
set_hitbox_value(AT_DATTACK, 1, HG_BASE_HITPAUSE, multihit_hitpause);
set_hitbox_value(AT_DATTACK, 1, HG_VISUAL_EFFECT_X_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 1, HG_VISUAL_EFFECT_Y_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 1, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_DATTACK, 1, HG_TECHABLE, 3);
set_hitbox_value(AT_DATTACK, 1, HG_HITBOX_GROUP, 1);

set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 2, HG_MUNO_HITBOX_NAME, "Multihit Hitbox 1");
set_hitbox_value(AT_DATTACK, 2, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_DATTACK, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_X, 1);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_Y, -31);
set_hitbox_value(AT_DATTACK, 2, HG_WIDTH, 88);
set_hitbox_value(AT_DATTACK, 2, HG_HEIGHT, 33);
set_hitbox_value(AT_DATTACK, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_DATTACK, 2, HG_DAMAGE, 1);
set_hitbox_value(AT_DATTACK, 2, HG_ANGLE, 45);
set_hitbox_value(AT_DATTACK, 2, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_DATTACK, 2, HG_BASE_KNOCKBACK, multihit_base_kb);
set_hitbox_value(AT_DATTACK, 2, HG_BASE_HITPAUSE, multihit_hitpause);
set_hitbox_value(AT_DATTACK, 2, HG_VISUAL_EFFECT_X_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 2, HG_VISUAL_EFFECT_Y_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 2, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_DATTACK, 2, HG_TECHABLE, 3);
set_hitbox_value(AT_DATTACK, 2, HG_HITBOX_GROUP, 2);

set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 3, HG_MUNO_HITBOX_NAME, "Multihit Hitbox 1");
set_hitbox_value(AT_DATTACK, 3, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 3, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DATTACK, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_X, 1);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_Y, -31);
set_hitbox_value(AT_DATTACK, 3, HG_WIDTH, 88);
set_hitbox_value(AT_DATTACK, 3, HG_HEIGHT, 33);
set_hitbox_value(AT_DATTACK, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_DATTACK, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_DATTACK, 3, HG_ANGLE, 45);
set_hitbox_value(AT_DATTACK, 3, HG_ANGLE_FLIPPER, 10);
set_hitbox_value(AT_DATTACK, 3, HG_BASE_KNOCKBACK, multihit_base_kb);
set_hitbox_value(AT_DATTACK, 3, HG_BASE_HITPAUSE, multihit_hitpause);
set_hitbox_value(AT_DATTACK, 3, HG_VISUAL_EFFECT_X_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 3, HG_VISUAL_EFFECT_Y_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 3, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_DATTACK, 3, HG_TECHABLE, 3);
set_hitbox_value(AT_DATTACK, 3, HG_HITBOX_GROUP, 3);

set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 4, HG_MUNO_HITBOX_NAME, "Multihit Hitbox 1");
set_hitbox_value(AT_DATTACK, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 4, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_DATTACK, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_X, 1);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_Y, -31);
set_hitbox_value(AT_DATTACK, 4, HG_WIDTH, 88);
set_hitbox_value(AT_DATTACK, 4, HG_HEIGHT, 33);
set_hitbox_value(AT_DATTACK, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_DATTACK, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_DATTACK, 4, HG_ANGLE, 45);
set_hitbox_value(AT_DATTACK, 4, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_DATTACK, 4, HG_BASE_KNOCKBACK, multihit_base_kb);
set_hitbox_value(AT_DATTACK, 4, HG_BASE_HITPAUSE, multihit_hitpause);
set_hitbox_value(AT_DATTACK, 4, HG_VISUAL_EFFECT_X_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 4, HG_VISUAL_EFFECT_Y_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 4, HG_HIT_SFX, asset_get("sfx_blow_weak2"));
set_hitbox_value(AT_DATTACK, 4, HG_TECHABLE, 3);
set_hitbox_value(AT_DATTACK, 4, HG_HITBOX_GROUP, 4);

//finisher
set_hitbox_value(AT_DATTACK, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DATTACK, 5, HG_MUNO_HITBOX_NAME, "Finishing Hitbox");
set_hitbox_value(AT_DATTACK, 5, HG_WINDOW, 2);
set_hitbox_value(AT_DATTACK, 5, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_DATTACK, 5, HG_LIFETIME, 2);
set_hitbox_value(AT_DATTACK, 5, HG_HITBOX_X, 1);
set_hitbox_value(AT_DATTACK, 5, HG_HITBOX_Y, -31);
set_hitbox_value(AT_DATTACK, 5, HG_WIDTH, 88);
set_hitbox_value(AT_DATTACK, 5, HG_HEIGHT, 33);
set_hitbox_value(AT_DATTACK, 5, HG_PRIORITY, 2);
set_hitbox_value(AT_DATTACK, 5, HG_DAMAGE, 6);
set_hitbox_value(AT_DATTACK, 5, HG_ANGLE, 45);
set_hitbox_value(AT_DATTACK, 5, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_DATTACK, 5, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_DATTACK, 5, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(AT_DATTACK, 5, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DATTACK, 5, HG_HITPAUSE_SCALING, 0.6);
set_hitbox_value(AT_DATTACK, 5, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DATTACK, 5, HG_VISUAL_EFFECT_X_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 5, HG_VISUAL_EFFECT_Y_OFFSET, 8);
set_hitbox_value(AT_DATTACK, 5, HG_HIT_SFX, asset_get("sfx_blow_medium3"));