sprite_change_offset("idle", 37, 57, true);
sprite_change_offset("hurt", 22, 26, true);
sprite_change_offset("bighurt", 15, 22, true);
sprite_change_offset("uphurt", 8, 28, true);
sprite_change_offset("downhurt", 12, 38, true);
sprite_change_offset("bouncehurt", 16, 22, true);
sprite_change_offset("spinhurt", 22, 33, true);
sprite_change_offset("crouch", 23, 27, true);
sprite_change_offset("walk", 40, 57, true);
sprite_change_offset("walkturn", 18, 26, true);
sprite_change_offset("dash", 42, 57, true);
sprite_change_offset("dashstart", 39, 57, true);
sprite_change_offset("dashstop", 42, 57, true);
sprite_change_offset("dashturn", 27, 57, true);

sprite_change_offset("jumpstart", 16, 24, true);
sprite_change_offset("jump", 21, 29, true);
sprite_change_offset("doublejump", 20, 29, true);
sprite_change_offset("walljump", 21, 29, true);
sprite_change_offset("wallcling", 10, 24, true);
sprite_change_offset("wallslide", 10, 24, true);
sprite_change_offset("pratfall", 14, 29, true);
sprite_change_offset("land", 15, 24, true);
sprite_change_offset("landinglag", 15, 24, true);

sprite_change_offset("parry", 28, 33, true);
sprite_change_offset("roll_forward", 17, 25, true);
sprite_change_offset("roll_backward", 17, 25, true);
sprite_change_offset("airdodge", 17, 25, true);
sprite_change_offset("waveland", 22, 24, true);
sprite_change_offset("tech", 13, 27, true);

sprite_change_offset("jab", 27, 32, true);
sprite_change_offset("dattack", 25, 27, true);
sprite_change_offset("ftilt", 25, 33, true);
sprite_change_offset("dtilt", 18, 22, true);
sprite_change_offset("utilt", 31, 34, true);
sprite_change_offset("nair", 28, 27, true);
sprite_change_offset("fair", 31, 44, true);
sprite_change_offset("bair", 32, 30, true);
sprite_change_offset("uair", 20, 58, true);
sprite_change_offset("dair", 28, 46, true);
sprite_change_offset("fstrong", 17, 36, true);
sprite_change_offset("ustrong", 29, 57, true);
sprite_change_offset("dstrong", 27, 29, true);
sprite_change_offset("nspecial", 37, 45, true);
sprite_change_offset("fspecial", 25, 27, true);
sprite_change_offset("uspecial", 35, 40, true);
sprite_change_offset("dspecial", 36, 39, true);
sprite_change_offset("dspecial_steal", 22, 28, true);
sprite_change_offset("dspecial2", 22, 28, true);
sprite_change_offset("dspecial_w", 32, 58, true);
sprite_change_offset("taunt", 23, 42, true);
sprite_change_offset("taunt_ravyn", 23, 42, true);
sprite_change_offset("taunt_2", 14, 32, true);

sprite_change_offset("plat", 18, 0);

sprite_change_offset("hive_spawn", 50,70 );
sprite_change_offset("hive_empty", 36, 66 );
sprite_change_offset("hive_full", 36, 66 );
sprite_change_offset("hive_hurt", 36, 66 );
sprite_change_offset("hive_hitstun", 32, 74 );
sprite_change_offset("hive_hitstun_full", 32, 74 );
sprite_change_offset("hive_swarm_empty", 72, 92 );
sprite_change_offset("hive_swarm_full", 72, 92 );
sprite_change_offset("hive_break_empty", 48, 66 );
sprite_change_offset("hive_break_full", 64, 90 );
sprite_change_offset("money_spawn", 50,70 );
sprite_change_offset("money_empty", 36, 66 );
sprite_change_offset("money_full", 36, 66 );
sprite_change_offset("money_hurt", 36, 66 );
sprite_change_offset("money_hitstun_empty", 32, 74 );
sprite_change_offset("money_hitstun_full", 32, 74 );
sprite_change_offset("money_swarm_empty", 72, 92 );
sprite_change_offset("money_swarm_full", 72, 92 );
sprite_change_offset("money_break_empty", 48, 66 );
sprite_change_offset("money_break_full", 64, 90 );
sprite_change_offset("money_swap_empty", 80, 32 );
sprite_change_offset("money_swap_full", 80, 32 );
sprite_change_offset("cactus_spawn", 50,70 );
sprite_change_offset("cactus_empty", 44, 82 );
sprite_change_offset("cactus_full", 44, 82 );
sprite_change_offset("cactus_hurt", 36, 66 );
sprite_change_offset("cactus_hitstun_empty", 36, 80 );
sprite_change_offset("cactus_hitstun_full", 36, 80 );
sprite_change_offset("cactus_swarm_empty", 72, 92 );
sprite_change_offset("cactus_swarm_full", 72, 92 );
sprite_change_offset("cactus_break_empty", 48, 66 );
sprite_change_offset("cactus_break_full", 64, 90 );
sprite_change_offset("cactus_swap_empty", 80, 32 );
sprite_change_offset("cactus_swap_full", 80, 32 );
sprite_change_offset("after_image", 36, 46 );
sprite_change_offset("assurance", 64, 128);
sprite_change_offset("payback_vfx", 64, 32);
sprite_change_offset("quickattack_vfx", 64, 32);
sprite_change_offset("shiny", 0, 0);
sprite_change_offset("lv_up", 32, 32);
sprite_change_offset("armor_up", 32, 32);

sprite_change_offset("hfx_honey_large", 157,152 );
sprite_change_offset("hfx_big_honey", 64,68 );
sprite_change_offset("hfx_honey_small", 96,116 );

set_victory_bg(sprite_get("purrloin_victorybg"));
set_victory_theme(sound_get("vicroy"))