set_attack_value(AT_FSPECIAL, AG_CATEGORY, 2);
set_attack_value(AT_FSPECIAL, AG_SPRITE, sprite_get("fspecial"));
set_attack_value(AT_FSPECIAL, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_FSPECIAL, AG_HURTBOX_SPRITE, sprite_get("fspecial_hurt"));
set_attack_value(AT_FSPECIAL, AG_NUM_WINDOWS, 12);
set_attack_value(AT_FSPECIAL, AG_OFF_LEDGE, 1);

set_window_value(AT_FSPECIAL, 1, AG_WINDOW_LENGTH, 13 );
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 2 );
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_CUSTOM_AIR_FRICTION, 1.3 );
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 1.5);

set_window_value(AT_FSPECIAL, 2, AG_WINDOW_LENGTH, 12 );
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 2 );
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 4 );
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_HSPEED, 6);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL, 2, AG_WINDOW_SFX, asset_get("sfx_spin_longer"));

set_window_value(AT_FSPECIAL, 3, AG_WINDOW_LENGTH, 12 );
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_ANIM_FRAME_START, 2 );
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 4 );
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_HSPEED, 6);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL, 3, AG_WINDOW_HAS_SFX, 1);

set_window_value(AT_FSPECIAL, 4, AG_WINDOW_LENGTH, 12 );
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_ANIM_FRAME_START, 2 );
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_ANIM_FRAMES, 4 );
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_HSPEED, 6);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL, 4, AG_WINDOW_SFX, asset_get("sfx_spin_longer"));

set_window_value(AT_FSPECIAL, 5, AG_WINDOW_LENGTH, 12 );
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_ANIM_FRAME_START, 2 );
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_ANIM_FRAMES, 4 );
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_HSPEED, 6);
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_VSPEED, 0);
set_window_value(AT_FSPECIAL, 5, AG_WINDOW_HAS_SFX, 1);

set_window_value(AT_FSPECIAL, 6, AG_WINDOW_LENGTH, 3 );
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_ANIM_FRAME_START, 13 );
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_ANIM_FRAMES, 1 );
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_HSPEED_TYPE, 0);
set_window_value(AT_FSPECIAL, 6, AG_WINDOW_HSPEED, 1);

set_window_value(AT_FSPECIAL, 7, AG_WINDOW_LENGTH, 7 );
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_ANIM_FRAME_START, 14 );
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_ANIM_FRAMES, 2 );
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(AT_FSPECIAL, 7, AG_WINDOW_HSPEED, 5);

set_window_value(AT_FSPECIAL, 8, AG_WINDOW_LENGTH, 20 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_TYPE, 10 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_ANIM_FRAME_START, 15 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_ANIM_FRAMES, 1 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.3 );
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_HSPEED_TYPE, 2);
set_window_value(AT_FSPECIAL, 8, AG_WINDOW_HSPEED, 5);


set_window_value(AT_FSPECIAL, 9, AG_WINDOW_LENGTH, 20 );
set_window_value(AT_FSPECIAL, 9, AG_WINDOW_TYPE, 10 );
set_window_value(AT_FSPECIAL, 9, AG_WINDOW_ANIM_FRAME_START, 15 );
set_window_value(AT_FSPECIAL, 9, AG_WINDOW_ANIM_FRAMES, 1 );
set_window_value(AT_FSPECIAL, 9, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 9, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.3 );

set_window_value(AT_FSPECIAL, 10, AG_WINDOW_LENGTH, 4 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_ANIM_FRAME_START, 16 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_ANIM_FRAMES, 2 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_HAS_CUSTOM_FRICTION, 1 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_CUSTOM_AIR_FRICTION, 0.9 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_CUSTOM_GROUND_FRICTION, 1.5 );
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_CUSTOM_GRAVITY, 1.0);
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FSPECIAL, 10, AG_WINDOW_SFX, asset_get("sfx_land_med"));

set_window_value(AT_FSPECIAL, 11, AG_WINDOW_LENGTH, 4 );
set_window_value(AT_FSPECIAL, 11, AG_WINDOW_ANIM_FRAME_START, 16 );
set_window_value(AT_FSPECIAL, 11, AG_WINDOW_ANIM_FRAMES, 1 );


set_window_value(AT_FSPECIAL, 12, AG_WINDOW_LENGTH, 6 );
set_window_value(AT_FSPECIAL, 12, AG_WINDOW_ANIM_FRAME_START, 18 );
set_window_value(AT_FSPECIAL, 12, AG_WINDOW_ANIM_FRAMES, 2 );




set_num_hitboxes(AT_FSPECIAL,5);

set_hitbox_value(AT_FSPECIAL, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_X, 34);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 1, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 1, HG_HEIGHT, 76);
set_hitbox_value(AT_FSPECIAL, 1, HG_SHAPE, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, 1, HG_TECHABLE, 1);
set_hitbox_value(AT_FSPECIAL, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL, 1, HG_ANGLE, 30);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_FSPECIAL, 1, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL, 1, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_FSPECIAL, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FSPECIAL, 1, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSPECIAL, 1, HG_HITBOX_GROUP, 1); 

set_hitbox_value(AT_FSPECIAL, 2, HG_PARENT_HITBOX, 1);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL, 2, HG_WINDOW, 3);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_X, 34);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 2, HG_TECHABLE, 1);
set_hitbox_value(AT_FSPECIAL, 2, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 2, HG_HEIGHT, 76);
set_hitbox_value(AT_FSPECIAL, 2, HG_SHAPE, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL, 2, HG_ANGLE, 30);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_FSPECIAL, 2, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL, 2, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_FSPECIAL, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FSPECIAL, 2, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSPECIAL, 2, HG_HITBOX_GROUP, 2); 

set_hitbox_value(AT_FSPECIAL, 3, HG_PARENT_HITBOX, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL, 3, HG_WINDOW, 4);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_X, 34);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 3, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 3, HG_HEIGHT, 76);
set_hitbox_value(AT_FSPECIAL, 3, HG_SHAPE, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL, 3, HG_ANGLE, 30);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_FSPECIAL, 3, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL, 3, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_FSPECIAL, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FSPECIAL, 3, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_TECHABLE, 1);
set_hitbox_value(AT_FSPECIAL, 3, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSPECIAL, 3, HG_HITBOX_GROUP, 3); 

set_hitbox_value(AT_FSPECIAL, 4, HG_PARENT_HITBOX, 3);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL, 4, HG_WINDOW, 5);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_X, 34);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 4, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 4, HG_HEIGHT, 76);
set_hitbox_value(AT_FSPECIAL, 4, HG_SHAPE, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, 4, HG_DAMAGE, 3);
set_hitbox_value(AT_FSPECIAL, 4, HG_ANGLE, 30);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_KNOCKBACK, 7.5);
set_hitbox_value(AT_FSPECIAL, 4, HG_KNOCKBACK_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL, 4, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_FSPECIAL, 4, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_FSPECIAL, 4, HG_ANGLE_FLIPPER, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_HIT_LOCKOUT, 0);
set_hitbox_value(AT_FSPECIAL, 4, HG_TECHABLE, 1);
set_hitbox_value(AT_FSPECIAL, 4, HG_HITBOX_GROUP, -1); 

set_hitbox_value(AT_FSPECIAL, 5, HG_PARENT_HITBOX, 5);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FSPECIAL, 5, HG_WINDOW, 6);
set_hitbox_value(AT_FSPECIAL, 5, HG_LIFETIME, 3);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITBOX_X, 34);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITBOX_Y, -32);
set_hitbox_value(AT_FSPECIAL, 5, HG_WIDTH, 60);
set_hitbox_value(AT_FSPECIAL, 5, HG_HEIGHT, 76);
set_hitbox_value(AT_FSPECIAL, 5, HG_SHAPE, 2);
set_hitbox_value(AT_FSPECIAL, 5, HG_PRIORITY, 2);
set_hitbox_value(AT_FSPECIAL, 5, HG_DAMAGE, 4);
set_hitbox_value(AT_FSPECIAL, 5, HG_ANGLE, 30);
set_hitbox_value(AT_FSPECIAL, 5, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_FSPECIAL, 5, HG_KNOCKBACK_SCALING, 0.7);
set_hitbox_value(AT_FSPECIAL, 5, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_FSPECIAL, 5, HG_HITPAUSE_SCALING, 1.0);
set_hitbox_value(AT_FSPECIAL, 5, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_FSPECIAL, 5, HG_VISUAL_EFFECT_Y_OFFSET, 20);
set_hitbox_value(AT_FSPECIAL, 5, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_FSPECIAL, 5, HG_HITBOX_GROUP, -1); 
