set_attack_value(AT_USPECIAL_2, AG_CATEGORY, 2);

set_num_hitboxes(AT_USPECIAL_2, 2);

set_hitbox_value(AT_USPECIAL_2, 1, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL_2, 1, HG_WINDOW, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_LIFETIME, 50);
set_hitbox_value(AT_USPECIAL_2, 1, HG_WIDTH, 34);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_USPECIAL_2, 1, HG_SHAPE, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_DAMAGE, 5);
set_hitbox_value(AT_USPECIAL_2, 1, HG_ANGLE, 270);
set_hitbox_value(AT_USPECIAL_2, 1, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_USPECIAL_2, 1, HG_KNOCKBACK_SCALING, 0.6);
set_hitbox_value(AT_USPECIAL_2, 1, HG_BASE_HITPAUSE, 4);
set_hitbox_value(AT_USPECIAL_2, 1, HG_TECHABLE, 2);
set_hitbox_value(AT_USPECIAL_2, 1, HG_VISUAL_EFFECT, 305);
set_hitbox_value(AT_USPECIAL_2, 1, HG_HIT_SFX, asset_get("sfx_clairen_hit_med"));
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_SPRITE, sprite_get("pandy_uboltnew"));
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_VSPEED, 50);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_ANIM_SPEED, 0.3);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_WALL_BEHAVIOR, 0);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_USPECIAL_2, 1, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_USPECIAL_2, 1, HG_PROJECTILE_DESTROY_EFFECT, hfx_elecbig);

//blast
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITBOX_TYPE, 2);
set_hitbox_value(AT_USPECIAL_2, 2, HG_WINDOW, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_USPECIAL_2, 2, HG_WIDTH, 125);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HEIGHT, 120);
set_hitbox_value(AT_USPECIAL_2, 2, HG_SHAPE, 0);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PRIORITY, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_DAMAGE, 8);
set_hitbox_value(AT_USPECIAL_2, 2, HG_ANGLE, 90);
set_hitbox_value(AT_USPECIAL_2, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_USPECIAL_2, 2, HG_KNOCKBACK_SCALING, 1.0);
set_hitbox_value(AT_USPECIAL_2, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HITPAUSE_SCALING, 0.8);
set_hitbox_value(AT_USPECIAL_2, 2, HG_VISUAL_EFFECT, hfx_elecbig);
set_hitbox_value(AT_USPECIAL_2, 2, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"));
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_SPRITE, asset_get("empty_sprite"));
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_MASK, -1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_ANIM_SPEED, 0);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_WALL_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_GROUND_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_ENEMY_BEHAVIOR, 1);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_PARRY_STUN, true);
set_hitbox_value(AT_USPECIAL_2, 2, HG_EXTENDED_PARRY_STUN, true);
set_hitbox_value(AT_USPECIAL_2, 2, HG_PROJECTILE_DESTROY_EFFECT, 1);