set_attack_value(AT_EXTRA_1, AG_CATEGORY, 2);
set_attack_value(AT_EXTRA_1, AG_SPRITE, sprite_get("nspecial2"));
set_attack_value(AT_EXTRA_1, AG_NUM_WINDOWS, 1);
set_attack_value(AT_EXTRA_1, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_EXTRA_1, AG_LANDING_LAG, 5);
set_attack_value(AT_EXTRA_1, AG_HURTBOX_SPRITE, sprite_get("empty"));

set_window_value(AT_EXTRA_1, 1, AG_WINDOW_LENGTH, 4*7);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy1"));
set_window_value(AT_EXTRA_1, 1, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_1, 2, AG_WINDOW_LENGTH, 4*5);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy1"));
set_window_value(AT_EXTRA_1, 2, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_1, 3, AG_WINDOW_LENGTH, 4*9);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAMES, 8);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_ANIM_FRAME_START, 13);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy1"));
set_window_value(AT_EXTRA_1, 3, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_1, 4, AG_WINDOW_LENGTH, 4*5);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_ANIM_FRAME_START, 21);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy1"));
set_window_value(AT_EXTRA_1, 4, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_1, 5, AG_WINDOW_LENGTH, 4*5);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_ANIM_FRAME_START, 21);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy1"));
set_window_value(AT_EXTRA_1, 5, AG_WINDOW_SFX_FRAME, 1);

set_window_value(AT_EXTRA_1, 6, AG_WINDOW_LENGTH, 6*6);
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_ANIM_FRAMES, 6);
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_ANIM_FRAME_START, 26);
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy2"));
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_SFX_FRAME, 1);
set_window_value(AT_EXTRA_1, 6, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);

set_window_value(AT_EXTRA_1, 7, AG_WINDOW_LENGTH, 5*7);
set_window_value(AT_EXTRA_1, 7, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_EXTRA_1, 7, AG_WINDOW_ANIM_FRAME_START, 32);
set_window_value(AT_EXTRA_1, 7, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_EXTRA_1, 7, AG_WINDOW_SFX, asset_get("sfx_shovel_swing_heavy2"));
set_window_value(AT_EXTRA_1, 7, AG_WINDOW_SFX_FRAME, 1);

set_num_hitboxes(AT_EXTRA_1, 8);

set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW, 1);
set_hitbox_value(AT_EXTRA_1, 1, HG_WINDOW_CREATION_FRAME, 4*4);
set_hitbox_value(AT_EXTRA_1, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_1, 1, HG_WIDTH, 106);
set_hitbox_value(AT_EXTRA_1, 1, HG_HEIGHT, 106);
set_hitbox_value(AT_EXTRA_1, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 1, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_EXTRA_1, 1, HG_ANGLE, 65);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_1, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 1, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_1, 1, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 1, HG_HIT_SFX, asset_get("sfx_crunch"));
set_hitbox_value(AT_EXTRA_1, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 1, HG_HITSTUN_MULTIPLIER, 1);

set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_WINDOW_CREATION_FRAME, 4*2);
set_hitbox_value(AT_EXTRA_1, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_1, 2, HG_WIDTH, 106);
set_hitbox_value(AT_EXTRA_1, 2, HG_HEIGHT, 106);
set_hitbox_value(AT_EXTRA_1, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 2, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_DAMAGE, 4);
set_hitbox_value(AT_EXTRA_1, 2, HG_ANGLE, 75);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_1, 2, HG_BASE_HITPAUSE, 5);
set_hitbox_value(AT_EXTRA_1, 2, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_1, 2, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(AT_EXTRA_1, 2, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 2, HG_HITSTUN_MULTIPLIER, 1);

set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_WINDOW_CREATION_FRAME, 4*2);
set_hitbox_value(AT_EXTRA_1, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_X, 30);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_Y, -52);
set_hitbox_value(AT_EXTRA_1, 3, HG_WIDTH, 106);
set_hitbox_value(AT_EXTRA_1, 3, HG_HEIGHT, 106);
set_hitbox_value(AT_EXTRA_1, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 3, HG_SHAPE, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 3, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(AT_EXTRA_1, 3, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 3, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_1, 3, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 3, HG_HIT_SFX, asset_get("sfx_blow_medium1"));
set_hitbox_value(AT_EXTRA_1, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 3, HG_HITSTUN_MULTIPLIER, .5);

set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_1, 4, HG_WINDOW_CREATION_FRAME, 4*5);
set_hitbox_value(AT_EXTRA_1, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_Y, -142);
set_hitbox_value(AT_EXTRA_1, 4, HG_WIDTH, 66);
set_hitbox_value(AT_EXTRA_1, 4, HG_HEIGHT, 126);
set_hitbox_value(AT_EXTRA_1, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 4, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_EXTRA_1, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_EXTRA_1, 4, HG_EXTRA_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_1, 4, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 4, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));
set_hitbox_value(AT_EXTRA_1, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 4, HG_HITSTUN_MULTIPLIER, 3);

set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_1, 5, HG_WINDOW_CREATION_FRAME, 4*6);
set_hitbox_value(AT_EXTRA_1, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_Y, -162);
set_hitbox_value(AT_EXTRA_1, 5, HG_WIDTH, 66);
set_hitbox_value(AT_EXTRA_1, 5, HG_HEIGHT, 166);
set_hitbox_value(AT_EXTRA_1, 5, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_KNOCKBACK, 2);
set_hitbox_value(AT_EXTRA_1, 5, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_EXTRA_1, 5, HG_EXTRA_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_1, 5, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 5, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));
set_hitbox_value(AT_EXTRA_1, 5, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 5, HG_HITSTUN_MULTIPLIER, 2);

set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_WINDOW, 3);
set_hitbox_value(AT_EXTRA_1, 6, HG_WINDOW_CREATION_FRAME, 4*7);
set_hitbox_value(AT_EXTRA_1, 6, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_Y, -182);
set_hitbox_value(AT_EXTRA_1, 6, HG_WIDTH, 66);
set_hitbox_value(AT_EXTRA_1, 6, HG_HEIGHT, 206);
set_hitbox_value(AT_EXTRA_1, 6, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 6, HG_DAMAGE, 1);
set_hitbox_value(AT_EXTRA_1, 6, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 6, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_1, 6, HG_BASE_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_EXTRA_HITPAUSE, 0);
set_hitbox_value(AT_EXTRA_1, 6, HG_VISUAL_EFFECT, 303);
set_hitbox_value(AT_EXTRA_1, 6, HG_HIT_SFX, asset_get("sfx_ori_energyhit_medium"));
set_hitbox_value(AT_EXTRA_1, 6, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 6, HG_HITSTUN_MULTIPLIER, 1.1);


set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 7, HG_WINDOW, 4);
set_hitbox_value(AT_EXTRA_1, 7, HG_WINDOW_CREATION_FRAME, 4*2);
set_hitbox_value(AT_EXTRA_1, 7, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_X, 0);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_Y, -72);
set_hitbox_value(AT_EXTRA_1, 7, HG_WIDTH, 86);
set_hitbox_value(AT_EXTRA_1, 7, HG_HEIGHT, 116);
set_hitbox_value(AT_EXTRA_1, 7, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 7, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 7, HG_BASE_KNOCKBACK, 11);
set_hitbox_value(AT_EXTRA_1, 7, HG_KNOCKBACK_SCALING, .2);
set_hitbox_value(AT_EXTRA_1, 7, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_EXTRA_1, 7, HG_EXTRA_HITPAUSE, 6);
set_hitbox_value(AT_EXTRA_1, 7, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_1, 7, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_EXTRA_1, 7, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 7, HG_HITSTUN_MULTIPLIER, 1);

set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_WINDOW, 6);
set_hitbox_value(AT_EXTRA_1, 8, HG_WINDOW_CREATION_FRAME, 6*3);
set_hitbox_value(AT_EXTRA_1, 8, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_Y, -82);
set_hitbox_value(AT_EXTRA_1, 8, HG_WIDTH, 106);
set_hitbox_value(AT_EXTRA_1, 8, HG_HEIGHT, 86);
set_hitbox_value(AT_EXTRA_1, 8, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 8, HG_ANGLE, 40);
set_hitbox_value(AT_EXTRA_1, 8, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_EXTRA_1, 8, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_EXTRA_1, 8, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_1, 8, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_HIT_SFX, asset_get("sfx_swipe_heavy2"));
set_hitbox_value(AT_EXTRA_1, 8, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 8, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 8, HG_SDI_MULTIPLIER, 0.001);
set_hitbox_value(AT_EXTRA_1, 8, HG_EXTRA_CAMERA_SHAKE, -1);

set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_WINDOW, 7);
set_hitbox_value(AT_EXTRA_1, 9, HG_WINDOW_CREATION_FRAME, 5*3);
set_hitbox_value(AT_EXTRA_1, 9, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_Y, -42);
set_hitbox_value(AT_EXTRA_1, 9, HG_WIDTH, 106);
set_hitbox_value(AT_EXTRA_1, 9, HG_HEIGHT, 86);
set_hitbox_value(AT_EXTRA_1, 9, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_DAMAGE, 2);
set_hitbox_value(AT_EXTRA_1, 9, HG_ANGLE, 270);
set_hitbox_value(AT_EXTRA_1, 9, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_EXTRA_1, 9, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_EXTRA_1, 9, HG_BASE_HITPAUSE, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_HITPAUSE_SCALING, 0);
set_hitbox_value(AT_EXTRA_1, 9, HG_VISUAL_EFFECT, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_HIT_SFX, asset_get("sfx_swipe_heavy2"));
set_hitbox_value(AT_EXTRA_1, 9, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 9, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 9, HG_EXTRA_CAMERA_SHAKE, -1);

set_hitbox_value(AT_EXTRA_1, 10, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_EXTRA_1, 10, HG_WINDOW, 7);
set_hitbox_value(AT_EXTRA_1, 10, HG_WINDOW_CREATION_FRAME, 5*3);
set_hitbox_value(AT_EXTRA_1, 10, HG_LIFETIME, 4);
set_hitbox_value(AT_EXTRA_1, 10, HG_HITBOX_X, 20);
set_hitbox_value(AT_EXTRA_1, 10, HG_HITBOX_Y, -42);
set_hitbox_value(AT_EXTRA_1, 10, HG_WIDTH, 86);
set_hitbox_value(AT_EXTRA_1, 10, HG_HEIGHT, 86);
set_hitbox_value(AT_EXTRA_1, 10, HG_PRIORITY, 2);
set_hitbox_value(AT_EXTRA_1, 10, HG_SHAPE, 2);
set_hitbox_value(AT_EXTRA_1, 10, HG_DAMAGE, 6);
set_hitbox_value(AT_EXTRA_1, 10, HG_ANGLE, 90);
set_hitbox_value(AT_EXTRA_1, 10, HG_BASE_KNOCKBACK, 9);
set_hitbox_value(AT_EXTRA_1, 10, HG_KNOCKBACK_SCALING, 1);
set_hitbox_value(AT_EXTRA_1, 10, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_EXTRA_1, 10, HG_HITPAUSE_SCALING, 0.7);
set_hitbox_value(AT_EXTRA_1, 10, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_EXTRA_1, 10, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_EXTRA_1, 10, HG_HITBOX_GROUP, -1);
set_hitbox_value(AT_EXTRA_1, 10, HG_HITSTUN_MULTIPLIER, 1);
set_hitbox_value(AT_EXTRA_1, 10, HG_VISUAL_EFFECT_Y_OFFSET, 40);
